### ISSUE TITLE
error missing script: ghost

### ISSUE THREAD

**Issue by captainhook** [TryGhost/Ghost-CLI#1007]
Hi,
I am running Ghost under Plesk's Node.js

To install Ghost-CLI I have used 
```
sudo /opt/plesk/node/10/bin/npm install ghost-cli@latest
```

When running 'ghost' command, I get:

```
0 info it worked if it ends with ok
1 verbose cli [ '/opt/plesk/node/10/bin/node',                      1 verbose cli   '/opt/plesk/node/10/bin/npm',
1 verbose cli   'run',                                              1 verbose cli   'ghost' ]
2 info using npm@6.9.0                                              3 info using node@v10.16.0
4 verbose stack Error: missing script: ghost
4 verbose stack     at run (/opt/plesk/node/10/lib/node_modules/npm/lib/run-script.js:155:19)                                           4 verbose stack     at /opt/plesk/node/10/lib/node_modules/npm/lib/run-script.js:63:5                                                   4 verbose stack     at /opt/plesk/node/10/lib/node_modules/npm/node_modules/read-package-json/read-json.js:115:5                        4 verbose stack     at /opt/plesk/node/10/lib/node_modules/npm/node_modules/read-package-json/read-json.js:418:5                        4 verbose stack     at checkBinReferences_ (/opt/plesk/node/10/lib/node_modules/npm/node_modules/read-package-json/read-json.js:373:45) 4 verbose stack     at final (/opt/plesk/node/10/lib/node_modules/npm/node_modules/read-package-json/read-json.js:416:3)                4 verbose stack     at then (/opt/plesk/node/10/lib/node_modules/npm/node_modules/read-package-json/read-json.js:160:5)                 4 verbose stack     at /opt/plesk/node/10/lib/node_modules/npm/node_modules/read-package-json/read-json.js:280:12                       4 verbose stack     at /opt/plesk/node/10/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:90:16                            4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)                             5 verbose cwd /var/www/vhosts/DOMAIN.com/httpdocs/ghost             6 verbose Linux 3.10.0-957.27.2.el7.x86_64                          7 verbose argv "/opt/plesk/node/10/bin/node" "/opt/plesk/node/10/bin/npm" "run" "ghost"                                                 8 verbose node v10.16.0
9 verbose npm  v6.9.0                                               10 error missing script: ghost                                      11 verbose exit [ 1, true ]                                         ~                                                                   ~                                                                   ~                                                                   ~                                                                   ~                                                                   ~                                                                   ~                                                                   ~                                                                                                                     25,1          All
```
  

Rather new to node.js, would appreciate any tips to correct this.

Many thanks

**Comment by acburdine** [comment]
@captainhook my guess is that you need to run `npm install -g ghost-cli@latest` to get `ghost` to install globally, but I'm unfamiliar with how plesk works, so that's all I can offer.

Going to close this issue as this appears to be an issue specific to plesk's setup. If you are still experiencing errors, please reach out in our [forum](https://forum.ghost.org). If it _does_ turn out to be an issue that can be resolved in the CLI, we can re-open this issue 😄
