### ISSUE TITLE
Could not communicate with Ghost | Can't connect to the bootstrap socket (localhost 8000) ECONNREFUSED

### ISSUE THREAD

**Issue by Jyodsh** [TryGhost/Ghost-CLI#1019]
My ghost instance appears to be broken. 
Here is the output of ghost doctor

```
jyothish@localhost:/var/www/ghost$ ghost doctor -V
[16:26:41] Checking system Node.js version [started]
[16:26:41] Checking system Node.js version [completed]
[16:26:41] Checking logged in user [started]
[16:26:41] Checking logged in user [completed]
[16:26:41] Ensuring user is not logged in as ghost user [started]
[16:26:41] Ensuring user is not logged in as ghost user [completed]
[16:26:41] Checking if logged in user is directory owner [started]
[16:26:41] Checking if logged in user is directory owner [completed]
[16:26:41] Checking current folder permissions [started]
[16:26:41] Checking current folder permissions [completed]
[16:26:41] Checking operating system compatibility [started]
[16:26:41] Checking systemd is installed [started]
[16:26:41] Checking nginx is installed [started]
[16:26:41] Checking systemd is installed [completed]
[16:26:41] Checking nginx is installed [completed]
[16:26:41] Checking operating system compatibility [completed]
[16:26:41] Checking for a MySQL installation [started]
[16:26:41] Checking for a MySQL installation [completed]
[16:26:41] Validating config [started]
+ sudo systemctl is-active ghost_www-thakshashila-com
+ sudo systemctl reset-failed ghost_www-thakshashila-com
[16:26:41] Validating config [completed]
[16:26:41] Checking folder permissions [started]
[16:26:41] Checking folder permissions [completed]
[16:26:41] Checking file permissions [started]
[16:26:42] Checking file permissions [completed]
[16:26:42] Checking content folder ownership [started]
[16:26:42] Checking content folder ownership [completed]
[16:26:42] Checking memory availability [started]
[16:26:42] Checking memory availability [completed]

```

Output of ghost start 

```
jyothish@localhost:/var/www/ghost$ ghost start 
+ sudo systemctl is-active ghost_www-thakshashila-com
✔ Ensuring user is not logged in as ghost user
✔ Checking if logged in user is directory owner
✔ Checking current folder permissions
+ sudo systemctl is-active ghost_www-thakshashila-com
✔ Validating config
✔ Checking folder permissions
✔ Checking file permissions
✔ Checking content folder ownership
✔ Checking memory availability
+ sudo systemctl start ghost_www-thakshashila-com
☲ Starting Ghost
+ sudo systemctl stop ghost_www-thakshashila-com
✖ Starting Ghost
A GhostError occurred.

Message: Could not communicate with Ghost
Suggestion: journalctl -u ghost_www-thakshashila-com -n 50

Debug Information:
    OS: Ubuntu, v16.04
    Node Version: v8.9.0
    Ghost-CLI Version: 1.11.0
    Environment: production
    Command: 'ghost start'

Additional log info available in: /home/jyothish/.ghost/logs/ghost-cli-debug-2019-10-13T11_04_33_367Z.log
```

Logs fetched after a failed Ghost start command 

```
jyothish@localhost:/var/www/ghost$ tail -f /home/jyothish/.ghost/logs/ghost-cli-debug-2019-10-13T11_04_33_367Z.log
Suggestion: journalctl -u ghost_www-thakshashila-com -n 50
Stack: Error: Could not communicate with Ghost
    at Server.server.close (/usr/local/lib/node_modules/ghost-cli/lib/utils/port-polling.js:56:20)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Server.emit (events.js:208:7)
    at emitCloseNT (net.js:1655:8)
    at _combinedTickCallback (internal/process/next_tick.js:135:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

```

Console output after running ghost run command
```

jyothish@localhost:/var/www/ghost$ ghost run 
The `ghost run` command is used by the configured Ghost process manager and for debugging. If you're not running this to debug something, you should run `ghost start` instead.
+ sudo node current/index.js
[2019-10-13 11:08:28] INFO Ghost is running in production...
[2019-10-13 11:08:28] INFO Your site is now available on http://thakshashila.com/
[2019-10-13 11:08:28] INFO Ctrl+C to shut down
[2019-10-13 11:08:28] WARN Can't connect to the bootstrap socket (localhost 8000) ECONNREFUSED
[2019-10-13 11:08:28] WARN Tries: 0
[2019-10-13 11:08:28] WARN Retrying...
[2019-10-13 11:08:28] WARN Can't connect to the bootstrap socket (localhost 8000) ECONNREFUSED
[2019-10-13 11:08:28] WARN Tries: 1
[2019-10-13 11:08:28] WARN Retrying...
[2019-10-13 11:08:29] WARN Can't connect to the bootstrap socket (localhost 8000) ECONNREFUSED
[2019-10-13 11:08:29] WARN Tries: 2
[2019-10-13 11:08:29] WARN Retrying...
[2019-10-13 11:08:29] WARN Can't connect to the bootstrap socket (localhost 8000) ECONNREFUSED
[2019-10-13 11:08:29] INFO Ghost boot 4.571s



```

**Comment by acburdine** [comment]
@Jyodsh My guess is that this is related to #805 - can you try removing the "bootstrap-socket" section from your Ghost config to see if that fixes the problem?

**Comment by Jyodsh** [comment]
Thanks @acburdine .
I removed the the following lines from  config.production.json
  "bootstrap-socket": {
    "port": 8000,
    "host": "localhost"
  }

But  still the site is  not starting with `ghost start` . What I observed `ghost start` adding back the bootstrap-scoket lines (which i removed) to  config.production.json. 

note: if I run  `ghost run` site is working perfectly.

**Comment by Jyodsh** [comment]
Later I found that the issue is with the node version. ghost-cli was not taking version updated with nvm.
I've updated the nodejs version by following the steps mentioned [here](https://ghost.org/faq/node-versions/) and it worked.

**Comment by filipencus** [comment]
> Later I found that the issue is with the node version. ghost-cli was not taking version updated with nvm.
> I've updated the nodejs version by following the steps mentioned [here](https://ghost.org/faq/node-versions/) and it worked.

I cant upgrade nodejs because of other services already running in the same server. another workaraound?
