### ISSUE TITLE
Could not communicate with Ghost

### ISSUE THREAD

**Issue by sixteener** [TryGhost/Ghost-CLI#1028]
Debug Information:
    OS: Ubuntu, v16.04
    Node Version: v10.17.0
    Ghost-CLI Version: 1.12.0
    Environment: production
    Command: 'ghost install --no-stack'
Message: Could not communicate with Ghost
Suggestion: journalctl -u ghost_localhost -n 50
Stack: Error: Could not communicate with Ghost
    at Server.server.close (/usr/lib/node_modules/ghost-cli/lib/utils/port-polling.js:56:20)
    at Object.onceWrapper (events.js:286:20)
    at Server.emit (events.js:198:13)
    at emitCloseNT (net.js:1619:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by sooxt98** [comment]
https://forum.ghost.org/t/getting-error-when-trying-to-upgrade-to-ghost-3-x/13636/2
