### ISSUE TITLE
when install local report error

### ISSUE THREAD

**Issue by zaxayn** [TryGhost/Ghost-CLI#1070]
The log:
Debug Information:
    OS: Mac OS X, v10.14.6
    Node Version: v12.11.0
    Ghost Version: 3.1.0
    Ghost-CLI Version: 1.13.1
    Environment: development
    Command: 'ghost install local'
Message: Ghost process exited with code: 0
Stack: Error: Ghost process exited with code: 0
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/ghost-cli/lib/utils/local-process.js:56:24)
    at ChildProcess.emit (events.js:210:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)

**Comment by zaxayn** [comment]
the error occur when i run: ghost install local

**Comment by zaxayn** [comment]
192:ghost yun$ ghost doctor
Found a development config but not a production config, running in development mode instead
✔ Checking system Node.js version
✔ Checking current folder permissions
✔ Validating config
✔ Checking memory availability
✔ Checking binary dependencies
192:ghost yun$

**Comment by mrusme** [comment]
Please find a possible solution (or at least some hints on how to further debug this) in #1103.

**Comment by vikaspotluri123** [comment]
@zaxayn a new version of the CLI has been released that includes a better error message. Can you please update your CLI, try installing Ghost again, and sharing the output?
