### ISSUE TITLE
Stack: Error: Ghost process exited with code: 0

### ISSUE THREAD

**Issue by DennisAhaus** [TryGhost/Ghost-CLI#1103]
Enter ghost-install-dir and execute `ghost restart` then I got following message:

<pre>
Debug Information:
    OS: Ubuntu, v16.04.6 LTS
    Node Version: v12.14.1
    Ghost Version: 3.3.0
    Ghost-CLI Version: 1.13.1
    Environment: production
    Command: 'ghost start --enable'
Message: Ghost process exited with code: 0
Stack: Error: Ghost process exited with code: 0
    at ChildProcess.<anonymous> (/home/dennis/.nvm/versions/node/v12.14.1/lib/node_modules/ghost-cli/lib/utils/local-process.js:56:24)
    at ChildProcess.emit (events.js:223:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
</pre>
 
The corresponding log file shows the same text.

Can not start the instance anyways. Website is down! Any ideas?

**Comment by mrusme** [comment]
Same on MacOS:

```
✔ Checking system Node.js version
✔ Checking current folder permissions
✔ Checking memory availability
✔ Checking for latest Ghost version
✔ Setting up install directory
✔ Downloading and installing Ghost v3.13.3
✔ Finishing install process
✔ Configuring Ghost
✔ Setting up instance
✖ Starting Ghost
One or more errors occurred.

1) GhostError

Message: Ghost process exited with code: 0

Debug Information:
    OS: Mac OS X, v10.15.4
    Node Version: v12.16.1
    Ghost Version: 3.13.3
    Ghost-CLI Version: 1.13.1
    Environment: development
    Command: 'ghost install local'

Additional log info available in: ~/.ghost/logs/ghost-cli-debug-2020-04-20T10_02_14_245Z.log

Try running ghost doctor to check your system for known issues.
```

```
Debug Information:
    OS: Mac OS X, v10.15.4
    Node Version: v12.16.1
    Ghost Version: 3.13.3
    Ghost-CLI Version: 1.13.1
    Environment: development
    Command: 'ghost install local'
Message: Ghost process exited with code: 0
Stack: Error: Ghost process exited with code: 0
    at ChildProcess.<anonymous> (~/.nvm/versions/node/v12.16.1/lib/node_modules/ghost-cli/lib/utils/local-process.js:56:24)
    at ChildProcess.emit (events.js:311:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
```

**Comment by mrusme** [comment]
Looks like this issue appears several times in this issue-tracker, but there is no obvious solution to it: #1120 #1070 #1066 #827 

Maybe one of the maintainers could go through, merge and provide a solution this? /cc @acburdine @ErisDS

**Comment by mrusme** [comment]
`ghost run -V` doesn't tell a lot more apart of issues with `DTraceProviderBindings`:

```
ghost run -V
The `ghost run` command is used by the configured Ghost process manager and for debugging. If you're not running this to debug something, you should run `ghost start` instead.
dyld: lazy symbol binding failed: Symbol not found: _usdt_create_provider
  Referenced from: /.../ghost/versions/3.13.3/node_modules/dtrace-provider/src/build/Release/DTraceProviderBindings.node
  Expected in: flat namespace

dyld: Symbol not found: _usdt_create_provider
  Referenced from: /.../ghost/versions/3.13.3/node_modules/dtrace-provider/src/build/Release/DTraceProviderBindings.node
  Expected in: flat namespace
```

Tried `cd`ing into `versions/<current-version>/` and running `npm install`, which completed just fine. Not sure what's wrong here.

**Comment by mrusme** [comment]
Apparently the previous `dyld` issue has something to do with `binutils` installed via `homebrew` on macOS. To fix that error one can simply run (for now):

`brew uninstall binutils`

Then `cd` into `versions/<current-version>/`, `rm -rf node_modules` and `npm install`. After that, the output looks different:

```
The `ghost run` command is used by the configured Ghost process manager and for debugging. If you're not running this to debug something, you should run `ghost start` instead.
[2020-04-20 11:36:24] ERROR connect ECONNREFUSED 127.0.0.1:3306

connect ECONNREFUSED 127.0.0.1:3306

"Unknown database error"

Error ID:
    500

Error Code:
    ECONNREFUSED

----------------------------------------

DatabaseError: connect ECONNREFUSED 127.0.0.1:3306
    at DatabaseError.KnexMigrateError (/.../ghost/versions/3.13.3/node_modules/knex-migrator/lib/errors.js:7:26)
    at new DatabaseError (/.../ghost/versions/3.13.3/node_modules/knex-migrator/lib/errors.js:55:26)
    at /.../ghost/versions/3.13.3/node_modules/knex-migrator/lib/database.js:47:19

Error: connect ECONNREFUSED 127.0.0.1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16)
    --------------------
    at Protocol._enqueue (/.../ghost/versions/3.13.3/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/.../ghost/versions/3.13.3/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at Connection.connect (/.../ghost/versions/3.13.3/node_modules/mysql/lib/Connection.js:116:18)
    at /.../ghost/versions/3.13.3/node_modules/knex/lib/dialects/mysql/index.js:68:18
    at Promise._execute (/.../ghost/versions/3.13.3/node_modules/bluebird/js/release/debuggability.js:384:9)
    at Promise._resolveFromExecutor (/.../ghost/versions/3.13.3/node_modules/bluebird/js/release/promise.js:518:18)
    at new Promise (/.../ghost/versions/3.13.3/node_modules/bluebird/js/release/promise.js:103:10)
    at Client_MySQL.acquireRawConnection (/.../ghost/versions/3.13.3/node_modules/knex/lib/dialects/mysql/index.js:63:12)
    at create (/.../ghost/versions/3.13.3/node_modules/knex/lib/client.js:289:39)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Has anyone on macOS actually ever tested this ghost-cli package? 🤔 Looks like it's super immature. In order to fix this issue I did the following:

`cp config.development.json config.production.json`

After that `ghost run -V` looked like this:

```
The `ghost run` command is used by the configured Ghost process manager and for debugging. If you're not running this to debug something, you should run `ghost start` instead.
[2020-04-20 11:39:41] INFO Creating table: posts
[2020-04-20 11:39:41] INFO Creating table: posts_meta
[2020-04-20 11:39:41] INFO Creating table: users
[2020-04-20 11:39:41] INFO Creating table: posts_authors
[2020-04-20 11:39:41] INFO Creating table: roles
[2020-04-20 11:39:41] INFO Creating table: roles_users
[2020-04-20 11:39:41] INFO Creating table: permissions
[2020-04-20 11:39:41] INFO Creating table: permissions_users
[2020-04-20 11:39:41] INFO Creating table: permissions_roles
[2020-04-20 11:39:41] INFO Creating table: permissions_apps
[2020-04-20 11:39:41] INFO Creating table: settings
[2020-04-20 11:39:41] INFO Creating table: tags
[2020-04-20 11:39:41] INFO Creating table: posts_tags
[2020-04-20 11:39:41] INFO Creating table: apps
[2020-04-20 11:39:41] INFO Creating table: app_settings
[2020-04-20 11:39:41] INFO Creating table: app_fields
[2020-04-20 11:39:41] INFO Creating table: invites
[2020-04-20 11:39:41] INFO Creating table: brute
[2020-04-20 11:39:41] INFO Creating table: webhooks
[2020-04-20 11:39:41] INFO Creating table: sessions
[2020-04-20 11:39:41] INFO Creating table: integrations
[2020-04-20 11:39:41] INFO Creating table: api_keys
[2020-04-20 11:39:41] INFO Creating table: mobiledoc_revisions
[2020-04-20 11:39:41] INFO Creating table: members
[2020-04-20 11:39:41] INFO Creating table: labels
[2020-04-20 11:39:41] INFO Creating table: members_labels
[2020-04-20 11:39:41] INFO Creating table: members_stripe_customers
[2020-04-20 11:39:41] INFO Creating table: members_stripe_customers_subscriptions
[2020-04-20 11:39:41] INFO Creating table: actions
[2020-04-20 11:39:41] INFO Creating table: emails
[2020-04-20 11:39:41] INFO Model: Tag
[2020-04-20 11:39:41] INFO Model: Role
[2020-04-20 11:39:41] INFO Model: Permission
[2020-04-20 11:39:41] INFO Model: User
[2020-04-20 11:39:42] INFO Model: Post
[2020-04-20 11:39:42] INFO Model: Integration
[2020-04-20 11:39:42] INFO Relation: Role to Permission
[2020-04-20 11:39:42] INFO Relation: Post to Tag
[2020-04-20 11:39:42] INFO Relation: User to Role
[2020-04-20 11:39:44] INFO Ghost is running in production...
[2020-04-20 11:39:44] INFO Your site is now available on http://localhost:2368/
[2020-04-20 11:39:44] INFO Ctrl+C to shut down
[2020-04-20 11:39:44] INFO Ghost boot 3.902s
```

And likewise `ghost start` now successfully boots:

```
ghost start
✔ Checking current folder permissions
✔ Validating config
✔ Checking memory availability
✔ Checking binary dependencies
✔ Starting Ghost: ghost-local

------------------------------------------------------------------------------

Your admin interface is located at:

    http://localhost:2368/ghost/
```

**Comment by ErisDS** [comment]
> Has anyone on macOS actually ever tested this ghost-cli package?

This kind of snark is not appreciated here. The Ghost team uses this package constantly, however this is a community-run project.

Ghost-CLI is not intended to do a production install on Mac or Windows. Production is geared towards Ubuntu only.

**Comment by mrusme** [comment]
@ErisDS I was simply following [Ghost's official documentation](https://ghost.org/docs/install/local/#developing-themes) on developing themes. This isn’t about a production environment at all.

**Comment by acburdine** [comment]
@mrusme the reason you're experiencing some oddities when running `ghost run` is because `ghost run` doesn't do a number of the "pre-start" checks that the other commands do. One of those pre-start checks is determining which environment to run in - if `ghost start` detects that you've created a `config.development.json` but _not_ a `config.production.json`, it will automatically switch to running in development mode. `ghost run` will default to running in production mode each time (saves a bit on memory consumption), so if you have a development setup and want to run things via `ghost run`, you'll need to run `ghost run -D` instead to run it in development mode. This isn't documented functionality, so apologies for the confusion.

Something we can probably improve on is our "defaults" for environment selection - if you're on macOS or windows, we can probably safely assume you're not running a production instance, and default to development mode. On linux, we'd keep production as the default mode.

As far as a solution to the underlying issue.....I'm not 100% sure 😕 as you've noted, this issue has cropped up several times in different forms, and is tricky to pin down given the lack of debug information the CLI provides. That's probably the first thing to fix, and once the CLI gives better error messaging, the underlying problem might be easier to see.

**Comment by badrihippo** [comment]
Might not be relevant to this case, but I'm documenting this here in case someone else lands up with the same issue.

I came back to Ghost dev after a gap and ran into this same error, even though it was perfectly fine earlier. I'm on Manjaro though, not macOS. It turns out I had upgraded Node, so it wasn't working on the new version. Installing the previous version (or, in my case, switching with `nvm`) did the trick.

I figured this out by `cd`ing into my `versions/2.*` directory and running `yarn`. It told me the current and expected version of Node (output for `yarn`; I assume `npm` would give some similar message):

```
cd versions/2.27.0/
yarn
yarn install v1.22.5
[1/5] Validating package.json...
error ghost@2.27.0: The engine "node" is incompatible with this module. Expected version "^8.10.0 || ^10.13.0". Got "12.18.4"
warning ghost@2.27.0: The engine "cli" appears to be invalid.
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
So changing to Node v10.x got it working again. Of course, like I said, this is a potential solution only in old installations that suddenly stopped working, not in fresh ones.

**Comment by yuraloginoff** [comment]
I had the same issue on Ubuntu 20.04.2 LTS x86_64.

How I fixed:

1. remove nodejs from Ubuntu Software (snapcraft.io)
2. install nvm (https://github.com/nvm-sh/nvm)
3. `nvm install 14.17.1`. v14.17.1 is the latest LTS at the moment (https://ghost.org/docs/faq/node-versions/)
4. `npm install ghost-cli@latest -g`
5. `ghost install local`

Hope that helps!

**Comment by boywondercreative** [comment]
> I had the same issue on Ubuntu 20.04.2 LTS x86_64.
> Hope that helps!

Thanks @yuraloginoff
