### ISSUE TITLE
update failed, after which cannot run ghost-cli

### ISSUE THREAD

**Issue by QingShui23** [TryGhost/Ghost-CLI#1150]
update failed, after which cannot run ghost-cli.
error code:
------------------------------------------------------
SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/ghost-cli/lib/bootstrap.js:6:17)

**Comment by vikaspotluri123** [comment]
@QingShui23 can you share a screenshot of the output? What version of node are you using?

**Comment by lallenfrancisl** [comment]
I currently face this issue an here's the specs

OS: Ubuntu 18.04
node version: v10.22.0
ghost-cli version: 1.14.1
