### ISSUE TITLE
ghost run works fine ghost start isn't working

### ISSUE THREAD

**Issue by vicke4** [TryGhost/Ghost-CLI#1261]
Hi,

`ghost run` command works without any issue. But, when I run `ghost start`, I get the below error for the `journalctl -n 50` command.

```
/home/ganapa/.nvm/versions/node/v12.18.3/lib/node_modules/ghost-cli/node_modules/yargs/yargs.js:4
async function requiresNode8OrGreater () {}
      ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
```
What am I doing wrong? Any help will be much appreciated.

Node version: v12.18.3
npm version: 6.14.6
Ghost version: 3.27.0
Ghost CLI version: 1.14.1

**Comment by vicke4** [comment]
Figured it out. Ghost systemd service was using `/usr/bin/node` which was Node 6. Deleted that and symlinked it to Node 12. Working now!!
