### ISSUE TITLE
Ghost DigitalOcean fresh installation skips setting up `ghost` mysql user

### ISSUE THREAD

**Issue by Rubix982** [TryGhost/Ghost-CLI#1268]
### Issue Summary

Hello! 

I was just setting up a ghost droplet on digitalocean, when I ran into the issue of ghost failing to start because it skipped a `mysql` step, logs are below.

The specific line is,

```
ℹ Setting up "ghost" mysql user [skipped]
```

The complete logs are,

```
You are required to change your password immediately (root enforced)
Welcome to Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-112-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Mon Aug  3 06:43:19 UTC 2020

  System load:  0.0               Processes:           89
  Usage of /:   9.3% of 24.06GB   Users logged in:     0
  Memory usage: 29%               IP address for eth0: 139.59.76.56
  Swap usage:   0%

 * Canonical Livepatch is available for installation.
   - Reduce system reboots and improve kernel security. Activate at:
     https://ubuntu.com/livepatch

28 packages can be updated.
0 updates are security updates.

Failed to connect to https://changelogs.ubuntu.com/meta-release-lts. Check your Internet connection or proxy settings


********************************************************************************

Welcome to DigitalOcean's One-Click Ghost Droplet.
To keep this Droplet secure, the UFW firewall is enabled. 
All ports are BLOCKED except 22 (SSH), 80 (HTTP), and 443 (HTTPS).

For help and more information, visit http://do.co/ghost1804

********************************************************************************
To delete this message of the day: rm -rf /etc/update-motd.d/99-one-click
Last login: Mon Aug  3 06:41:36 2020 from xxx.xxx.xxx
Changing password for root.
(current) UNIX password: 
Enter new UNIX password: 
Retype new UNIX password: 
You must choose a longer password
Enter new UNIX password: 
Retype new UNIX password: 

-------------------------------------------------------------------------------

Configuring DigitalOcean 1-Click Ghost installation.

Please wait a minute while your 1-Click is configured. 

Once complete, you are encouraged to run mysql_secure_installation to ready
your server for production. Passwords have been saved to:

    root/.digitalocean_password

-------------------------------------------------------------------------------


Ensuring Ghost-CLI is up-to-date...
+ sudo npm i -g ghost-cli@latest
/usr/bin/ghost -> /usr/lib/node_modules/ghost-cli/bin/ghost
+ ghost-cli@1.14.1
removed 1 package and updated 4 packages in 59.669s


   ╭────────────────────────────────────────────────────────────────╮
   │                                                                │
   │      New patch version of npm available! 6.14.4 → 6.14.7       │
   │   Changelog: https://github.com/npm/cli/releases/tag/v6.14.7   │
   │               Run npm install -g npm to update!                │
   │                                                                │
   ╰────────────────────────────────────────────────────────────────╯


Ghost will prompt you for two details:

1. Your domain
 - Add an A Record -> xxx.xxx.xxx & ensure the DNS has fully propagated
 - Or alternatively enter http://xxx.xxx.xxx
2. Your email address (only used for SSL)

Press enter when you're ready to get started!

dev-hearted.software
+ sudo chown -R ghost-mgr:ghost-mgr /home/ghost-mgr/.config
✔ Checking system Node.js version
✔ Checking logged in user
✔ Checking current folder permissions
✔ Checking operating system compatibility
✔ Checking for a MySQL installation
✔ Checking memory availability
✔ Checking for latest Ghost version
✔ Setting up install directory
✔ Downloading and installing Ghost v3.27.0
✔ Finishing install process
? Enter your blog URL: https://dev-hearted.software
✔ Configuring Ghost
✔ Setting up instance
+ sudo useradd --system --user-group ghost
+ sudo chown -R ghost:ghost /var/www/ghost/content
✔ Setting up "ghost" system user
ℹ Setting up "ghost" mysql user [skipped] <------------------------------- *Here is the error*
✔ Creating nginx config file at /var/www/ghost/system/files/dev-hearted.software.conf
+ sudo ln -sf /var/www/ghost/system/files/dev-hearted.software.conf /etc/nginx/sites-available/dev-hearted.software.conf
+ sudo ln -sf /etc/nginx/sites-available/dev-hearted.software.conf /etc/nginx/sites-enabled/dev-hearted.software.conf
+ sudo nginx -s reload
✔ Setting up Nginx
? Enter your email (For SSL Certificate) johndoe@github.com
+ sudo mkdir -p /etc/letsencrypt
+ sudo ./acme.sh --install --home /etc/letsencrypt
+ sudo /etc/letsencrypt/acme.sh --issue --home /etc/letsencrypt --domain dev-hearted.software --webroot /var/www/ghost/system/nginx-root --reloadcmd "nginx -s reload" --accountemail saifulislam84210@gmail.com
+ sudo openssl dhparam -out /etc/nginx/snippets/dhparam.pem 2048
+ sudo mv /tmp/ssl-params.conf /etc/nginx/snippets/ssl-params.conf
✔ Creating ssl config file at /var/www/ghost/system/files/dev-hearted.software-ssl.conf
+ sudo ln -sf /var/www/ghost/system/files/dev-hearted.software-ssl.conf /etc/nginx/sites-available/dev-hearted.software-ssl.conf
+ sudo ln -sf /etc/nginx/sites-available/dev-hearted.software-ssl.conf /etc/nginx/sites-enabled/dev-hearted.software-ssl.conf
+ sudo nginx -s reload
✔ Setting up SSL
✔ Creating systemd service file at /var/www/ghost/system/files/ghost_dev-hearted-software.service
+ sudo ln -sf /var/www/ghost/system/files/ghost_dev-hearted-software.service /lib/systemd/system/ghost_dev-hearted-software.service
+ sudo systemctl daemon-reload
✔ Setting up Systemd
+ sudo systemctl is-active ghost_dev-hearted-software
+ sudo systemctl start ghost_dev-hearted-software
+ sudo systemctl stop ghost_dev-hearted-software
✖ Starting Ghost
One or more errors occurred.

1) GhostError

Message: ER_ACCESS_DENIED_ERROR: Access denied for user 'ghost'@'localhost' (using password: YES)
Help: Unknown database error
Suggestion: journalctl -u ghost_dev-hearted-software -n 50

Debug Information:
    OS: Ubuntu, v18.04.4 LTS
    Node Version: v12.18.0
    Ghost Version: 3.27.0
    Ghost-CLI Version: 1.14.1
    Environment: production
    Command: 'ghost install --auto --db=mysql --dbhost=localhost --dbname=ghost_production --dbuser=ghost --dbpass=some_pass --dir=/var/www/ghost --start'

Additional log info available in: /home/ghost-mgr/.ghost/logs/ghost-cli-debug-2020-08-03T06_58_08_378Z.log

Try running ghost doctor to check your system for known issues.

You can always refer to https://ghost.org/docs/api/ghost-cli/ for troubleshooting.

------------------------------------------------------------------------------

For any further commands, please switch to the ghost-mgr user to manage Ghost.

    sudo -i -u ghost-mgr

------------------------------------------------------------------------------

root@ghost-ubuntu-s-1vcpu-1gb-blr1-01:~# ghost doctor
You can't run commands as the 'root' user.
Switch to your regular user, or create a new user with regular account privileges and use this user to run 'ghost doctor'.
For more information, see https://ghost.org/docs/install/ubuntu/#create-a-new-user-.
```

The logs from journalctl are these, 

```
Aug 03 07:32:00 ghost-ubuntu-s-1vcpu-1gb-blr1-01 node[4568]:     at Handshake.ErrorPacket (/var/www/ghost/versions/3.27.0/node_modules/mysql/lib/protoc
Aug 03 07:32:00 ghost-ubuntu-s-1vcpu-1gb-blr1-01 node[4568]:     at Protocol._parsePacket (/var/www/ghost/versions/3.27.0/node_modules/mysql/lib/protoc
Aug 03 07:32:00 ghost-ubuntu-s-1vcpu-1gb-blr1-01 node[4568]:     at Parser._parsePacket (/var/www/ghost/versions/3.27.0/node_modules/mysql/lib/protocol
Aug 03 07:32:00 ghost-ubuntu-s-1vcpu-1gb-blr1-01 node[4568]:     at Parser.write (/var/www/ghost/versions/3.27.0/node_modules/mysql/lib/protocol/Parser
Aug 03 07:32:00 ghost-ubuntu-s-1vcpu-1gb-blr1-01 node[4568]:     at Protocol.write (/var/www/ghost/versions/3.27.0/node_modules/mysql/lib/protocol/Prot
Aug 03 07:32:00 ghost-ubuntu-s-1vcpu-1gb-blr1-01 node[4568]:     at Socket.<anonymous> (/var/www/ghost/versions/3.27.0/node_modules/mysql/lib/Connectio
Aug 03 07:32:00 ghost-ubuntu-s-1vcpu-1gb-blr1-01 node[4568]:     at Socket.<anonymous> (/var/www/ghost/versions/3.27.0/node_modules/mysql/lib/Connectio
Aug 03 07:32:00 ghost-ubuntu-s-1vcpu-1gb-blr1-01 node[4568]:     at Socket.emit (events.js:315:20)
Aug 03 07:32:00 ghost-ubuntu-s-1vcpu-1gb-blr1-01 node[4568]:     at addChunk (_stream_readable.js:295:12)
Aug 03 07:32:00 ghost-ubuntu-s-1vcpu-1gb-blr1-01 node[4568]:     at readableAddChunk (_stream_readable.js:271:9)
Aug 03 07:32:00 ghost-ubuntu-s-1vcpu-1gb-blr1-01 node[4568]:     at Socket.Readable.push (_stream_readable.js:212:10)
Aug 03 07:32:00 ghost-ubuntu-s-1vcpu-1gb-blr1-01 node[4568]:     at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
Aug 03 07:32:00 ghost-ubuntu-s-1vcpu-1gb-blr1-01 node[4568]:     --------------------
Aug 03 07:32:00 ghost-ubuntu-s-1vcpu-1gb-blr1-01 node[4568]:     at Protocol._enqueue (/var/www/ghost/versions/3.27.0/node_modules/mysql/lib/protocol/P
Aug 03 07:32:00 ghost-ubuntu-s-1vcpu-1gb-blr1-01 node[4568]:     at Protocol.handshake (/var/www/ghost/versions/3.27.0/node_modules/mysql/lib/protocol/
Aug 03 07:32:00 ghost-ubuntu-s-1vcpu-1gb-blr1-01 node[4568]:     at Connection.connect (/var/www/ghost/versions/3.27.0/node_modules/mysql/lib/Connectio
Aug 03 07:32:00 ghost-ubuntu-s-1vcpu-1gb-blr1-01 node[4568]:     at /var/www/ghost/versions/3.27.0/node_modules/knex-migrator/node_modules/knex/lib/dia
Aug 03 07:32:00 ghost-ubuntu-s-1vcpu-1gb-blr1-01 node[4568]:     at Promise._execute (/var/www/ghost/versions/3.27.0/node_modules/bluebird/js/release/d
Aug 03 07:32:00 ghost-ubuntu-s-1vcpu-1gb-blr1-01 node[4568]:     at Promise._resolveFromExecutor (/var/www/ghost/versions/3.27.0/node_modules/bluebird/
Aug 03 07:32:00 ghost-ubuntu-s-1vcpu-1gb-blr1-01 node[4568]:     at new Promise (/var/www/ghost/versions/3.27.0/node_modules/bluebird/js/release/promis
Aug 03 07:32:00 ghost-ubuntu-s-1vcpu-1gb-blr1-01 node[4568]:     at Client_MySQL.acquireRawConnection (/var/www/ghost/versions/3.27.0/node_modules/knex
Aug 03 07:32:00 ghost-ubuntu-s-1vcpu-1gb-blr1-01 node[4568]:     at create (/var/www/ghost/versions/3.27.0/node_modules/knex-migrator/node_modules/knex
Aug 03 07:32:00 ghost-ubuntu-s-1vcpu-1gb-blr1-01 node[4568]:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
Aug 03 07:32:00 ghost-ubuntu-s-1vcpu-1gb-blr1-01 node[4568]: 
Aug 03 07:32:00 ghost-ubuntu-s-1vcpu-1gb-blr1-01 node[4568]: [2020-08-03 07:32:00] INFO Bootstrap client was closed.
Aug 03 07:32:00 ghost-ubuntu-s-1vcpu-1gb-blr1-01 systemd[1]: Stopping Ghost systemd service for blog: dev-hearted-software...
Aug 03 07:32:01 ghost-ubuntu-s-1vcpu-1gb-blr1-01 node[4568]: /usr/lib/node_modules/ghost-cli/lib/process-manager.js:46
Aug 03 07:32:01 ghost-ubuntu-s-1vcpu-1gb-blr1-01 node[4568]:         throw error;
Aug 03 07:32:01 ghost-ubuntu-s-1vcpu-1gb-blr1-01 node[4568]:         ^
Aug 03 07:32:01 ghost-ubuntu-s-1vcpu-1gb-blr1-01 node[4568]: {
Aug 03 07:32:01 ghost-ubuntu-s-1vcpu-1gb-blr1-01 node[4568]:   message: {
Aug 03 07:32:01 ghost-ubuntu-s-1vcpu-1gb-blr1-01 node[4568]:     statusCode: 500,
Aug 03 07:32:01 ghost-ubuntu-s-1vcpu-1gb-blr1-01 node[4568]:     errorType: 'DatabaseError',
Aug 03 07:32:01 ghost-ubuntu-s-1vcpu-1gb-blr1-01 node[4568]:     level: 'normal',
Aug 03 07:32:01 ghost-ubuntu-s-1vcpu-1gb-blr1-01 node[4568]:     message: "ER_ACCESS_DENIED_ERROR: Access denied for user 'ghost'@'localhost' (using pa
Aug 03 07:32:01 ghost-ubuntu-s-1vcpu-1gb-blr1-01 node[4568]:     id: 500,
Aug 03 07:32:01 ghost-ubuntu-s-1vcpu-1gb-blr1-01 node[4568]:     help: 'Unknown database error',
Aug 03 07:32:01 ghost-ubuntu-s-1vcpu-1gb-blr1-01 node[4568]:     name: 'DatabaseError',
Aug 03 07:32:01 ghost-ubuntu-s-1vcpu-1gb-blr1-01 node[4568]:     code: 'ER_ACCESS_DENIED_ERROR',
Aug 03 07:32:01 ghost-ubuntu-s-1vcpu-1gb-blr1-01 node[4568]:     property: null,
Aug 03 07:32:01 ghost-ubuntu-s-1vcpu-1gb-blr1-01 node[4568]:     redirect: null,
Aug 03 07:32:01 ghost-ubuntu-s-1vcpu-1gb-blr1-01 node[4568]:     errno: 1045,
Aug 03 07:32:01 ghost-ubuntu-s-1vcpu-1gb-blr1-01 node[4568]:     sqlMessage: "Access denied for user 'ghost'@'localhost' (using password: YES)",
Aug 03 07:32:01 ghost-ubuntu-s-1vcpu-1gb-blr1-01 node[4568]:     sqlState: '28000',
Aug 03 07:32:01 ghost-ubuntu-s-1vcpu-1gb-blr1-01 node[4568]:     fatal: true
Aug 03 07:32:01 ghost-ubuntu-s-1vcpu-1gb-blr1-01 node[4568]:   }
Aug 03 07:32:01 ghost-ubuntu-s-1vcpu-1gb-blr1-01 node[4568]: }
Aug 03 07:32:01 ghost-ubuntu-s-1vcpu-1gb-blr1-01 systemd[1]: ghost_dev-hearted-software.service: Main process exited, code=exited, status=1/FAILURE
Aug 03 07:32:01 ghost-ubuntu-s-1vcpu-1gb-blr1-01 systemd[1]: ghost_dev-hearted-software.service: Failed with result 'exit-code'.
Aug 03 07:32:01 ghost-ubuntu-s-1vcpu-1gb-blr1-01 systemd[1]: Stopped Ghost systemd service for blog: dev-hearted-software.
```

Googling, I found a forum on `digitalocean` with the same problem, [here](https://www.digitalocean.com/community/questions/ghost-1click-app-access-denied-for-user-ghost-localhost). 
What I'm not sure about is why the `mysql` part is even skipped. 

### To Reproduce

1. Get a domain name from a domain registarar
2. Make a new droplet from digitalocean
3. Install ghost on that new domain
4. Make proper DNS configurations
5. Login to your droplet via `ssh` and watch for everything to be setup.

Considered a bug because the process should be automatic, and ghost doesn't provide the reason why it skipped the `mysql` part, which should have been automated.

### The fix

For some reason, the password given to the `mysql` instance isn't the correct password. In my case, it is trying `YES` as the password, while the actual user creation has succeeded. I just went into `mysql` using `sudo mysql`, and then, I did,
```
ALTER USER 'ghost'@'localhost' IDENTIFIED BY 'YES';
```

And then it starts working normally. After making the changes, the output of `ghost doctor` is,
```
✔ Checking system Node.js version
✔ Checking logged in user
✔ Ensuring user is not logged in as ghost user
✔ Checking if logged in user is directory owner
✔ Checking current folder permissions
✔ Checking operating system compatibility
✔ Checking for a MySQL installation
+ sudo systemctl is-active ghost_dev-hearted-software
+ sudo systemctl reset-failed ghost_dev-hearted-software
✔ Validating config
✔ Checking folder permissions
✔ Checking file permissions
✔ Checking content folder ownership
✔ Checking memory availability
✔ Checking binary dependencies
```

Which should mean everything is A-okay.

### Technical details:

- OS: Ubuntu, v18.04.4 LTS
- Node Version: v12.18.0
- Ghost Version: 3.27.0
- Ghost-CLI Version: 1.14.1
- Environment: production
- Command: 'ghost install --auto --db=mysql --dbhost=localhost --dbname=ghost_production --dbuser=ghost --dbpass=some_pass --dir=/var/www/ghost --start'

This issue was first posted in the `TryGhost/Ghost` repo, but now, after adding in the fix, as an edit, I realize this is an issue of the `ghost-cli` repository, and should belong there. Let me try if I can shift / transfer it over there.

I tried going through the `ghost-cli` repository, but I couldn't find the exact code for where to make the changes.

That's all. Thank you!

**Comment by acburdine** [comment]
@Rubix982 So when the prompt says `(using password: YES)` that doesn't mean Ghost is trying to login to MySQL using "YES" as a password, it just means that a password _is_ being used. If, say, you were to login to MySQL without a password, the prompt would have the message `(using password: NO)`.

I'm not 100% sure why the digitalocean 1-click setup would have failed/skipped the MySQL setup, but I can run some tests and see if there's an issue with the image itself.

**Comment by Rubix982** [comment]
@acburdine I just did a fresh install now, and it works for some reason ( ???? ). Confused myself, but if there is anything, just try a new droplet and a fresh install to make it work. Other than work, I'm closing this issue. I hope this was useful to anyone else out there facing similar problems.

**Comment by balinterdi** [comment]
To anyone who comes here in desperation. The first time I couldn't make it work no matter what.

The 2nd time I was lucky, I guess, and it worked like a charm, so trying from scratch might be the best use of your time 😆

**Comment by fultonm** [comment]
Having the same issue, using AWS RDS MySQL. It worked the first time. Dropped the table in MySQL Workbench to start over. Now it skips the DB set up every time. I deleted nginx, ghost, started from scratch multiple times. Skips DB set up.

**Comment by acburdine** [comment]
@fultonm did you reset the db username/password in your config file to `root`? the mysql setup is really only to create a specific `ghost` user for your database so that Ghost doesn't run as root. If the user specified in your `config.production.json` _isn't_ root, Ghost-CLI assumes you configured the lower-privileged user yourself, and skips the setup step.

**Comment by fultonm** [comment]
I had already created a less privileged user that I was specifying the user name and password for during set up.

**Comment by acburdine** [comment]
> I had already created a less privileged user that I was specifying the user name and password for during set up.

the same thing applies here - if you pass in a non-root user during set up, the db setup step will be skipped. The db setup getting skipped shouldn't be an issue, you'll just need to make sure that the database schema you pass to Ghost during setup is already created.

**Comment by fultonm** [comment]
I experienced different behavior when running ghost install for the first time on the instance. Passing in my ghost_db_user and password with permission to create and alter databases causes ghost install to initialize the ghost_prod database with all of its tables. If I drop this table, along will all ghost config I know about, for some reason it will not attempt to create this database again.

**Comment by acburdine** [comment]
Hmm, ok. I'll take a deeper look and see if I can't figure out what's going on.

**Comment by acburdine** [comment]
@fultonm can you paste the following:

1. The command you're running to try and setup mysql (a time that it gets skipped) as well as any output from that command
2. The output of `ls -al` run inside of your Ghost installation directory (the directory you're in when you run the command from 1)

I've got a theory as to what's happening, but there's a few different factors at play so the above logs would be super helpful in tracking the issue down.

**Comment by Rubix982** [comment]
Reopening issue until further updates. (Y)

**Comment by Rubix982** [comment]
This should be solved by now. It was caused by an automatic dependency update from a bot, as far as I was able to investigate.

**Comment by Tenelia** [comment]
Hey, @Rubix982 I ran into the same issue and now I can't even use root, or ghost-mgr, or any other user to access MySQL no matter what setup I use. Setting passwords, resetting them, or starting over doesn't seem to work.

**Comment by 3ux1n3** [comment]
I just faced this issue and it took me a couple of days to figure it out , 
when you see this message : 

```
********************************************************************************

Welcome to DigitalOcean's One-Click Ghost Droplet.
To keep this Droplet secure, the UFW firewall is enabled. 
All ports are BLOCKED except 22 (SSH), 80 (HTTP), and 443 (HTTPS).

For help and more information, visit http://do.co/ghost1804

********************************************************************************
```
it means the one click install script didn't finish setting up yet and you SSHed into your server before that , problem is when u ssh first time you trigger the ghost initialisation and it fails , here is how i solved this : 


after setting up the ghost instance in digital ocean you give it time ( i waited 15 minutes before i SSH into it )

**Comment by 3ux1n3** [comment]
your problem is cause by SSHing into droplet early , you must give the one click script time to finish up , i had same issue for 2 days now and when i tried this theory it works now , start from scratch setup ghost droplet and give it a little over 15 minutes before you ssh in for first time
you should not see this message : 

```
-------------------------------------------------------------------------------

Configuring DigitalOcean 1-Click Ghost installation.

Please wait a minute while your 1-Click is configured. 

Once complete, you are encouraged to run mysql_secure_installation to ready
your server for production. Passwords have been saved to:

    root/.digitalocean_password

-------------------------------------------------------------------------------
```
if you see it you must destroy droplet and try again

**Comment by Rubix982** [comment]
@3ux1n3 thank you. This issue is now 4 years old. I now have nostalgia. Thanks for helping me remember this.
