### ISSUE TITLE
Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by mlicheng** [TryGhost/Ghost-CLI#1280]
### Summary
when i run ghost from local , there is a error occur , and some time the site went down, minutes ago when i fresh the page the site is good , and then i check the logs file and ghost cli out put , ```ghost ls``` shows Status stopped 

### Steps to Reproduce
just as usual , ghost start

### command error log 
```
{"name":"Log","hostname":"bogon","pid":9664,"level":50,"err":{"id":"bb332e30-e36f-11ea-a585-5fa0e2654d64","domain":"http://localhost:2369/","code":"IMAGE_SIZE_URL","name":"InternalServerError","statusCode":500,"level":"critical","message":"Unknown Request error.","context":"\"https://static.ghost.org/v1.0.0/images/ghost-logo.svg\"","stack":"InternalServerError: Unknown Request error.\n    at new InternalServerError (/Users/admin/ghost-local/versions/3.30.1/node_modules/ghost-ignition/lib/errors/index.js:90:23)\n    at /Users/admin/ghost-local/versions/3.30.1/core/server/lib/image/image-size.js:176:31\n    at tryCatcher (/Users/admin/ghost-local/versions/3.30.1/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/Users/admin/ghost-local/versions/3.30.1/node_modules/bluebird/js/release/promise.js:547:31)\n    at Promise._settlePromise (/Users/admin/ghost-local/versions/3.30.1/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromise0 (/Users/admin/ghost-local/versions/3.30.1/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/Users/admin/ghost-local/versions/3.30.1/node_modules/bluebird/js/release/promise.js:725:18)\n    at _drainQueueStep (/Users/admin/ghost-local/versions/3.30.1/node_modules/bluebird/js/release/async.js:93:12)\n    at _drainQueue (/Users/admin/ghost-local/versions/3.30.1/node_modules/bluebird/js/release/async.js:86:9)\n    at Async._drainQueues (/Users/admin/ghost-local/versions/3.30.1/node_modules/bluebird/js/release/async.js:102:5)\n    at Immediate.Async.drainQueues [as _onImmediate] (/Users/admin/ghost-local/versions/3.30.1/node_modules/bluebird/js/release/async.js:15:14)\n    at runCallback (timers.js:705:18)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)\n    at process.topLevelDomainCallback (domain.js:126:23)\n\nError: ESOCKETTIMEDOUT\n    at ClientRequest.<anonymous> (/Users/admin/ghost-local/versions/3.30.1/node_modules/request/request.js:816:19)\n    at Object.onceWrapper (events.js:286:20)\n    at ClientRequest.emit (events.js:198:13)\n    at ClientRequest.EventEmitter.emit (domain.js:448:20)\n    at TLSSocket.emitRequestTimeout (_http_client.js:662:40)\n    at Object.onceWrapper (events.js:286:20)\n    at TLSSocket.emit (events.js:198:13)\n    at TLSSocket.EventEmitter.emit (domain.js:448:20)\n    at TLSSocket.Socket._onTimeout (net.js:443:8)\n    at ontimeout (timers.js:436:11)\n    at tryOnTimeout (timers.js:300:5)\n    at listOnTimeout (timers.js:263:5)\n    at Timer.processTimers (timers.js:223:10)"},"msg":"Unknown Request error.","time":"2020-08-21T05:32:40.982Z","v":0}
```

### Technical details
only found this 
```
Unhandled rejection Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at ServerResponse.header (/Users/admin/ghost-local/versions/3.30.1/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/Users/admin/ghost-local/versions/3.30.1/node_modules/express/lib/response.js:170:12)
    at res.render (/Users/admin/ghost-local/versions/3.30.1/core/server/web/shared/middlewares/error-handler.js:200:32)
    at /Users/admin/ghost-local/versions/3.30.1/node_modules/express-hbs/lib/hbs.js:635:23
    at /Users/admin/ghost-local/versions/3.30.1/node_modules/express-hbs/lib/resolver.js:29:5
    at tryCatcher (/Users/admin/ghost-local/versions/3.30.1/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/admin/ghost-local/versions/3.30.1/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/admin/ghost-local/versions/3.30.1/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/admin/ghost-local/versions/3.30.1/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/admin/ghost-local/versions/3.30.1/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/Users/admin/ghost-local/versions/3.30.1/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/admin/ghost-local/versions/3.30.1/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/admin/ghost-local/versions/3.30.1/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/admin/ghost-local/versions/3.30.1/node_modules/bluebird/js/release/async.js:15:14)
    at runCallback (timers.js:705:18)
```

   * OS: Mac OS X, v10.15.6
   * Node Version: v10.18.1
   * Ghost Version: 3.30.1
   * Ghost-CLI Version: 1.14.1
   * Environment: production

## Bug submission checklist

- [ ] Checked for existing issues
- [x] Attached log file
- [x] Provided technical details incl. operating system

**Comment by scolear** [comment]
Hey @mlicheng , did you figure out anything regarding this? I am having the same issue and have no idea how to approach this problem - as its hidden in the belly of ghost running in docker. Thanks

**Comment by ruhrscholz** [comment]
There also seems to be an issue here: https://github.com/TryGhost/Ghost/issues/13225
