### ISSUE TITLE
Ghost Error (Communication) / File Permission Error

### ISSUE THREAD

**Issue by Jaimss** [TryGhost/Ghost-CLI#1291]
### Summary

It appears my ghost cli is unable to access the log files to write logs, so it is throwing an error when i start up.

### Steps to Reproduce

1. Follow local install steps [here](https://ghost.org/docs/install/local/)
    - My install was working for a short period of time like this, but it was in the dev environment, so I did the following in an attempt to get a prod environment
2. `ghost setup`
3. Follow the promts.
4. Run the different commands to see the output (pasted below).

### Log file

The issue is that I can't get access to my log files.
`ghost ls`:
```
james@jamesdev:/var/www/ghost$ ghost ls
+ sudo systemctl is-active ghost_blog-jaims-dev
┌────────────────┬────────────────┬─────────┬─────────┬─────┬──────┬─────────────────┐
│ Name           │ Location       │ Version │ Status  │ URL │ Port │ Process Manager │
├────────────────┼────────────────┼─────────┼─────────┼─────┼──────┼─────────────────┤
│ blog-jaims-dev │ /var/www/ghost │ 3.31.3  │ stopped │ n/a │ n/a  │ n/a             │
└────────────────┴────────────────┴─────────┴─────────┴─────┴──────┴─────────────────┘
james@jamesdev:/var/www/ghost$
```
`ghost run`:
```
james@jamesdev:/var/www/ghost$ ghost run
The `ghost run` command is used by the configured Ghost process manager and for debugging. If you're not running this to debug something, you should run `ghost start` instead.
+ sudo node current/index.js
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: EACCES: permission denied, open '/var/www/ghost/versions/3.31.3/content/logs/https___blog_jaims_dev_production.error.log'
Emitted 'error' event on Logger instance at:
    at WriteStream.onStreamError (/var/www/ghost/versions/3.31.3/node_modules/ghost-ignition/node_modules/bunyan/lib/bunyan.js:627:18)
    at WriteStream.emit (events.js:315:20)
    at internal/fs/streams.js:361:12
    at FSReqCallback.oncomplete (fs.js:156:23) {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/var/www/ghost/versions/3.31.3/content/logs/https___blog_jaims_dev_production.error.log'
}
james@jamesdev:/var/www/ghost$
```
`ghost start`:
```
james@jamesdev:/var/www/ghost$ ghost start
+ sudo systemctl is-active ghost_blog-jaims-dev
✔ Ensuring user is not logged in as ghost user
✔ Checking if logged in user is directory owner
✔ Checking current folder permissions
+ sudo systemctl is-active ghost_blog-jaims-dev
✔ Validating config
✔ Checking folder permissions
✔ Checking file permissions
✔ Checking content folder ownership
✔ Checking memory availability
✔ Checking binary dependencies
+ sudo systemctl start ghost_blog-jaims-dev
+ sudo systemctl stop ghost_blog-jaims-dev
✖ Starting Ghost: blog-jaims-dev
A GhostError occurred.

Message: Could not communicate with Ghost
Suggestion: journalctl -u ghost_blog-jaims-dev -n 50

Debug Information:
    OS: Ubuntu, v20.04.1 LTS
    Node Version: v12.18.3
    Ghost Version: 3.31.3
    Ghost-CLI Version: 1.14.1
    Environment: production
    Command: 'ghost start'

Additional log info available in: /home/james/.ghost/logs/ghost-cli-debug-2020-08-31T16_54_37_656Z.log

Try running ghost doctor to check your system for known issues.

You can always refer to https://ghost.org/docs/api/ghost-cli/ for troubleshooting.
james@jamesdev:/var/www/ghost$
```
`journalctl -u ghost_blog-jaims-dev -n 50`:
```
james@jamesdev:/var/www/ghost$ sudo journalctl -u ghost_blog-jaims-dev -n 50
-- Logs begin at Sat 2020-07-04 03:34:27 UTC, end at Mon 2020-08-31 16:55:43 UTC. --
Aug 31 16:54:32 jamesdev node[315350]: Emitted 'error' event on Logger instance at:
Aug 31 16:54:32 jamesdev node[315350]:     at WriteStream.onStreamError (/var/www/ghost/versions/3.31.3/node_modules/ghost-ignition/node_modules/bunyan/lib/bunyan.js:627:18)
Aug 31 16:54:32 jamesdev node[315350]:     at WriteStream.emit (events.js:315:20)
Aug 31 16:54:32 jamesdev node[315350]:     at internal/fs/streams.js:361:12
Aug 31 16:54:32 jamesdev node[315350]:     at FSReqCallback.oncomplete (fs.js:156:23) {
Aug 31 16:54:32 jamesdev node[315350]:   errno: -13,
Aug 31 16:54:32 jamesdev node[315350]:   code: 'EACCES',
Aug 31 16:54:32 jamesdev node[315350]:   syscall: 'open',
Aug 31 16:54:32 jamesdev node[315350]:   path: '/var/www/ghost/versions/3.31.3/content/logs/https___blog_jaims_dev_production.error.log'
Aug 31 16:54:32 jamesdev node[315350]: }
Aug 31 16:54:32 jamesdev systemd[1]: ghost_blog-jaims-dev.service: Succeeded.
Aug 31 16:54:32 jamesdev systemd[1]: ghost_blog-jaims-dev.service: Scheduled restart job, restart counter is at 121.
Aug 31 16:54:32 jamesdev systemd[1]: Stopped Ghost systemd service for blog: blog-jaims-dev.
Aug 31 16:54:32 jamesdev systemd[1]: Started Ghost systemd service for blog: blog-jaims-dev.
Aug 31 16:54:33 jamesdev node[315361]: - Inspecting operating system
Aug 31 16:54:34 jamesdev node[315385]: events.js:292
Aug 31 16:54:34 jamesdev node[315385]:       throw er; // Unhandled 'error' event
Aug 31 16:54:34 jamesdev node[315385]:       ^
Aug 31 16:54:34 jamesdev node[315385]: Error: EACCES: permission denied, open '/var/www/ghost/versions/3.31.3/content/logs/https___blog_jaims_dev_production.error.log'
Aug 31 16:54:34 jamesdev node[315385]: Emitted 'error' event on Logger instance at:
Aug 31 16:54:34 jamesdev node[315385]:     at WriteStream.onStreamError (/var/www/ghost/versions/3.31.3/node_modules/ghost-ignition/node_modules/bunyan/lib/bunyan.js:627:18)
Aug 31 16:54:34 jamesdev node[315385]:     at WriteStream.emit (events.js:315:20)
Aug 31 16:54:34 jamesdev node[315385]:     at internal/fs/streams.js:361:12
Aug 31 16:54:34 jamesdev node[315385]:     at FSReqCallback.oncomplete (fs.js:156:23) {
Aug 31 16:54:34 jamesdev node[315385]:   errno: -13,
Aug 31 16:54:34 jamesdev node[315385]:   code: 'EACCES',
Aug 31 16:54:34 jamesdev node[315385]:   syscall: 'open',
Aug 31 16:54:34 jamesdev node[315385]:   path: '/var/www/ghost/versions/3.31.3/content/logs/https___blog_jaims_dev_production.error.log'
Aug 31 16:54:34 jamesdev node[315385]: }
Aug 31 16:54:35 jamesdev systemd[1]: ghost_blog-jaims-dev.service: Succeeded.
Aug 31 16:54:35 jamesdev systemd[1]: ghost_blog-jaims-dev.service: Scheduled restart job, restart counter is at 122.
Aug 31 16:54:35 jamesdev systemd[1]: Stopped Ghost systemd service for blog: blog-jaims-dev.
Aug 31 16:54:35 jamesdev systemd[1]: Started Ghost systemd service for blog: blog-jaims-dev.
Aug 31 16:54:35 jamesdev node[315396]: - Inspecting operating system
Aug 31 16:54:37 jamesdev node[315420]: events.js:292
Aug 31 16:54:37 jamesdev node[315420]:       throw er; // Unhandled 'error' event
Aug 31 16:54:37 jamesdev node[315420]:       ^
Aug 31 16:54:37 jamesdev node[315420]: Error: EACCES: permission denied, open '/var/www/ghost/versions/3.31.3/content/logs/https___blog_jaims_dev_production.error.log'
Aug 31 16:54:37 jamesdev node[315420]: Emitted 'error' event on Logger instance at:
Aug 31 16:54:37 jamesdev node[315420]:     at WriteStream.onStreamError (/var/www/ghost/versions/3.31.3/node_modules/ghost-ignition/node_modules/bunyan/lib/bunyan.js:627:18)
Aug 31 16:54:37 jamesdev node[315420]:     at WriteStream.emit (events.js:315:20)
Aug 31 16:54:37 jamesdev node[315420]:     at internal/fs/streams.js:361:12
Aug 31 16:54:37 jamesdev node[315420]:     at FSReqCallback.oncomplete (fs.js:156:23) {
Aug 31 16:54:37 jamesdev node[315420]:   errno: -13,
Aug 31 16:54:37 jamesdev node[315420]:   code: 'EACCES',
Aug 31 16:54:37 jamesdev node[315420]:   syscall: 'open',
Aug 31 16:54:37 jamesdev node[315420]:   path: '/var/www/ghost/versions/3.31.3/content/logs/https___blog_jaims_dev_production.error.log'
Aug 31 16:54:37 jamesdev node[315420]: }
Aug 31 16:54:37 jamesdev systemd[1]: ghost_blog-jaims-dev.service: Succeeded.
Aug 31 16:54:37 jamesdev systemd[1]: Stopped Ghost systemd service for blog: blog-jaims-dev.
james@jamesdev:/var/www/ghost$
```
`ghost doctor`:
```
james@jamesdev:/var/www/ghost$ ghost doctor
✔ Checking system Node.js version
✔ Checking logged in user
✔ Ensuring user is not logged in as ghost user
✔ Checking if logged in user is directory owner
✔ Checking current folder permissions
System checks failed with message: 'Linux version is not Ubuntu 16 or 18'
Some features of Ghost-CLI may not work without additional configuration.
For local installs we recommend using `ghost install local` instead.
? Continue anyway? Yes
System stack check skipped
ℹ Checking operating system compatibility [skipped]
✔ Checking for a MySQL installation
+ sudo systemctl is-active ghost_blog-jaims-dev
✔ Validating config
✔ Checking folder permissions
✔ Checking file permissions
✔ Checking content folder ownership
✔ Checking memory availability
✔ Checking binary dependencies
james@jamesdev:/var/www/ghost$
```

### Technical details

This is automatically output by Ghost-CLI if an error occurs, please copy & paste:
```
Debug Information:
    OS: Ubuntu, v20.04.1 LTS
    Node Version: v12.18.3
    Ghost Version: 3.31.3
    Ghost-CLI Version: 1.14.1
    Environment: production
    Command: 'ghost start'
```
## Bug submission checklist

Please fill out this checklist to acknowledge that you followed the requirements to submit a bug report.

- [✔️] Tried to find help in the forum & docs
- [✔️] Checked for existing issues
- [✔️] Attached log file (i attached the logs that are available to me)
- [✔️] Provided technical details incl. operating system

**Comment by ErisDS** [comment]
Just to be clear, you tried to switch a dev install to be in production mode by running setup and it didn't work?

Not sure this is a workflow we've really tested. My first guess is that your config file is not gonna contain everything it needs - can you share?

**Comment by acburdine** [comment]
@Jaimss it looks like something was misconfigured 🤔  you said you tried setting it up as a local install, but all the error messages are suggesting `production` as the environment.

What's likely happening is there's both a development _and_ a production configuration file, but the production configuration file is missing the important `paths.contentPath` setting. Because the `contentPath` isn't set correctly, Ghost is trying to write logs to the specific version folder of Ghost, rather than the installation's root-level content folder.

If you're wanting to run a blog in `local` mode, you'll need to run `ghost start --development`. If you _do_ want to run your blog in production mode, you'll need to copy over the `paths` section from your development config to your production config.

**Comment by Jaimss** [comment]
Ah ok. Thank you for explaining the difference between the prod and dev environments. I was thinking the two would maybe be running concurrently, but it appears that I have to pick one or the other.

I think this resolves my problem. Thanks.

**Comment by vikaspotluri123** [comment]
@acburdine I think we should add a warning when both dev and prod configs exist - the number of users that should intentionally have both should be low 🤔
