### ISSUE TITLE
Can't upgrade past v3.22.2

### ISSUE THREAD

**Issue by gldhnchn** [TryGhost/Ghost-CLI#1293]
While updating ghost with `ghost update` I noticed, that I cannont update to any version above 3.22.2 without ghost crashing. Upgrading to some specific version will get me a error message in the update process. Other versions will say everything worked, but ghost will still be broken with the same error in the logs.

This is the message from the update process:
> Message: alter table `tags` add `twitter_image` varchar(2000) null - ER_TOO_BIG_ROWSIZE: Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs
> Help: Error occurred while executing the following migration: 04-add-meta-columns-to-tags-table.js

```
Debug Information:
    OS: Ubuntu, v20.04.1 LTS
    Node Version: v10.19.0
    Ghost Version: 3.24.0
    Ghost-CLI Version: 1.14.1
    Environment: production
    Command: 'ghost update 3.24.0'
```

output from journalctl:
```
Sep 03 11:24:32 blackhole node[404180]:     at MigrationScriptError.KnexMigrateError (/var/www/ghost/versions/3.29.2/node_modules/knex-migrator/lib/e>
Sep 03 11:24:32 blackhole node[404180]:     at new MigrationScriptError (/var/www/ghost/versions/3.29.2/node_modules/knex-migrator/lib/errors.js:25:2>
Sep 03 11:24:32 blackhole node[404180]:     at /var/www/ghost/versions/3.29.2/node_modules/knex-migrator/lib/index.js:1055:19
Sep 03 11:24:32 blackhole node[404180]: Error: ER_TOO_BIG_ROWSIZE: Row size too large. The maximum row size for the used table type, not counting BLO>
Sep 03 11:24:32 blackhole node[404180]:     at Query.Sequence._packetToError (/var/www/ghost/versions/3.29.2/node_modules/mysql/lib/protocol/sequence>
Sep 03 11:24:32 blackhole node[404180]:     at Query.ErrorPacket (/var/www/ghost/versions/3.29.2/node_modules/mysql/lib/protocol/sequences/Query.js:7>
Sep 03 11:24:32 blackhole node[404180]:     at Protocol._parsePacket (/var/www/ghost/versions/3.29.2/node_modules/mysql/lib/protocol/Protocol.js:291:>
Sep 03 11:24:32 blackhole node[404180]:     at Parser._parsePacket (/var/www/ghost/versions/3.29.2/node_modules/mysql/lib/protocol/Parser.js:433:10)
Sep 03 11:24:32 blackhole node[404180]:     at Parser.write (/var/www/ghost/versions/3.29.2/node_modules/mysql/lib/protocol/Parser.js:43:10)
Sep 03 11:24:32 blackhole node[404180]:     at Protocol.write (/var/www/ghost/versions/3.29.2/node_modules/mysql/lib/protocol/Protocol.js:38:16)
Sep 03 11:24:32 blackhole node[404180]:     at Socket.<anonymous> (/var/www/ghost/versions/3.29.2/node_modules/mysql/lib/Connection.js:88:28)
Sep 03 11:24:32 blackhole node[404180]:     at Socket.<anonymous> (/var/www/ghost/versions/3.29.2/node_modules/mysql/lib/Connection.js:526:10)
Sep 03 11:24:32 blackhole node[404180]:     at Socket.emit (events.js:198:13)
Sep 03 11:24:32 blackhole node[404180]:     at Socket.EventEmitter.emit (domain.js:448:20)
Sep 03 11:24:32 blackhole node[404180]:     at addChunk (_stream_readable.js:288:12)
Sep 03 11:24:32 blackhole node[404180]:     at readableAddChunk (_stream_readable.js:269:11)
Sep 03 11:24:32 blackhole node[404180]:     at Socket.Readable.push (_stream_readable.js:224:10)
Sep 03 11:24:32 blackhole node[404180]:     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
Sep 03 11:24:32 blackhole node[404180]:     --------------------
Sep 03 11:24:32 blackhole node[404180]:     at Protocol._enqueue (/var/www/ghost/versions/3.29.2/node_modules/mysql/lib/protocol/Protocol.js:144:48)
Sep 03 11:24:32 blackhole node[404180]:     at Connection.query (/var/www/ghost/versions/3.29.2/node_modules/mysql/lib/Connection.js:198:25)
Sep 03 11:24:32 blackhole node[404180]:     at /var/www/ghost/versions/3.29.2/node_modules/knex-migrator/node_modules/knex/lib/dialects/mysql/index.j>
Sep 03 11:24:32 blackhole node[404180]:     at Promise._execute (/var/www/ghost/versions/3.29.2/node_modules/bluebird/js/release/debuggability.js:384>
Sep 03 11:24:32 blackhole node[404180]:     at Promise._resolveFromExecutor (/var/www/ghost/versions/3.29.2/node_modules/bluebird/js/release/promise.>
Sep 03 11:24:32 blackhole node[404180]:     at new Promise (/var/www/ghost/versions/3.29.2/node_modules/bluebird/js/release/promise.js:103:10)
Sep 03 11:24:32 blackhole node[404180]:     at Client_MySQL._query (/var/www/ghost/versions/3.29.2/node_modules/knex-migrator/node_modules/knex/lib/d>
Sep 03 11:24:32 blackhole node[404180]:     at Client_MySQL.query (/var/www/ghost/versions/3.29.2/node_modules/knex-migrator/node_modules/knex/lib/cl>
Sep 03 11:24:32 blackhole node[404180]:     at /var/www/ghost/versions/3.29.2/node_modules/knex-migrator/node_modules/knex/lib/transaction.js:321:24
Sep 03 11:24:32 blackhole node[404180]:     at Promise._execute (/var/www/ghost/versions/3.29.2/node_modules/bluebird/js/release/debuggability.js:384>
Sep 03 11:24:32 blackhole node[404180]:     at Promise._resolveFromExecutor (/var/www/ghost/versions/3.29.2/node_modules/bluebird/js/release/promise.>
Sep 03 11:24:32 blackhole node[404180]:     at new Promise (/var/www/ghost/versions/3.29.2/node_modules/bluebird/js/release/promise.js:103:10)
Sep 03 11:24:32 blackhole node[404180]:     at Client_MySQL.trxClient.query (/var/www/ghost/versions/3.29.2/node_modules/knex-migrator/node_modules/k>
Sep 03 11:24:32 blackhole node[404180]:     at Runner.query (/var/www/ghost/versions/3.29.2/node_modules/knex-migrator/node_modules/knex/lib/runner.j>
Sep 03 11:24:32 blackhole node[404180]:     at Runner.queryArray (/var/www/ghost/versions/3.29.2/node_modules/knex-migrator/node_modules/knex/lib/run>
Sep 03 11:24:32 blackhole node[404180]:     at /var/www/ghost/versions/3.29.2/node_modules/knex-migrator/node_modules/knex/lib/runner.js:38:25
```

**Comment by ErisDS** [comment]
This is to do with having a very old database that has been upgraded and has legacy configuration.

Full details can be found here: https://forum.ghost.org/t/update-above-3-22-2-fails/15948

**Comment by gldhnchn** [comment]
Thanks for the link. I was able to solve the issue. What I did:

1. add "innodb_default_row_format = dynamic" to /etc/mysql/mariadb.conf.d/50-server.cnf
2. sudo mysqlcheck -o ghost_prod
3. ghost update

Now I am on v3.31.5, thank you!
