### ISSUE TITLE
Error with fresh new install at ghost start, problem with knex dependency

### ISSUE THREAD

**Issue by planetahuevo** [TryGhost/Ghost-CLI#1296]
### Summary

Dependency problem that makes ghost start to fail.
I have tried 
ghost update --force
ghost buster (in case cache is doing something) 
and ghost run and it gives me the same error. 
but then the ghost is running with the error.

### Steps to Reproduce

1. install ghost as normal. 
2. it stops at ghost start.
3.- wait a lot for the error or ctrl C 
4.- run ghost status - the system is running "fine"?

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Log file

I have removed the folder data and replaces with "domain-com"
 
```
Error: knex: Required configuration option 'client' is missing.
    at new Client (domain-com/versions/3.32.2/node_modules/knex-migrator/node_modules/knex/lib/client.js:55:11)
    at Knex (domain-com/versions/3.32.2/node_modules/knex-migrator/node_modules/knex/lib/knex.js:53:28)
    at Object.connect (domain-com/versions/3.32.2/node_modules/knex-migrator/lib/database.js:26:12)
    at KnexMigrator.isDatabaseOK (domain-com/versions/3.32.2/node_modules/knex-migrator/lib/index.js:589:32)
    at Object.module.exports.getState (domain-com/versions/3.32.2/core/server/data/db/migrator.js:13:25)
    at isDatabaseInitialisationRequired (domain-com/versions/3.32.2/core/server/index.js:171:21)
    at makeGhost (domain-com/versions/3.32.2/core/index.js:13:12)
    at Object.<anonymous> (domain-com/versions/3.32.2/index.js:27:1)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

### Technical details

This is automatically output by Ghost-CLI if an error occurs, please copy & paste:

    OS: Ubuntu, v18.04.5 LTS
    Node Version: v12.18.3
    Ghost Version: 3.32.2
    Ghost-CLI Version: 1.14.1
    Environment: production

I have a sudo user ghostinstall and a web user. 
And ghost system user has been created perfectly. No other errors on installation.

## Bug submission checklist

Please fill out this checklist to acknowledge that you followed the requirements to submit a bug report.

- [x ] Tried to find help in the forum & docs
- [x ] Checked for existing issues
- [x ] Attached log file
- [x ] Provided technical details incl. operating system

**Comment by planetahuevo** [comment]
Hi, 
You can close this. 
The problem was that the system had a "ghost" user already created as system (from an old manual installation) and ghost uninstall does not remove or check it. 
deleting the user with "$ sudo deluser --remove-home ghost" solved the problem and now everything works as expected! :D

**Comment by planetahuevo** [comment]
Ok, what I thought was the fix, it is not. I cannot know why that one time worked, but I have started over 5 times after that and I am getting the same issues all around, but now I do not get the ghost run to work either.

All the installation happens perfectly, no errors, ghost user is created, systemd is ok. 
I can see that the database is not creating any tables, but appart from that, the installation does not give any errors (well the one when trying to start as above). 
Any ideas?

**Comment by planetahuevo** [comment]
Found the issue!
I was not adding the --db mysql to my CLI ghost install command. So it tried to use the other database system with the wrong credentials, of course.
I am going to leave this open, so someone can have a look because it would be great to have an error when not all the data of MYSQL has been provided on the CLI.
I hope the answer help others.
