### ISSUE TITLE
Consistent ghost update failure: 3.27.0 -> 3.40.1 due to MySQL 8 Collation Change

### ISSUE THREAD

**Issue by zebity** [TryGhost/Ghost-CLI#1359]
Welcome to Ghost-CLI's GitHub repo! 👋🎉

Do you need help or have a question? Please come chat in our forum: https://forum.ghost.org 👫.

Docs: https://ghost.org/docs/ 📖.

Please be aware that the team behind the Ghost CLI only supports the recommended stack: https://github.com/TryGhost/Ghost-cli#recommended-stack.

### Summary

Updating ghost from: 3.27.0 -> 3.40.1 results in ghost not starting correctly.

I have had two different failures:
1. Update Error: ER_CANT_DROP_FIELD_OR_KEY: Can't DROP 'email_recipients_email_id_foreign'; check that column/key exists
2. ERROR Migration lock was never released or currently a migration is running.

In both cases the underlying cause appears to be due to table: email_receipients being created with different Character Set Collation, which result in Foreign Key creation SQL Failure.

The existing tables have SQL Character Set / Collation: utf8mb4 / utf8mb4_general_ci
The new table have SQL Character Set / Collation: utf8mb4 / utf8mb4_0900_ai_ci

The problem can be fixed by changing the Character Set / Collation on the offending table and re-running ghost

### Steps to Reproduce

1. cd /var/www/ghost
2. sudo npm install ghost-cli@latest -g
3. sudo npm install -g npm
4. ghost update

Ghost then fails to start and "ghost update --rollback" also fails

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Log file

First attempt:

/var/www/ghost/content/log/http__xxx.xxx__production.error.log

...
...
2020-12-15 09:25:06] ERROR alter table `email_recipients` drop foreign key `email_recipients_email_id_foreign` - ER_CANT_DROP_FIELD_OR_KEY: Can't DROP 'email_recipients_email_id_foreign'; check that column/key exists

alter table `email_recipients` drop foreign key `email_recipients_email_id_foreign` - ER_CANT_DROP_FIELD_OR_KEY: Can't DROP 'email_recipients_email_id_foreign'; check that column/key exists

&quot;OuterError: update `members` set `email_count` = (SELECT COUNT(id) FROM email_recipients WHERE email_recipients.member_id = members.id), `email_opened_count` = (SELECT COUNT(id) FROM email_recipients WHERE email_recipients.member_id = members.id AND email_recipients.opened_at IS NOT NULL) - ER_CANT_AGGREGATE_2COLLATIONS: Illegal mix of collations (utf8mb4_0900_ai_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation '='&quot;

Error ID:
    400

Error Code: 
    ER_CANT_DROP_FIELD_OR_KEY

----------------------------------------
...
...

2nd Attempt Running "ghost run":

ghost run
The `ghost run` command is used by the configured Ghost process manager and for debugging. If you're not running this to debug something, you should run `ghost start` instead.
+ sudo node current/index.js
[2020-12-16 00:15:37] ERROR Migration lock was never released or currently a migration is running.

Migration lock was never released or currently a migration is running.

"If you are sure no migration is running, check your data and if your database is in a broken state, you could run `knex-migrator rollback`."

Error ID:
    500

----------------------------------------

MigrationsAreLockedError: Migration lock was never released or currently a migration is running.
    at MigrationsAreLockedError.KnexMigrateError (/var/www/ghost/versions/3.40.1/node_modules/knex-migrator/lib/errors.js:7:26)
    at new MigrationsAreLockedError (/var/www/ghost/versions/3.40.1/node_modules/knex-migrator/lib/errors.js:37:26)
    at /var/www/ghost/versions/3.40.1/node_modules/knex-migrator/lib/locking.js:62:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)Use the command `cat [filepath]` to read the log, then copy & paste the contents here:

### Technical details

This is automatically output by Ghost-CLI if an error occurs, please copy & paste:

Debug Information:
    OS: Ubuntu, v20.04.1 LTS
    Node Version: v12.20.0
    Ghost Version: 3.40.1
    Ghost-CLI Version: 1.15.3
    Environment: production
    MySQL Version: Server version: 8.0.22-0ubuntu0.20.04.2 (Ubuntu)

Investigation found that email_receipents has the wrong collation setting:

mysql> SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, COLLATION_NAME FROM INFORMATION_SCHEMA.COLUMNS where COLLATION_NAME like 'utf8mb4_0900_ai_ci';
+---------------+--------------------+-----------------------------------+--------------+--------------------+
| TABLE_CATALOG | TABLE_SCHEMA       | TABLE_NAME                        | COLUMN_NAME  | COLLATION_NAME     |
+---------------+--------------------+-----------------------------------+--------------+--------------------+
...
...
| def           | ghost     | email_recipients                  | batch_id     | utf8mb4_0900_ai_ci |
| def           | ghost     | email_recipients                  | email_id     | utf8mb4_0900_ai_ci |
| def           | ghost     | email_recipients                  | id           | utf8mb4_0900_ai_ci |
| def           | ghost     | email_recipients                  | member_email | utf8mb4_0900_ai_ci |
| def           | ghost     | email_recipients                  | member_id    | utf8mb4_0900_ai_ci |
| def           | ghost     | email_recipients                  | member_name  | utf8mb4_0900_ai_ci |
| def           | ghost     | email_recipients                  | member_uuid  | utf8mb4_0900_ai_ci |
+---------------+--------------------+-----------------------------------+--------------+--------------------+
47 rows in set (0.04 sec)

## Bug submission checklist

Please fill out this checklist to acknowledge that you followed the requirements to submit a bug report.

- [Y] Tried to find help in the forum & docs
- [Y] Checked for existing issues: Here is related issue: https://github.com/TryGhost/knex-migrator/pull/233
- [Y] Attached log file
- [Y] Provided technical details incl. operating system

**Comment by acburdine** [comment]
@zebity did you also happen to update your MySQL version to v8 during this process? MySQL v8 changes the default table collation, and that's what throws off a lot of the queries that the migrations run.

If you _did_ upgrade to MySQL v8, you'll likely need to run the following query to update your default collation:
```
ALTER DATABASE <database_name> CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
```
Once you've done that, you'll also likely need to remove the row from the migration lock table to allow knex-migrator to rollback the database changes.

**Comment by zebity** [comment]
@acburdine ,

long delay between raising issue and responding, my apologies.

Yes doing Ubuntu apt update/upgrade did result in change to default collation and this has caused repeated failures doing Ghost updates.

I have documented a lot of my work arounds on this in my Ghost admin blog: https://tips.graphica.com.au/ghost-blog-administration/

I document work arounds for myself so I have reference for next time, but it would be great if the ghost migration scripts could handle these cases automatically.

Thank you for advise and response.

John.
