### ISSUE TITLE
TypeError: Cannot destructure property 'message' of 'message.error' as it is undefined.

### ISSUE THREAD

**Issue by mmiszy** [TryGhost/Ghost-CLI#1585]
### Summary

After updating ghost to `4.25.1` the following problem occurs:

```ts
/var/www/ghost$ ghost restart
+ sudo systemctl is-active ghost_news-website-com
+ sudo systemctl restart ghost_news-website-com
☴ Restarting Ghost/usr/lib/node_modules/ghost-cli/lib/utils/port-polling.js:68
                    let {message: errMsg} = message.error;
                                  ^

TypeError: Cannot destructure property 'message' of 'message.error' as it is undefined.
    at Server.<anonymous> (/usr/lib/node_modules/ghost-cli/lib/utils/port-polling.js:68:35)
    at Object.onceWrapper (events.js:519:28)
    at Server.emit (events.js:400:28)
    at emitCloseNT (net.js:1677:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

### Steps to Reproduce

1. Run `ghost restart`

### Log

<details>

```
[2021-12-04 13:29:45] WARN Ghost is shutting down
[2021-12-04 13:29:45] WARN Ghost has shut down
[2021-12-04 13:29:45] WARN Your site is now offline
[2021-12-04 13:29:45] WARN Ghost was running for 4 minutes
[2021-12-04 13:29:48] INFO Ghost is running in production...
[2021-12-04 13:29:48] INFO Your site is now available on https://news.typeofweb.com/
[2021-12-04 13:29:48] INFO Ctrl+C to shut down
[2021-12-04 13:29:48] INFO Ghost server started in 0.667s
[2021-12-04 13:29:48] INFO Bootstrap client was closed.
[2021-12-04 13:29:48] INFO Database is in a ready state.
[2021-12-04 13:29:48] INFO Ghost database ready in 0.986s
[2021-12-04 13:29:50] WARN Theme translations file locales/pl.json not found.
[2021-12-04 13:29:50] WARN Theme translations falling back to locales/en.json.
[2021-12-04 13:29:51] INFO Ghost URL Service Ready in 4.139s
[2021-12-04 13:29:51] INFO Ghost booted in 4.259s
[2021-12-04 13:29:51] WARN Can't connect to the bootstrap socket (localhost 8000) ECONNREFUSED.
[2021-12-04 13:29:51] WARN Tries: 0
[2021-12-04 13:29:51] WARN Retrying...
[2021-12-04 13:29:51] INFO Adding offloaded job to the queue
[2021-12-04 13:29:51] INFO Scheduling job email-analytics-fetch-latest at 38 3/5 * * * *. Next run on: Sat Dec 04 2021 13:33:38 GMT+0000 (Coordinated Universal Time)
[2021-12-04 13:29:51] INFO Adding offloaded job to the queue
[2021-12-04 13:29:51] INFO Scheduling job update-check at 35 52 3 * * *. Next run on: Sun Dec 05 2021 03:52:35 GMT+0000 (Coordinated Universal Time)
[2021-12-04 13:29:51] INFO Populating members_monthly_price_id from stripe_plans
[2021-12-04 13:29:51] WARN Can't connect to the bootstrap socket (localhost 8000) ECONNREFUSED.
[2021-12-04 13:29:51] WARN Tries: 1
[2021-12-04 13:29:51] WARN Retrying...
[2021-12-04 13:29:51] WARN Skipping population of members_monthly_price_id, could not find Monthly plan
[2021-12-04 13:29:51] INFO Populating members_yearly_price_id from stripe_plans
[2021-12-04 13:29:51] WARN Skipping population of members_yearly_price_id, could not find yearly plan
[2021-12-04 13:29:51] INFO Migrating members_monthly_price_id setting to monthly_price_id column
[2021-12-04 13:29:51] WARN Skipping migration, monthly_price_id already set
[2021-12-04 13:29:51] INFO Migrating members_yearly_price_id setting to yearly_price_id column
[2021-12-04 13:29:51] WARN Skipping migration, yearly_price_id already set
[2021-12-04 13:29:51] INFO Migrating portal_plans setting from ids to names
[2021-12-04 13:29:51] INFO The portal_plans setting already contains names, skipping migration
[2021-12-04 13:29:51] INFO No invalid subscriptions, skipping migration
[2021-12-04 13:29:52] WARN Can't connect to the bootstrap socket (localhost 8000) ECONNREFUSED.
[2021-12-04 13:29:52] WARN Tries: 2
[2021-12-04 13:29:52] WARN Retrying...
[2021-12-04 13:29:52] WARN Can't connect to the bootstrap socket (localhost 8000) ECONNREFUSED.
```

</details>

### Technical details

This is automatically output by Ghost-CLI if an error occurs, please copy & paste:

* OS: `Linux ghost-s-1vcpu-1gb-fra1-01 5.4.0-89-generic #100-Ubuntu SMP Fri Sep 24 14:50:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
* Node Version: v14.18.1
* Ghost-CLI Version: 1.18.1
* Ghost version: 4.25.1
* Environment:
* Command: `ghost restart`

## Bug submission checklist

Please fill out this checklist to acknowledge that you followed the requirements to submit a bug report.

- [x] Tried to find help in the forum & docs
- [x] Checked for existing issues
- [x] Attached log file
- [x] Provided technical details incl. operating system

**Comment by Catreina** [comment]
I am going to second this, but I would also like to state that there is no "automatic output" of Ghost-CLI with this error:

```
? Do you want to start Ghost? Yes
+ sudo systemctl start REDACTED
☴ Starting Ghost/usr/lib/node_modules/ghost-cli/lib/utils/port-polling.js:68
                    let {message: errMsg} = message.error;
                                  ^

TypeError: Cannot destructure property 'message' of 'message.error' as it is undefined.
    at Server.<anonymous> (/usr/lib/node_modules/ghost-cli/lib/utils/port-polling.js:68:35)
    at Object.onceWrapper (node:events:509:28)
    at Server.emit (node:events:390:28)
    at emitCloseNT (node:net:1681:8)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

This on a fresh install of Ghost

**Comment by ErisDS** [comment]
This was raised/managed in Ghost [here](https://github.com/TryGhost/Ghost/issues/13837) and fixed [here](https://github.com/TryGhost/Ghost/commit/ec284784352bfd7f612ddf43c7448e2070764ece) - sorry that we missed this issue!
