### ISSUE TITLE
Server installation fail: Command failed: yarn install --no-emoji --no-progress

### ISSUE THREAD

**Issue by vgrosdoy** [TryGhost/Ghost-CLI#1658]
I have the same issue today as the issue #696 , whatever the ghost version (I tried 4.39.0 - 4.48.0 - 4.48.2 - 5.2.3)

docspriv@srv002:/var/www/docspriv/docs.priv$ ghost install 4.39.0

Love open source? We’re hiring Node.js Engineers to work on Ghost full-time.
https://careers.ghost.org/product-engineer-node-js

✔ Checking system Node.js version - found v16.15.1
✔ Checking logged in user
✔ Checking current folder permissions
✔ Checking system compatibility
✔ Checking for a MySQL installation
✔ Checking memory availability
✔ Checking free space
✔ Checking for latest Ghost version
✔ Setting up install directory
✖ Downloading and installing Ghost v4.39.0
A ProcessError occurred.

Message: Command failed: yarn install --no-emoji --no-progress
warning ghost@4.39.0: The engine "cli" appears to be invalid.
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@^2.29.1"
warning Resolution field "moment-timezone@0.5.23" is incompatible with requested version "moment-timezone@^0.5.33"
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@^2.29.1"
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@^2.27.0"
warning Resolution field "moment-timezone@0.5.23" is incompatible with requested version "moment-timezone@^0.5.31"
warning Resolution field "moment-timezone@0.5.23" is incompatible with requested version "moment-timezone@0.5.34"
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@^2.27.0"
warning Resolution field "moment-timezone@0.5.23" is incompatible with requested version "moment-timezone@^0.5.31"
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@2.27.0"
warning Resolution field "@tryghost/logging@2.0.4" is incompatible with requested version "@tryghost/logging@2.0.1"
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@2.27.0"
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@^2.29.1"
warning Error running install script for optional dependency: "/var/www/docspriv/docs.priv/versions/4.39.0/node_modules/sqlite3: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments: 
Directory: /var/www/docspriv/docs.priv/versions/4.39.0/node_modules/sqlite3
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.11.0
[skip...]

    OS: Ubuntu, v20.04.4 LTS
    Node Version: v16.15.1
    Ghost-CLI Version: 1.21.0
    Environment: production
    Command: 'ghost install 4.39.0'

**Comment by ruanspies** [comment]
Is there any updates on this? 

I am experiencing the exact same issue and am unable to create a local instance of Ghost. My error log is shown below:

```
Debug Information:
    OS: macOS, v12.6
    Node Version: v16.17.0
    Ghost-CLI Version: 1.23.1
    Environment: development
    Command: 'ghost install local'
Message: Command failed: yarn install --no-emoji --no-progress
warning ghost@5.18.0: The engine "cli" appears to be invalid.
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@^2.29.1"
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@2.29.1"
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@2.29.4"
warning Resolution field "moment-timezone@0.5.23" is incompatible with requested version "moment-timezone@0.5.34"
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@2.29.1"
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@^2.29.3"
warning Resolution field "moment-timezone@0.5.23" is incompatible with requested version "moment-timezone@^0.5.33"
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@^2.27.0"
warning Resolution field "moment-timezone@0.5.23" is incompatible with requested version "moment-timezone@^0.5.31"
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@2.27.0"
warning Resolution field "@tryghost/logging@2.3.2" is incompatible with requested version "@tryghost/logging@2.2.3"
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@^2.29.1"
warning "@tryghost/kg-lexical-html-renderer > @lexical/rich-text@0.4.1" has unmet peer dependency "@lexical/selection@0.4.1".
warning "@tryghost/kg-lexical-html-renderer > @lexical/rich-text@0.4.1" has unmet peer dependency "@lexical/utils@0.4.1".
warning " > bookshelf@1.2.0" has incorrect peer dependency "knex@>=0.15.0 <0.22.0".
warning " > mock-knex@0.4.9" has incorrect peer dependency "knex@> 0.8 < 2.1".
warning Workspaces can only be enabled in private projects.
error /Users/ruanspies/test/ghost/versions/5.18.0/node_modules/re2: Command failed.
Exit code: 1
Command: install-from-cache --artifact build/Release/re2.node --host-var RE2_DOWNLOAD_MIRROR --skip-path-var RE2_DOWNLOAD_SKIP_PATH --skip-ver-var RE2_DOWNLOAD_SKIP_VER || npm run rebuild
Arguments: 
Directory: /Users/ruanspies/test/ghost/versions/5.18.0/node_modules/re2
Output:
Trying https://github.com/uhop/node-re2/releases/download/1.17.7/darwin-arm64-93.br ...
Trying https://github.com/uhop/node-re2/releases/download/1.17.7/darwin-arm64-93.gz ...
Building locally ...

> re2@1.17.7 rebuild
> node-gyp rebuild

gyp info it worked if it ends with ok
gyp info using node-gyp@9.1.0
gyp info using node@16.17.0 | darwin | arm64
gyp info find Python using Python version 3.9.1 found at "/usr/local/bin/python3"
gyp info spawn /usr/local/bin/python3
gyp info spawn args [
gyp info spawn args   '/Users/ruanspies/test/ghost/versions/5.18.0/node_modules/re2/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/ruanspies/test/ghost/versions/5.18.0/node_modules/re2/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/ruanspies/test/ghost/versions/5.18.0/node_modules/re2/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/ruanspies/Library/Caches/node-gyp/13.5.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/ruanspies/Library/Caches/node-gyp/13.5.2',
gyp info spawn args   '-Dnode_gyp_dir=/Users/ruanspies/test/ghost/versions/5.18.0/node_modules/re2/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/ruanspies/Library/Caches/node-gyp/13.5.2/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/ruanspies/test/ghost/versions/5.18.0/node_modules/re2',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp: name 'openssl_fips' is not defined while evaluating condition 'openssl_fips != ""' in binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/ruanspies/test/ghost/versions/5.18.0/node_modules/re2/node_modules/node-gyp/lib/configure.js:284:16)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Darwin 21.6.0
gyp ERR! command "/usr/local/bin/node" "/Users/ruanspies/test/ghost/versions/5.18.0/node_modules/re2/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/ruanspies/test/ghost/versions/5.18.0/node_modules/re2
gyp ERR! node -v v16.17.0
gyp ERR! node-gyp -v v9.1.0
gyp ERR! not ok 
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "1".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

> re2@1.17.7 rebuild
> node-gyp rebuild

gyp info it worked if it ends with ok
gyp info using node-gyp@9.1.0
gyp info using node@16.17.0 | darwin | arm64
gyp info find Python using Python version 3.9.1 found at "/usr/local/bin/python3"
gyp info spawn /usr/local/bin/python3
gyp info spawn args [
gyp info spawn args   '/Users/ruanspies/test/ghost/versions/5.18.0/node_modules/re2/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/ruanspies/test/ghost/versions/5.18.0/node_modules/re2/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/ruanspies/test/ghost/versions/5.18.0/node_modules/re2/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/ruanspies/Library/Caches/node-gyp/13.5.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/ruanspies/Library/Caches/node-gyp/13.5.2',
gyp info spawn args   '-Dnode_gyp_dir=/Users/ruanspies/test/ghost/versions/5.18.0/node_modules/re2/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/ruanspies/Library/Caches/node-gyp/13.5.2/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/ruanspies/test/ghost/versions/5.18.0/node_modules/re2',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp: name 'openssl_fips' is not defined while evaluating condition 'openssl_fips != ""' in binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/ruanspies/test/ghost/versions/5.18.0/node_modules/re2/node_modules/node-gyp/lib/configure.js:284:16)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Darwin 21.6.0
gyp ERR! command "/usr/local/bin/node" "/Users/ruanspies/test/ghost/versions/5.18.0/node_modules/re2/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/ruanspies/test/ghost/versions/5.18.0/node_modules/re2
gyp ERR! node -v v16.17.0
gyp ERR! node-gyp -v v9.1.0
gyp ERR! not ok
warning Error running install script for optional dependency: "/Users/ruanspies/test/ghost/versions/5.18.0/node_modules/sharp: Command failed.
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
Arguments: 
Directory: /Users/ruanspies/test/ghost/versions/5.18.0/node_modules/sharp
Output:
sharp: Using cached /Users/ruanspies/.npm/_libvips/libvips-8.12.2-darwin-arm64v8.tar.br
sharp: Integrity check passed for darwin-arm64v8
gyp info it worked if it ends with ok
gyp info using node-gyp@9.0.0
gyp info using node@16.17.0 | darwin | arm64
gyp info find Python using Python version 3.9.1 found at \"/usr/local/bin/python3\"
gyp info spawn /usr/local/bin/python3
gyp info spawn args [
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/ruanspies/test/ghost/versions/5.18.0/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/ruanspies/Library/Caches/node-gyp/13.5.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/ruanspies/Library/Caches/node-gyp/13.5.2',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/ruanspies/Library/Caches/node-gyp/13.5.2/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/ruanspies/test/ghost/versions/5.18.0/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp: name 'openssl_fips' is not defined while evaluating condition 'openssl_fips != \"\"' in binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:261:16)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Darwin 21.6.0
gyp ERR! command \"/usr/local/bin/node\" \"/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
gyp ERR! cwd /Users/ruanspies/test/ghost/versions/5.18.0/node_modules/sharp
gyp ERR! node -v v16.17.0
gyp ERR! node-gyp -v v9.0.0
gyp ERR! not ok"

yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
[5/5] Building fresh packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
info This module is OPTIONAL, you can safely ignore this error

Exit code: 1

--------------- stdout ---------------
yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
[5/5] Building fresh packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
info This module is OPTIONAL, you can safely ignore this error


--------------- stderr ---------------
warning ghost@5.18.0: The engine "cli" appears to be invalid.
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@^2.29.1"
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@2.29.1"
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@2.29.4"
warning Resolution field "moment-timezone@0.5.23" is incompatible with requested version "moment-timezone@0.5.34"
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@2.29.1"
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@^2.29.3"
warning Resolution field "moment-timezone@0.5.23" is incompatible with requested version "moment-timezone@^0.5.33"
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@^2.27.0"
warning Resolution field "moment-timezone@0.5.23" is incompatible with requested version "moment-timezone@^0.5.31"
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@2.27.0"
warning Resolution field "@tryghost/logging@2.3.2" is incompatible with requested version "@tryghost/logging@2.2.3"
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@^2.29.1"
warning "@tryghost/kg-lexical-html-renderer > @lexical/rich-text@0.4.1" has unmet peer dependency "@lexical/selection@0.4.1".
warning "@tryghost/kg-lexical-html-renderer > @lexical/rich-text@0.4.1" has unmet peer dependency "@lexical/utils@0.4.1".
warning " > bookshelf@1.2.0" has incorrect peer dependency "knex@>=0.15.0 <0.22.0".
warning " > mock-knex@0.4.9" has incorrect peer dependency "knex@> 0.8 < 2.1".
warning Workspaces can only be enabled in private projects.
error /Users/ruanspies/test/ghost/versions/5.18.0/node_modules/re2: Command failed.
Exit code: 1
Command: install-from-cache --artifact build/Release/re2.node --host-var RE2_DOWNLOAD_MIRROR --skip-path-var RE2_DOWNLOAD_SKIP_PATH --skip-ver-var RE2_DOWNLOAD_SKIP_VER || npm run rebuild
Arguments: 
Directory: /Users/ruanspies/test/ghost/versions/5.18.0/node_modules/re2
Output:
Trying https://github.com/uhop/node-re2/releases/download/1.17.7/darwin-arm64-93.br ...
Trying https://github.com/uhop/node-re2/releases/download/1.17.7/darwin-arm64-93.gz ...
Building locally ...

> re2@1.17.7 rebuild
> node-gyp rebuild

gyp info it worked if it ends with ok
gyp info using node-gyp@9.1.0
gyp info using node@16.17.0 | darwin | arm64
gyp info find Python using Python version 3.9.1 found at "/usr/local/bin/python3"
gyp info spawn /usr/local/bin/python3
gyp info spawn args [
gyp info spawn args   '/Users/ruanspies/test/ghost/versions/5.18.0/node_modules/re2/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/ruanspies/test/ghost/versions/5.18.0/node_modules/re2/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/ruanspies/test/ghost/versions/5.18.0/node_modules/re2/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/ruanspies/Library/Caches/node-gyp/13.5.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/ruanspies/Library/Caches/node-gyp/13.5.2',
gyp info spawn args   '-Dnode_gyp_dir=/Users/ruanspies/test/ghost/versions/5.18.0/node_modules/re2/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/ruanspies/Library/Caches/node-gyp/13.5.2/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/ruanspies/test/ghost/versions/5.18.0/node_modules/re2',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp: name 'openssl_fips' is not defined while evaluating condition 'openssl_fips != ""' in binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/ruanspies/test/ghost/versions/5.18.0/node_modules/re2/node_modules/node-gyp/lib/configure.js:284:16)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Darwin 21.6.0
gyp ERR! command "/usr/local/bin/node" "/Users/ruanspies/test/ghost/versions/5.18.0/node_modules/re2/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/ruanspies/test/ghost/versions/5.18.0/node_modules/re2
gyp ERR! node -v v16.17.0
gyp ERR! node-gyp -v v9.1.0
gyp ERR! not ok 
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "1".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

> re2@1.17.7 rebuild
> node-gyp rebuild

gyp info it worked if it ends with ok
gyp info using node-gyp@9.1.0
gyp info using node@16.17.0 | darwin | arm64
gyp info find Python using Python version 3.9.1 found at "/usr/local/bin/python3"
gyp info spawn /usr/local/bin/python3
gyp info spawn args [
gyp info spawn args   '/Users/ruanspies/test/ghost/versions/5.18.0/node_modules/re2/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/ruanspies/test/ghost/versions/5.18.0/node_modules/re2/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/ruanspies/test/ghost/versions/5.18.0/node_modules/re2/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/ruanspies/Library/Caches/node-gyp/13.5.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/ruanspies/Library/Caches/node-gyp/13.5.2',
gyp info spawn args   '-Dnode_gyp_dir=/Users/ruanspies/test/ghost/versions/5.18.0/node_modules/re2/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/ruanspies/Library/Caches/node-gyp/13.5.2/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/ruanspies/test/ghost/versions/5.18.0/node_modules/re2',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp: name 'openssl_fips' is not defined while evaluating condition 'openssl_fips != ""' in binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/ruanspies/test/ghost/versions/5.18.0/node_modules/re2/node_modules/node-gyp/lib/configure.js:284:16)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Darwin 21.6.0
gyp ERR! command "/usr/local/bin/node" "/Users/ruanspies/test/ghost/versions/5.18.0/node_modules/re2/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/ruanspies/test/ghost/versions/5.18.0/node_modules/re2
gyp ERR! node -v v16.17.0
gyp ERR! node-gyp -v v9.1.0
gyp ERR! not ok
warning Error running install script for optional dependency: "/Users/ruanspies/test/ghost/versions/5.18.0/node_modules/sharp: Command failed.
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
Arguments: 
Directory: /Users/ruanspies/test/ghost/versions/5.18.0/node_modules/sharp
Output:
sharp: Using cached /Users/ruanspies/.npm/_libvips/libvips-8.12.2-darwin-arm64v8.tar.br
sharp: Integrity check passed for darwin-arm64v8
gyp info it worked if it ends with ok
gyp info using node-gyp@9.0.0
gyp info using node@16.17.0 | darwin | arm64
gyp info find Python using Python version 3.9.1 found at \"/usr/local/bin/python3\"
gyp info spawn /usr/local/bin/python3
gyp info spawn args [
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/ruanspies/test/ghost/versions/5.18.0/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/ruanspies/Library/Caches/node-gyp/13.5.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/ruanspies/Library/Caches/node-gyp/13.5.2',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/ruanspies/Library/Caches/node-gyp/13.5.2/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/ruanspies/test/ghost/versions/5.18.0/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp: name 'openssl_fips' is not defined while evaluating condition 'openssl_fips != \"\"' in binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:261:16)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Darwin 21.6.0
gyp ERR! command \"/usr/local/bin/node\" \"/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
gyp ERR! cwd /Users/ruanspies/test/ghost/versions/5.18.0/node_modules/sharp
gyp ERR! node -v v16.17.0
gyp ERR! node-gyp -v v9.0.0
gyp ERR! not ok"
```

**Comment by ErisDS** [comment]
To clarify, `yarn install --no-emoji --no-progress` is the _command_ that failed to run - not the error message.

The log out put from you both (@vgrosdoy & @ruanspies) shows completely different errors - both to do with trying to build binary dependencies that have to be compiled during the `yarn install` command.

I don't have much more to add but if you're not able to debug from the error output the [forum](https://forum.ghost.org) is a much better place to get help with install issues that the CLI repo 🙂

**Comment by mlc-mlapis** [comment]
We still have exactly the same problem, both on Ubuntu and Windows, even with the latest Ghost version 5.20.0.
```
yarn install v1.22.19
[1/5] Validating package.json...
warning ghost@5.20.0: The engine "cli" appears to be invalid.
[2/5] Resolving packages...
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@^2.29.1"
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@2.29.1"
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@2.29.4"
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@2.29.4"
warning Resolution field "moment-timezone@0.5.23" is incompatible with requested version "moment-timezone@0.5.34"
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@2.29.1"
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@2.29.3"
warning Resolution field "moment-timezone@0.5.23" is incompatible with requested version "moment-timezone@^0.5.33"
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@2.29.1"
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@^2.27.0"
warning Resolution field "moment-timezone@0.5.23" is incompatible with requested version "moment-timezone@^0.5.31"
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@2.29.4"
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@2.29.4"
warning Resolution field "moment-timezone@0.5.23" is incompatible with requested version "moment-timezone@0.5.34"
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@2.29.1"
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@2.29.3"
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@2.27.0"
warning Resolution field "@tryghost/logging@2.3.2" is incompatible with requested version "@tryghost/logging@2.2.3"
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@^2.29.1"
success Already up-to-date.
Done in 0.92s.
```
