### ISSUE TITLE
ghost install local error (On the local ubuntu computer)

### ISSUE THREAD

**Issue by scooomaker** [TryGhost/Ghost-CLI#1711]
I ran `ghost install local`,but it keeps showing errors:
```
➜  ghost install local


✔ Checking system Node.js version - found v16.13.0
✔ Checking current folder permissions
✔ Checking memory availability
✔ Checking free space
✖ Checking for latest Ghost version
An error occurred.
Message: 'Cannot read properties of undefined (reading 'statusCode')'


Debug Information:
    OS: Ubuntu, v22.04.1 LTS
    Node Version: v16.13.0
    Ghost-CLI Version: 1.23.1
    Environment: development
    Command: 'ghost install local'

Additional log info available in: /home/scooo/.ghost/logs/ghost-cli-debug-2022-11-10T03_57_06_144Z.log

Try running ghost doctor to check your system for known issues.
```

Debug Information:
```
Debug Information:
    OS: Ubuntu, v22.04.1 LTS
    Node Version: v16.13.0
    Ghost-CLI Version: 1.23.1
    Environment: development
    Command: 'ghost install local'
An error occurred.
Message: 'Cannot read properties of undefined (reading 'statusCode')'

Stack: TypeError: Cannot read properties of undefined (reading 'statusCode')
    at packageJson (/home/scooo/.nvm/versions/node/v16.13.0/lib/node_modules/ghost-cli/node_modules/package-json/index.js:71:22)
    at async Object.loadVersions (/home/scooo/.nvm/versions/node/v16.13.0/lib/node_modules/ghost-cli/lib/utils/version.js:15:24)
    at async resolveVersion (/home/scooo/.nvm/versions/node/v16.13.0/lib/node_modules/ghost-cli/lib/utils/version.js:133:26)
    at async Task.version [as task] (/home/scooo/.nvm/versions/node/v16.13.0/lib/node_modules/ghost-cli/lib/commands/install.js:121:31)
```
I tried to reinstall ghost-cli and node.js , but they didn't work.

run ` ghost doctor` :
```
➜  ghost doctor

Working directory is not a recognisable Ghost installation.
Run `ghost doctor` again within a folder where Ghost was installed with Ghost-CLI.
```
It still say `Working directory is not a recognisable Ghost installation`.
I make sure the folder is new and I give it read and write permissions.

This problem has been bothering me for many days, What's caused this error and how can I fix that? Thank you.

**Comment by scooomaker** [comment]
I ran it successfully on win11. I think this problem is only for ubuntu22.04, because it seems to regard my local computer as a server.

**Comment by scooomaker** [comment]
The cause is proxy.
sorry ......
Use tty found this problem.

**Comment by KonngExplorer** [comment]
> The cause is proxy. sorry ...... Use tty found this problem.

Could you please tell me how you solved it? I also encountered this problem.
