### ISSUE TITLE
Ghost-CLI needs permissions in cwd

### ISSUE THREAD

**Issue by sebgie** [TryGhost/Ghost-CLI#277]
I was logged in to a server and switched user. Which leads to the situation that I don't have any rights to the current working directory. When running the `ghost help` command. Switching to another folder where I have read permissions `ghost help` works.

Not a huge problem but weird that ghost-cli would need read permissions in the current working dir?

```
root:root$ su admin2
admin2:/root$ ghost 
No command specified. Run `ghost help` for usage
admin2:/root$ ghost help
fs.js:952
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: EACCES: permission denied, scandir '/root'
    at Error (native)
    at Object.fs.readdirSync (fs.js:952:18)
    at findCandidatesInDir (/usr/lib/node_modules/ghost-cli/node_modules/find-plugins/index.js:62:15)
    at findPlugins (/usr/lib/node_modules/ghost-cli/node_modules/find-plugins/index.js:29:58)
    at findExtensions (/usr/lib/node_modules/ghost-cli/lib/utils/find-extensions.js:26:12)
    at Object.run (/usr/lib/node_modules/ghost-cli/lib/bootstrap.js:69:26)
    at Object.<anonymous> (/usr/lib/node_modules/ghost-cli/bin/ghost:12:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
```

**Comment by acburdine** [comment]
@sebgie do you know if you're running the latest ghost-cli version? This error I could see happening in ghost-cli beta.1, but I fixed it in ghost-cli beta.2.

**Comment by sebgie** [comment]
`beta4`, it ironically also fails when running `ghost version`. 

```
admin2:/root$ ghost version
fs.js:952
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: EACCES: permission denied, scandir '/root'
    at Error (native)
    at Object.fs.readdirSync (fs.js:952:18)
    at findCandidatesInDir (/usr/lib/node_modules/ghost-cli/node_modules/find-plugins/index.js:62:15)
    at findPlugins (/usr/lib/node_modules/ghost-cli/node_modules/find-plugins/index.js:29:58)
    at findExtensions (/usr/lib/node_modules/ghost-cli/lib/utils/find-extensions.js:26:12)
    at Object.run (/usr/lib/node_modules/ghost-cli/lib/bootstrap.js:69:26)
    at Object.<anonymous> (/usr/lib/node_modules/ghost-cli/bin/ghost:12:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
admin2:/root$ sudo ghost version
Ghost-CLI version: 1.0.0-beta.4
```

**Comment by sebgie** [comment]
Installed beta5 a minute ago, same issue.

**Comment by acburdine** [comment]
So I wasn't able to replicate this error specifically, but what I _was_ able to get was other errors originating from `npm root -g`. Basically, if you don't have read rights to the current folder then you're not gonna have a good day. Need to figure out a better way to handle this error....

**Comment by acburdine** [comment]
Ok so I was able to replicate this error - it's actually being thrown from npm this time.

Gonna close this as a wontfix - the _only_ way you get into this situation is if you are logged in as root, are in a directory that only root can read, and run `su <otheruser>` . (note: this is different from `su - <otheruser>`). Basically this is an _extreme_ edge case and adding a check just for this case seems a bit much.

Can reopen later if this happens more often for people.
