### ISSUE TITLE
Skip MySQL extension if sqlite was configured

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost-CLI#304]
```
root@dev-kate-01:/var/www/ghost# ghost install --url https://kate-ghost-test.acburdine.me --db sqlite3 --dbpath ./content/data/ghost.db
✔ Checking for latest Ghost version
✔ Running system checks
✔ Setting up install directory
✔ Downloading and installing Ghost v1.0.0-beta.2
✔ Moving files
✔ Configuring Ghost
✔ Running setup checks
✔ Setting up instance
? Do you wish to set up a ghost mysql user? (Y/n)
```

**Comment by regalstreak** [comment]
Any idea on how I get around this? As looks like you successfully got an sqlite3 install. It is trying to connect to the mysql host (I dont have mysql set up) even though i want to use sqlite

`root@thecyberfibre:~/.ghost/logs# cat ghost-cli-debug-2017-07-10T09_31_35_408Z.log 
Debug Information:
    Node Version: v6.11.0
    Ghost-CLI Version: 1.0.0-beta.6
    Environment: production
    Command: 'ghost install --db sqlite3 --dbpath ./content/data/ghost.db'
An error occurred.
Message: 'connect ECONNREFUSED 127.0.0.1:3306'

Stack: Error: connect ECONNREFUSED 127.0.0.1:3306
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
    --------------------
    at Protocol._enqueue (/usr/lib/node_modules/ghost-cli/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Protocol.handshake (/usr/lib/node_modules/ghost-cli/node_modules/mysql/lib/protocol/Protocol.js:52:41)
    at Connection.connect (/usr/lib/node_modules/ghost-cli/node_modules/mysql/lib/Connection.js:130:18)
    at /usr/lib/node_modules/ghost-cli/node_modules/knex/lib/dialects/mysql/index.js:106:18
    at Promise._execute (/usr/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/usr/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/usr/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:79:10)
    at Client_MySQL.acquireRawConnection (/usr/lib/node_modules/ghost-cli/node_modules/knex/lib/dialects/mysql/index.js:104:12)
    at Object.create (/usr/lib/node_modules/ghost-cli/node_modules/knex/lib/client.js:239:16)
    at Pool._createResource (/usr/lib/node_modules/ghost-cli/node_modules/generic-pool/lib/generic-pool.js:354:17)
    at Pool._ensureMinimum (/usr/lib/node_modules/ghost-cli/node_modules/generic-pool/lib/generic-pool.js:408:12)
    at new Pool (/usr/lib/node_modules/ghost-cli/node_modules/generic-pool/lib/generic-pool.js:157:8)
    at Client_MySQL.initializePool (/usr/lib/node_modules/ghost-cli/node_modules/knex/lib/client.js:269:17)
    at Client_MySQL.Client (/usr/lib/node_modules/ghost-cli/node_modules/knex/lib/client.js:116:12)
    at new Client_MySQL (/usr/lib/node_modules/ghost-cli/node_modules/knex/lib/dialects/mysql/index.js:62:20)
    at Knex (/usr/lib/node_modules/ghost-cli/node_modules/knex/lib/index.js:60:34)
Code: ECONNREFUSED
root@thecyberfibre:~/.ghost/logs# 
`

**Comment by acburdine** [comment]
As per #325, this also needs to be updated to better handle config prompts, e.g. skipping the mysql config prompts if sqlite is configured.

**Comment by flip111** [comment]
Documentation is pointing to the issue, but this issue is closed https://docs.ghost.org/v1/docs/using-ghost-cli-programatically
