### ISSUE TITLE
Error on setup systemd: Expected property `title` to be of type `string`, but undefined

### ISSUE THREAD

**Issue by wookayin** [TryGhost/Ghost-CLI#360]
### This issue is a

* [x] Bug Report
* [ ] Feature Request

### Summary

The following error occurs when trying to setup systemd on linux:

```
Debug Information:
    Node Version: v6.9.2
    Ghost-CLI Version: 1.0.0-rc.2
    Environment: production
    Command: 'ghost setup linux-user systemd'
An error occurred.
Message: 'Expected property `title` to be of type `string`, got `undefined`'
```

### Steps to Reproduce (for a bug report)

Just 'ghost setup linux-user systemd'.

### Technical details (will be automatically output by Ghost-CLI if an error occurs):

* OS: Ubuntu 16.04
* Node Version: 6.9.2
* Ghost-CLI Version: 1.0.0-rc.2
* Environment: production
* Command: `ghost setup linux-user systemd`

### Stacktrace from the log

```
Stack: TypeError: Expected property `title` to be of type `string`, got `undefined`
    at new Task (/usr/lib/node_modules/ghost-cli/node_modules/listr/lib/task.js:23:10)
    at Listr.add (/usr/lib/node_modules/ghost-cli/node_modules/listr/index.js:72:21)
    at new Listr (/usr/lib/node_modules/ghost-cli/node_modules/listr/index.js:51:8)
    at UI.listr (/usr/lib/node_modules/ghost-cli/lib/ui/index.js:164:21)
    at system.hook.then (/usr/lib/node_modules/ghost-cli/lib/commands/setup.js:96:32)
    at tryCatcher (/usr/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/usr/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
```

**Comment by acburdine** [comment]
This is a known issue, has been fixed in master and will be released in the next version.

**Comment by wookayin** [comment]
Thanks, I checked out the latest source.
