### ISSUE TITLE
mysql user setup sometimes has issues with creating passwords

### ISSUE THREAD

**Issue by acburdine** [TryGhost/Ghost-CLI#396]
As reported by @Penderworth over in #378:

<details>
  <summary>Error Log</summary>

```
Debug Information:
    Node Version: v6.5.0
    Ghost-CLI Version: 1.0.0
    Environment: production
    Command: 'ghost install'
An error occurred.
Message: 'Command failed: /bin/sh -c sudo -E -u ghost /usr/local/lib/node_modules/ghost-cli/node_modules/.bin/knex-migrator-migrate --init --mgpath /var/www/ghost/current
[2017-07-27 10:08:56] ERROR

NAME: InternalServerError
CODE: ER_NOT_SUPPORTED_AUTH_MODE
MESSAGE: The server has encountered an error.

level:normal

InternalServerError: The server has encountered an error.
    at new KnexMigrateError (/usr/local/lib/node_modules/ghost-cli/node_modules/knex-migrator/lib/errors.js:7:26)
    at /usr/local/lib/node_modules/ghost-cli/node_modules/knex-migrator/lib/database.js:58:19
    at tryCatcher (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)

Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
    at Handshake.Sequence._packetToError (/usr/local/lib/node_modules/ghost-cli/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Handshake.ErrorPacket (/usr/local/lib/node_modules/ghost-cli/node_modules/mysql/lib/protocol/sequences/Handshake.js:103:18)
    at Protocol._parsePacket (/usr/local/lib/node_modules/ghost-cli/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/usr/local/lib/node_modules/ghost-cli/node_modules/mysql/lib/protocol/Parser.js:75:12)
    at Protocol.write (/usr/local/lib/node_modules/ghost-cli/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/usr/local/lib/node_modules/ghost-cli/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
    --------------------
    at Protocol._enqueue (/usr/local/lib/node_modules/ghost-cli/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Protocol.handshake (/usr/local/lib/node_modules/ghost-cli/node_modules/mysql/lib/protocol/Protocol.js:52:41)
    at Connection.connect (/usr/local/lib/node_modules/ghost-cli/node_modules/mysql/lib/Connection.js:130:18)
    at /usr/local/lib/node_modules/ghost-cli/node_modules/knex-migrator/node_modules/knex/lib/dialects/mysql/index.js:106:18
    at Promise._execute (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:79:10)
    at Client_MySQL.acquireRawConnection (/usr/local/lib/node_modules/ghost-cli/node_modules/knex-migrator/node_modules/knex/lib/dialects/mysql/index.js:104:12)
    at Object.create (/usr/local/lib/node_modules/ghost-cli/node_modules/knex-migrator/node_modules/knex/lib/client.js:239:16)
    at Pool._createResource (/usr/local/lib/node_modules/ghost-cli/node_modules/knex-migrator/node_modules/knex/node_modules/generic-pool/lib/generic-pool.js:354:17)
    at Pool._ensureMinimum (/usr/local/lib/node_modules/ghost-cli/node_modules/knex-migrator/node_modules/knex/node_modules/generic-pool/lib/generic-pool.js:408:12)
    at new Pool (/usr/local/lib/node_modules/ghost-cli/node_modules/knex-migrator/node_modules/knex/node_modules/generic-pool/lib/generic-pool.js:157:8)
    at Client_MySQL.initializePool (/usr/local/lib/node_modules/ghost-cli/node_modules/knex-migrator/node_modules/knex/lib/client.js:269:17)
    at Client_MySQL.Client (/usr/local/lib/node_modules/ghost-cli/node_modules/knex-migrator/node_modules/knex/lib/client.js:116:12)
    at new Client_MySQL (/usr/local/lib/node_modules/ghost-cli/node_modules/knex-migrator/node_modules/knex/lib/dialects/mysql/index.js:62:20)
    at Knex (/usr/local/lib/node_modules/ghost-cli/node_modules/knex-migrator/node_modules/knex/lib/index.js:60:34)
    at Object.connect (/usr/local/lib/node_modules/ghost-cli/node_modules/knex-migrator/lib/database.js:24:12)
    at Object.createDatabaseIfNotExist (/usr/local/lib/node_modules/ghost-cli/node_modules/knex-migrator/lib/database.js:41:30)
    at KnexMigrator.init (/usr/local/lib/node_modules/ghost-cli/node_modules/knex-migrator/lib/index.js:71:21)
    at KnexMigrator.migrate (/usr/local/lib/node_modules/ghost-cli/node_modules/knex-migrator/lib/index.js:158:21)
    at /usr/local/lib/node_modules/ghost-cli/node_modules/knex-migrator/bin/knex-migrator-migrate:26:29
    at tryCatcher (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/util.js:16:23)


'

Stack: Error: Command failed: /bin/sh -c sudo -E -u ghost /usr/local/lib/node_modules/ghost-cli/node_modules/.bin/knex-migrator-migrate --init --mgpath /var/www/ghost/current
[2017-07-27 10:08:56] ERROR

NAME: InternalServerError
CODE: ER_NOT_SUPPORTED_AUTH_MODE
MESSAGE: The server has encountered an error.

level:normal

InternalServerError: The server has encountered an error.
    at new KnexMigrateError (/usr/local/lib/node_modules/ghost-cli/node_modules/knex-migrator/lib/errors.js:7:26)
    at /usr/local/lib/node_modules/ghost-cli/node_modules/knex-migrator/lib/database.js:58:19
    at tryCatcher (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)

Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
    at Handshake.Sequence._packetToError (/usr/local/lib/node_modules/ghost-cli/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Handshake.ErrorPacket (/usr/local/lib/node_modules/ghost-cli/node_modules/mysql/lib/protocol/sequences/Handshake.js:103:18)
    at Protocol._parsePacket (/usr/local/lib/node_modules/ghost-cli/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/usr/local/lib/node_modules/ghost-cli/node_modules/mysql/lib/protocol/Parser.js:75:12)
    at Protocol.write (/usr/local/lib/node_modules/ghost-cli/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/usr/local/lib/node_modules/ghost-cli/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
    --------------------
    at Protocol._enqueue (/usr/local/lib/node_modules/ghost-cli/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Protocol.handshake (/usr/local/lib/node_modules/ghost-cli/node_modules/mysql/lib/protocol/Protocol.js:52:41)
    at Connection.connect (/usr/local/lib/node_modules/ghost-cli/node_modules/mysql/lib/Connection.js:130:18)
    at /usr/local/lib/node_modules/ghost-cli/node_modules/knex-migrator/node_modules/knex/lib/dialects/mysql/index.js:106:18
    at Promise._execute (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:79:10)
    at Client_MySQL.acquireRawConnection (/usr/local/lib/node_modules/ghost-cli/node_modules/knex-migrator/node_modules/knex/lib/dialects/mysql/index.js:104:12)
    at Object.create (/usr/local/lib/node_modules/ghost-cli/node_modules/knex-migrator/node_modules/knex/lib/client.js:239:16)
    at Pool._createResource (/usr/local/lib/node_modules/ghost-cli/node_modules/knex-migrator/node_modules/knex/node_modules/generic-pool/lib/generic-pool.js:354:17)
    at Pool._ensureMinimum (/usr/local/lib/node_modules/ghost-cli/node_modules/knex-migrator/node_modules/knex/node_modules/generic-pool/lib/generic-pool.js:408:12)
    at new Pool (/usr/local/lib/node_modules/ghost-cli/node_modules/knex-migrator/node_modules/knex/node_modules/generic-pool/lib/generic-pool.js:157:8)
    at Client_MySQL.initializePool (/usr/local/lib/node_modules/ghost-cli/node_modules/knex-migrator/node_modules/knex/lib/client.js:269:17)
    at Client_MySQL.Client (/usr/local/lib/node_modules/ghost-cli/node_modules/knex-migrator/node_modules/knex/lib/client.js:116:12)
    at new Client_MySQL (/usr/local/lib/node_modules/ghost-cli/node_modules/knex-migrator/node_modules/knex/lib/dialects/mysql/index.js:62:20)
    at Knex (/usr/local/lib/node_modules/ghost-cli/node_modules/knex-migrator/node_modules/knex/lib/index.js:60:34)
    at Object.connect (/usr/local/lib/node_modules/ghost-cli/node_modules/knex-migrator/lib/database.js:24:12)
    at Object.createDatabaseIfNotExist (/usr/local/lib/node_modules/ghost-cli/node_modules/knex-migrator/lib/database.js:41:30)
    at KnexMigrator.init (/usr/local/lib/node_modules/ghost-cli/node_modules/knex-migrator/lib/index.js:71:21)
    at KnexMigrator.migrate (/usr/local/lib/node_modules/ghost-cli/node_modules/knex-migrator/lib/index.js:158:21)
    at /usr/local/lib/node_modules/ghost-cli/node_modules/knex-migrator/bin/knex-migrator-migrate:26:29
    at tryCatcher (/usr/local/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/util.js:16:23)



    at Promise.all.then.arr (/usr/local/lib/node_modules/ghost-cli/node_modules/execa/index.js:231:11)
    at process._tickCallback (internal/process/next_tick.js:103:7)
Code: 1
```
</details>

After some investigation, this issue occurs in mysql 5.7 when the authentication plugin is set to something other than mysql_password_native. Because we're creating the password directly (see [here](https://github.com/TryGhost/Ghost-CLI/blob/master/extensions/mysql/index.js#L92)) rather than doing something like `PASSWORD('somepass')` it has issues.

My initial thought would be to just have it do `PASSWORD('password')` instead of putting the password in the plaintext query, but I need to verify that it works in all cases (e.g. on a system that currently works and doesn't throw the above error, will changing the query still work?)

**Comment by postblue** [comment]
Following as I have this error:

```
✖ Running database migrations
A ConfigError occurred.

Error detected in the production configuration.

Message: Invalid database username or password
Configuration Key(s): database.connection.user / database.connection.password
```

**Comment by the4dpatrick** [comment]
Is there a workaround in the meantime while this is being worked on? I'm currently blocked installing Ghost on a fresh EC2 instance because of this error. Below is my error log in case it helps.

Ghost-CLI: 1.0.3
Ubuntu 16.04.2 LTS
Mysql-server:  5.7.19-0ubuntu0.16.04.1

<details>
<summary>Error Log</summary>
<pre>
/var/www/ghost/current$ /usr/lib/node_modules/ghost-cli/node_modules/.bin/knex-migrator-migrate --init --mgpath /var/www/ghost/current
[2017-08-04 15:08:48] ERROR

NAME: InternalServerError
CODE: ER_NOT_SUPPORTED_AUTH_MODE
MESSAGE: The server has encountered an error.

level:normal

InternalServerError: The server has encountered an error.
    at new KnexMigrateError (/var/www/ghost/versions/1.5.0/node_modules/knex-migrator/lib/errors.js:7:26)
    at /var/www/ghost/versions/1.5.0/node_modules/knex-migrator/lib/database.js:58:19
    at tryCatcher (/var/www/ghost/versions/1.5.0/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/www/ghost/versions/1.5.0/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/var/www/ghost/versions/1.5.0/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/var/www/ghost/versions/1.5.0/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/www/ghost/versions/1.5.0/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/var/www/ghost/versions/1.5.0/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/var/www/ghost/versions/1.5.0/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/var/www/ghost/versions/1.5.0/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
    at Handshake.Sequence._packetToError (/var/www/ghost/versions/1.5.0/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Handshake.ErrorPacket (/var/www/ghost/versions/1.5.0/node_modules/mysql/lib/protocol/sequences/Handshake.js:103:18)
    at Protocol._parsePacket (/var/www/ghost/versions/1.5.0/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/var/www/ghost/versions/1.5.0/node_modules/mysql/lib/protocol/Parser.js:75:12)
    at Protocol.write (/var/www/ghost/versions/1.5.0/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/var/www/ghost/versions/1.5.0/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
    --------------------
    at Protocol._enqueue (/var/www/ghost/versions/1.5.0/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Protocol.handshake (/var/www/ghost/versions/1.5.0/node_modules/mysql/lib/protocol/Protocol.js:52:41)
    at Connection.connect (/var/www/ghost/versions/1.5.0/node_modules/mysql/lib/Connection.js:130:18)
    at /var/www/ghost/versions/1.5.0/node_modules/knex/lib/dialects/mysql/index.js:106:18
    at Promise._execute (/var/www/ghost/versions/1.5.0/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/var/www/ghost/versions/1.5.0/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/var/www/ghost/versions/1.5.0/node_modules/bluebird/js/release/promise.js:79:10)
    at Client_MySQL.acquireRawConnection (/var/www/ghost/versions/1.5.0/node_modules/knex/lib/dialects/mysql/index.js:104:12)
    at Object.create (/var/www/ghost/versions/1.5.0/node_modules/knex/lib/client.js:239:16)
    at Pool._createResource (/var/www/ghost/versions/1.5.0/node_modules/generic-pool/lib/generic-pool.js:354:17)
    at Pool._ensureMinimum (/var/www/ghost/versions/1.5.0/node_modules/generic-pool/lib/generic-pool.js:408:12)
    at new Pool (/var/www/ghost/versions/1.5.0/node_modules/generic-pool/lib/generic-pool.js:157:8)
    at Client_MySQL.initializePool (/var/www/ghost/versions/1.5.0/node_modules/knex/lib/client.js:269:17)
    at Client_MySQL.Client (/var/www/ghost/versions/1.5.0/node_modules/knex/lib/client.js:116:12)
    at new Client_MySQL (/var/www/ghost/versions/1.5.0/node_modules/knex/lib/dialects/mysql/index.js:62:20)
    at Knex (/var/www/ghost/versions/1.5.0/node_modules/knex/lib/index.js:60:34)
    at Object.connect (/var/www/ghost/versions/1.5.0/node_modules/knex-migrator/lib/database.js:24:12)
    at Object.createDatabaseIfNotExist (/var/www/ghost/versions/1.5.0/node_modules/knex-migrator/lib/database.js:41:30)
    at KnexMigrator.init (/var/www/ghost/versions/1.5.0/node_modules/knex-migrator/lib/index.js:73:21)
    at KnexMigrator.migrate (/var/www/ghost/versions/1.5.0/node_modules/knex-migrator/lib/index.js:160:21)
    at /usr/lib/node_modules/ghost-cli/node_modules/knex-migrator/bin/knex-migrator-migrate:26:29
    at tryCatcher (/usr/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/util.js:16:23)
</pre>
</details>

**Comment by acburdine** [comment]
@the4dpatrick the workaround at the moment is to create the specific user yourself, and then use _that_ user for your mysql config rather than root. If the user is _not_ root, Ghost won't attempt to create a user itself.

FWIW though, definitely aiming to fix this in the next version.

**Comment by the4dpatrick** [comment]
Thanks for the response. I actually got it to work by running the follow:

Open terminal and login:

```
mysql -u root -p
```
(you can access with other users as well)

After that::
```
use mysql;
update user set authentication_string=password(''), plugin='mysql_native_password' where user='root';
```

And the very last important thing is to reset mysql service:
```
sudo service mysql restart
```

---

This suffices for me for now, but it is good to know that this will be fixed in the next version.

**Comment by acburdine** [comment]
ok so we now have a way to do this in-query, which I will release in the next CLI version:

```mysql
CREATE USER 'user'@'host' IDENTIFIED WITH mysql_native_password;
SET old_passwords = 0;
SET PASSWORD for 'user'@'ghost' = PASSWORD('password');
```

relevant mysql docs: https://dev.mysql.com/doc/refman/5.6/en/create-user.html
