### ISSUE TITLE
Admin broken after upgrading from 1.1.0 to 1.4.0 (cli v 1.0.3)

### ISSUE THREAD

**Issue by theDustRoom** [TryGhost/Ghost-CLI#425]
### This issue is a

* [x] Bug Report

### Summary

If this is a bug, double-check and make sure there's not already an existing issue for it, then provide a quick summary of what error is occurring.

If this is a feature request, use this section to describe what feature you would like to see in the CLI, as well as a quick summary of any benefits or drawbacks you can think of if this feature is implemented.

### Steps to Reproduce (for a bug report)

I've done this on three separate ghost blogs, all 1.1.0 updating to 1.4.0.

1. Update from Ghost 1.1.0 to 1.4.0 using Ghost-CLI 1.0.3.
2. Navigate to blog.url/ghost

Error:

Error: No default engine was specified and no extension was provided.
    at new View (/var/appdata/ghost/ape/versions/1.4.0/node_modules/express/lib/view.js:62:11)
    at EventEmitter.render (/var/appdata/ghost/ape/versions/1.4.0/node_modules/express/lib/application.js:570:12)
    at ServerResponse.render (/var/appdata/ghost/ape/versions/1.4.0/node_modules/express/lib/response.js:971:7)
    at HTMLErrorRender (/var/appdata/ghost/ape/versions/1.4.0/core/server/middleware/error-handler.js:86:9)
    at Layer.handle_error (/var/appdata/ghost/ape/versions/1.4.0/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/var/appdata/ghost/ape/versions/1.4.0/node_modules/express/lib/router/index.js:315:13)
    at /var/appdata/ghost/ape/versions/1.4.0/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/appdata/ghost/ape/versions/1.4.0/node_modules/express/lib/router/index.js:335:12)
    at next (/var/appdata/ghost/ape/versions/1.4.0/node_modules/express/lib/router/index.js:275:10)
    at prepareError (/var/appdata/ghost/ape/versions/1.4.0/core/server/middleware/error-handler.js:58:5)
    at Layer.handle_error (/var/appdata/ghost/ape/versions/1.4.0/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/var/appdata/ghost/ape/versions/1.4.0/node_modules/express/lib/router/index.js:315:13)
    at /var/appdata/ghost/ape/versions/1.4.0/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/appdata/ghost/ape/versions/1.4.0/node_modules/express/lib/router/index.js:335:12)
    at next (/var/appdata/ghost/ape/versions/1.4.0/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/var/appdata/ghost/ape/versions/1.4.0/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/var/appdata/ghost/ape/versions/1.4.0/node_modules/express/lib/router/index.js:315:13)
    at /var/appdata/ghost/ape/versions/1.4.0/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/appdata/ghost/ape/versions/1.4.0/node_modules/express/lib/router/index.js:335:12)
    at next (/var/appdata/ghost/ape/versions/1.4.0/node_modules/express/lib/router/index.js:275:10)
    at /var/appdata/ghost/ape/versions/1.4.0/node_modules/express/lib/response.js:424:7
    at SendStream.onerror (/var/appdata/ghost/ape/versions/1.4.0/node_modules/express/lib/response.js:1003:5)

### Technical details (will be automatically output by Ghost-CLI if an error occurs):

* Node Version: 6.11.0
* Ghost-CLI Version: 1.0.3

**Comment by kirrg001** [comment]
Hey 👋 

Thanks for your report and sorry you are having trouble.

This is a known issue and it was reported [here](https://github.com/TryGhost/Ghost/issues/8829). It was already fixed in Ghost master and we are going to release a new version in the afternoon.

A workaround was posted [here](https://github.com/TryGhost/Ghost/issues/8829#issuecomment-319807736).

Closing.

**Comment by ErisDS** [comment]
Note: this issue only occurs to blogs running in development mode
