### ISSUE TITLE
`ghost install` not migrating DB 

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost-CLI#450]
## This issue is a

* [x] Bug Report
* [ ] Feature Request

A couple of times I've seen users report that running `ghost install` leaves them without a DB. 

### Steps to Reproduce (for a bug report)

1. `ghost install`

I'm not sure of the surrounding factors yet. One customer reported this after the SSL step failed due to their domain not being configured yet. Not sure if that could cause the DB step to fail as well?

Also, if the DB isn't setup properly, people end up in a pathway that pretends to help them but doesn't really:

> When I do `ghost run` I get an error: DatabaseIsNotOkError. Please run knex-migrator init. 
> When I run knex-migrator init I get InternalServerError. Please provide a file named MigratorConfig.js in your project root. 
> I can see that there is a MigratorConfig.js inside my /var/www/ghost/current/ path.

I see a couple of action points:

1. If any ghost command runs into knex migrator errors, these can be caught and rethrown as "please run `ghost setup migrate`"
2. If `ghost setup ssl` gets a verify error we could 
   a. rethrow this as a clear error about domain setup & prompt to run `ghost setup ssl` when ready
   b. fall back and make sure the site will run as non-ssl

### Technical details (will be automatically output by Ghost-CLI if an error occurs):

* OS:  Ubuntu 16 on vultr 
* Node Version: 6.11.2
* Ghost-CLI Version: 1.1.0
* Environment:  production
* Command: `ghost install`

**Comment by acburdine** [comment]
So the reason this is occurring is because if the SSL setup fails, it exits the setup process.

There are two different solutions that I think we could do to fix this.

1) Make any issues with SSL _not_ exit - this is related to #190 as improved pre-ssl generation checks will cause SSL to skip generation and warn with a "run 'ghost setup ssl' once you've fixed your domain"
2) Recommend that people re-run `ghost setup` after fixing the ssl errors.

No. 2 is probably the best short-term fix until #190 is implemented - each individual setup step is robust enough that running `ghost setup` after a failure in the ssl setup stage should be fine in terms of idempotency. No. 1 is definitely the ideal though.

**Comment by acburdine** [comment]
After a conversation with another user yesterday, it looks like the migration issue is related to permissions - e.g. if your directory permissions aren't setup correctly you can run into the "no MigratorConfig.js file exists" issue.

**Comment by davidfurlong** [comment]
I used the digital ocean one click install (https://www.digitalocean.com/community/tutorials/how-to-set-up-the-digitalocean-ghost-one-click-application-for-ubuntu-16-04), and got this error on step 4: 

```
root@deedmob-blog:/var/www/ghost# ghost update
✔ Checking for latest Ghost version
✔ Downloading and updating Ghost to v1.18.3
Running sudo command: systemctl stop ghost_146-185-175-92
✔ Stopping Ghost
✔ Linking latest Ghost and recording versions
Running sudo command: /usr/lib/node_modules/ghost-cli/node_modules/.bin/knex-migrator-migrate --init --mgpath /var/www/ghost/current
✖ Running database migrations
An error occurred.
Message: 'Command failed: /bin/sh -c sudo -S -p '#node-sudo-passwd#' -E -u ghost /usr/lib/node_modules/ghost-cli/node_modules/.bin/knex-migrator-migrate --init --mgpath /var/www/ghost/current
[2017-12-07 09:19:57] ERROR

NAME: MigrationScript
MESSAGE: task.execute is not a function

level:normal

Error occurred while executing the following migration: 1-custom-template-post.js
MigrationScript: task.execute is not a function
    at MigrationScript.KnexMigrateError (/usr/lib/node_modules/ghost-cli/node_modules/knex-migrator/lib/errors.js:9:26)
    at new MigrationScript (/usr/lib/node_modules/ghost-cli/node_modules/knex-migrator/lib/errors.js:28:26)
    at /usr/lib/node_modules/ghost-cli/node_modules/knex-migrator/lib/index.js:355:19
    at tryCatcher (/usr/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/usr/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

TypeError: task.execute is not a function
    at /usr/lib/node_modules/ghost-cli/node_modules/knex-migrator/lib/index.js:310:25
    at tryCatcher (/usr/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/usr/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)



'


Debug Information:
    Node Version: v6.11.5
    Ghost-CLI Version: 1.2.0
    Environment: production
    Command: 'ghost update'
```

**Comment by kirrg001** [comment]
@davidfurlong 
See https://docs.ghost.org/docs/troubleshooting#section-task-execute-is-not-a-function.

**Comment by davidfurlong** [comment]
@kirrg001 Thanks, I tried doing that. So I can't update? I am using the vanilla digital ocean one click install droplet so I expect most people setting up to have this issue?

**Comment by kirrg001** [comment]
@davidfurlong You can update your blog if you upgrade your CLI version to >= 1.3.0 (or simply latest).

**Comment by kirrg001** [comment]
@davidfurlong Cool that it worked. Can you please notify the docker image contributor?

**Comment by lmuzquiz** [comment]
Im getting the exact same error as @davidfurlong , bum i am not trying to update. Im doing a fresh new ghost install on a fresh new folder.

**Comment by gdude2002** [comment]
I've been getting this error on my `local` install on an Arch machine; trying to update from Ghost 1.13.0 to Ghost 1.23.0. I followed the steps at [this page](https://docs.ghost.org/docs/troubleshooting#section-task-execute-is-not-a-function) by moving my data from the ghost user (I wasn't using root) to my own user, as described.

I was using ghost-cli 1.7.3 and Node 6.9.5, via nvm. 

I ended up fixing this problem by running `npm i ghost ghost-cli` within my instance directory. Everything works, but I noticed that the port that Ghost was running on was incremented, so I had to fix my nginx config for that as well.

Just wanted to leave this here in case anyone else had the same issue.

**Comment by preparationh67** [comment]
Ran into this issue today and it seemed to be caused by ghost making incorrect assumptions if you already created a blank database on a remote DB host for ghost to use before setup. The only solution I could find was giving ghost the root DB user and password, having it create a new database with the root credentials, and then having it create the ghost user. A separate issue is we should be able to tell the setup script the name of the ghost mysql user account to create.

**Comment by kirrg001** [comment]
> If any ghost command runs into knex migrator errors, these can be caught and rethrown as "please run ghost setup migrate"

👍 Yeah, we have  to enhance the error log output & suggested commands in case Ghost returns an error back from knex-migrator, because knex-migrator has it's own suggestions.

See another example: https://forum.ghost.org/t/issue-with-migration/6012

**Comment by hhsadiq** [comment]
thanks @preparationh67 switching to root db user, and re-installing ghost from scratch solved the issue, otherwise i have spent half day solving this issue and could not find anything helpful. And agree with @kirrg001 regarding suggested commands and error log output.

**Comment by MaluNoPeleke** [comment]
I have now a similar problem with migration from 2.22 to 2.23.2 and knex-migrator 3.3 on node.js v10:

lib/node_modules/knex-migrator/bin/knex-migrator-migra
te:9
utils.getKnexMigrator({path: process.cwd()})
      ^

TypeError: utils.getKnexMigrator is not a function
    at Object.<anonymous> (/home/peleke7/lib/node_modules/knex-migra
tor/bin/knex-migrator-migrate:9:7)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js
:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:1
2)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
