### ISSUE TITLE
Corrupt `.ghost-cli` file

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost-CLI#551]
## Summary

```
TypeError: Invalid Version: undefined
    at new SemVer (/usr/local/lib/node_modules/ghost-cli/node_modules/semver/semver.js:279:11)
    at compare (/usr/local/lib/node_modules/ghost-cli/node_modules/semver/semver.js:566:10)
    at Function.lt (/usr/local/lib/node_modules/ghost-cli/node_modules/semver/semver.js:600:10)
    at UpdateCommand.run (/usr/local/lib/node_modules/ghost-cli/lib/commands/update.js:20:20)
    at Function._run (/usr/local/lib/node_modules/ghost-cli/lib/command.js:198:48)
    at Object.handler (/usr/local/lib/node_modules/ghost-cli/lib/command.js:117:22)
    at Object.runCommand (/usr/local/lib/node_modules/ghost-cli/node_modules/yargs/lib/command.js:228:22)
    at Object.parseArgs [as _parseArgs] (/usr/local/lib/node_modules/ghost-cli/node_modules/yargs/yargs.js:1013:30)
    at Object.parse (/usr/local/lib/node_modules/ghost-cli/node_modules/yargs/yargs.js:542:25)
    at Object.run (/usr/local/lib/node_modules/ghost-cli/lib/bootstrap.js:165:14)
    at startup (/usr/local/lib/node_modules/ghost-cli/bin/ghost:10:15)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

The existing `.ghost-cli` file only contained this:

```
{
  name: 'blog-name'
}
```

Both the cli version and the ghost version were not part of this file, which is required for [this line](https://github.com/TryGhost/Ghost-CLI/blob/master/lib/commands/update.js#L20).

Currently we have no idea why the `.ghost-cli` file missed specific keys.

It might be useful to auto fix broken/corrupt `.ghost-cli` files, but we first should try to figure out why this can happen.

## Technical details

Ghost-CLI Version: 1.3.0
Environment: production
Command: 'ghost update'

**Comment by vikaspotluri123** [comment]
I don't have time to work on this right now, but I do have a couple of thoughts
 - The ghost version can be determined by reading `current/package.json`
 - I don't see a good way to determine the CLI version that was installed. Given this, it might be best to fall back to `1.3.0` so all migrations can run if necessary - either they have already run so they won't need to run again, or they haven't run and 1.3.0 is the first time the concept of a migration was introduced
