### ISSUE TITLE
Failed to connect to bus: No such file or directory

### ISSUE THREAD

**Issue by kasbah** [TryGhost/Ghost-CLI#557]
### This issue is a

* [x] Bug Report
* [ ] Feature Request

### Steps to Reproduce

1. Install ghost-cli on a fresh Ubuntu 16.04
2. Run `ghost install`, watch it fail at the end when starting with:

```
An error occurred.
Message: 'Failed to connect to bus: No such file or directory'
```
try `ghost start`
```
Error: Failed to connect to bus: No such file or directory

    at module.exports.sync (/home/kaspar/.nvm/versions/node/v6.12.0/lib/node_modules/ghost-cli/node_modules/execa/index.js:303:26)
    at handleShell (/home/kaspar/.nvm/versions/node/v6.12.0/lib/node_modules/ghost-cli/node_modules/execa/index.js:105:9)
    at Function.module.exports.shellSync (/home/kaspar/.nvm/versions/node/v6.12.0/lib/node_modules/ghost-cli/node_modules/execa/index.js:312:43)
    at SystemdProcessManager.isRunning (/home/kaspar/.nvm/versions/node/v6.12.0/lib/node_modules/ghost-cli/extensions/systemd/systemd.js:61:19)
    at Instance.running (/home/kaspar/.nvm/versions/node/v6.12.0/lib/node_modules/ghost-cli/lib/instance.js:119:27)
    at StartCommand.run (/home/kaspar/.nvm/versions/node/v6.12.0/lib/node_modules/ghost-cli/lib/commands/start.js:28:22)
    at Function._run (/home/kaspar/.nvm/versions/node/v6.12.0/lib/node_modules/ghost-cli/lib/command.js:198:48)
    at Object.handler (/home/kaspar/.nvm/versions/node/v6.12.0/lib/node_modules/ghost-cli/lib/command.js:117:22)
    at Object.runCommand (/home/kaspar/.nvm/versions/node/v6.12.0/lib/node_modules/ghost-cli/node_modules/yargs/lib/command.js:228:22)
    at Object.parseArgs [as _parseArgs] (/home/kaspar/.nvm/versions/node/v6.12.0/lib/node_modules/ghost-cli/node_modules/yargs/yargs.js:1013:30)
    at Object.parse (/home/kaspar/.nvm/versions/node/v6.12.0/lib/node_modules/ghost-cli/node_modules/yargs/yargs.js:542:25)
    at Object.run (/home/kaspar/.nvm/versions/node/v6.12.0/lib/node_modules/ghost-cli/lib/bootstrap.js:165:14)
    at startup (/home/kaspar/.nvm/versions/node/v6.12.0/lib/node_modules/ghost-cli/bin/ghost:10:15)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

### Technical details (will be automatically output by Ghost-CLI if an error occurs):

* OS: Ubuntu 16.04
* Node Version: v6.12.0
* Ghost-CLI Version: 1.4.0
* Environment: production

EDIT: Aha! Looks like dbus wasn't installed. It would be nice if Ghost-CLI checked for this I guess?

**Comment by kirrg001** [comment]
Hey!

`dbus` is [preinstalled on Ubuntu 16.04](https://packages.ubuntu.com/xenial/allpackages).

Closing - we can re-open if it turns out documentation is missing.

**Comment by kasbah** [comment]
hi @kirrg001! Are you sure it is? The list you linked seems to list software that is available rather than preinstalled (e.g. 0ad, the game). I am almost certain it _is_ installed by default on the desktop images but not sure about server images. 

Unfortunately I can't really recall which of my servers I was testing on, it may have been an odd config, but wouldn't it make sense to add a basic check for all required packages on all Debian based systems anyway?
