### ISSUE TITLE
Stack Fail after update

### ISSUE THREAD

**Issue by ChaosCA** [TryGhost/Ghost-CLI#571]
### This issue is a

* [ x] Bug Report
* [ ] Feature Request

### Summary

After running a ghost update, it failed due to migrations it couldn't run in the pre 1.1.13 CLI. So I updated the CLI and tried to run the update again. However now ghost will not start. Attempts to `ghost update --force` and `ghost update --rollback` result in a Stack Fail.

```
Debug Information:
    Node Version: v6.12.2
    Ghost-CLI Version: 1.4.1
    Environment: production
    Command: 'ghost update --rollback'
An error occurred.
Message: 'failed
'

Stack: Error: failed

    at module.exports.sync (/usr/lib/node_modules/ghost-cli/node_modules/execa/index.js:303:26)
    at handleShell (/usr/lib/node_modules/ghost-cli/node_modules/execa/index.js:105:9)
    at Function.module.exports.shellSync (/usr/lib/node_modules/ghost-cli/node_modules/execa/index.js:312:43)
    at SystemdProcessManager.isRunning (/usr/lib/node_modules/ghost-cli/extensions/systemd/systemd.js:61:19)
    at Instance.running (/usr/lib/node_modules/ghost-cli/lib/instance.js:119:27)
    at UpdateCommand.run (/usr/lib/node_modules/ghost-cli/lib/commands/update.js:48:22)
    at precheck.then (/usr/lib/node_modules/ghost-cli/lib/command.js:206:52)
    at tryCatcher (/usr/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/usr/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/usr/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:454:14)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/usr/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:569:18)
```

### Technical details (will be automatically output by Ghost-CLI if an error occurs):

* OS: Debian 8
* Node Version: 6.12.2
* Ghost-CLI Version: 1.4.1
* Environment: production
 * Command: 'ghost update --rollback'

**Comment by ChaosCA** [comment]
Also note when trying to run with `ghost run`. I'm not sure how to get knex-migrator to run.

``
The `ghost run` command is used by the configured Ghost process manager and for debugging. If you're not running this to debug something, you should run `ghost start` instead.
Running sudo command: node current/index.js
[2017-12-15 19:41:11] ERROR

NAME: DatabaseIsNotOkError
CODE: DB_NEEDS_MIGRATION
MESSAGE: Migrations are missing. Please run knex-migrator migrate.

level:normal

If knex-migrator is not installed, please run "npm install -g knex-migrator"
Read more here: https://github.com/TryGhost/knex-migrator
DatabaseIsNotOkError: Migrations are missing. Please run knex-migrator migrate.
    at DatabaseIsNotOkError.KnexMigrateError (/var/www/ghost/versions/1.19.0/node_modules/knex-migrator/lib/errors.js:9:26)
    at new DatabaseIsNotOkError (/var/www/ghost/versions/1.19.0/node_modules/knex-migrator/lib/errors.js:21:26)
    at /var/www/ghost/versions/1.19.0/node_modules/knex-migrator/lib/index.js:1067:27
    at /var/www/ghost/versions/1.19.0/node_modules/lodash/lodash.js:4944:15
    at baseForOwn (/var/www/ghost/versions/1.19.0/node_modules/lodash/lodash.js:3001:24)
    at /var/www/ghost/versions/1.19.0/node_modules/lodash/lodash.js:4913:18
    at Function.forEach (/var/www/ghost/versions/1.19.0/node_modules/lodash/lodash.js:9359:14)
    at /var/www/ghost/versions/1.19.0/node_modules/knex-migrator/lib/index.js:1064:15
    at tryCatcher (/var/www/ghost/versions/1.19.0/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/www/ghost/versions/1.19.0/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/var/www/ghost/versions/1.19.0/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/var/www/ghost/versions/1.19.0/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/www/ghost/versions/1.19.0/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/var/www/ghost/versions/1.19.0/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/var/www/ghost/versions/1.19.0/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/var/www/ghost/versions/1.19.0/node_modules/bluebird/js/release/promise.js:524:17)
```

`ghost migrate` shows:
✔ Checking for available migrations
No migrations needed :)

**Comment by vikaspotluri123** [comment]
Hey @ChaosCA 👋 Can you reach out to us on [slack](slack.ghost.org)? This looks like a generic user issue, rather than a bug 😄 

Sidenote: `ghost migrate` runs CLI migrations, while `ghost setup migrate` runs database migrations

**Comment by ChaosCA** [comment]
@vikaspotluri123 I figured I'd post it here since its a failure when updating, but okay I'll try there.
Would you suggest running ghost setup migrate?
