### ISSUE TITLE
Ghost CLI generic error when running `ghost start` but `ghost run` works just fine.

### ISSUE THREAD

**Issue by cmivxx** [TryGhost/Ghost-CLI#599]
Popped into slack and noone was around, so I'm here.

Had 3 Ghost instances running just fine for quite a while without any problems.  Regularly did the updates, etc.  Today I went to move the DB to a new server as I am going to decommission the old one.  Old server is MySQL, new server is MariaDB, but they should work without issue.  Move all 3 databases, updated all 3 `config.production.json` files without issue and started restarting them.  2 of the 3 restarted just fine.  The third one, said it started in the `ghost status` call, but was throwing a `502 Bad Gateway` error, and the `node` service on the server started swallowing CPU cycles.  Pegged at 93% CPU.  Subsequent ghost-cli calls throw a generic error:

```
cmiller@ghosthost:/www/chrisrmiller.com/wwwroot$ ghost status
An error occurred.
Message: 'failed
'


Debug Information:
    Node Version: v6.12.3
    Ghost-CLI Version: 1.4.2
    Environment: production
    Command: 'ghost status'

Additional log info available in: /home/cmiller/.ghost/logs/ghost-cli-debug-2018-01-26T01_52_17_254Z.log

Please refer to https://docs.ghost.org/v1/docs/troubleshooting#section-cli-errors for troubleshooting.
```
Content of debug log from bottom of last message:
```
cmiller@ghosthost:/www/chrisrmiller.com/wwwroot$ cat /home/cmiller/.ghost/logs/ghost-cli-debug-2018-01-26T01_52_17_254Z.log
Debug Information:
   Node Version: v6.12.3
   Ghost-CLI Version: 1.4.2
   Environment: production
   Command: 'ghost status'
An error occurred.
Message: 'failed
'

Stack: Error: failed

   at module.exports.sync (/usr/lib/node_modules/ghost-cli/node_modules/execa/index.js:303:26)
   at handleShell (/usr/lib/node_modules/ghost-cli/node_modules/execa/index.js:105:9)
   at Function.module.exports.shellSync (/usr/lib/node_modules/ghost-cli/node_modules/execa/index.js:312:43)
   at SystemdProcessManager.isRunning (/usr/lib/node_modules/ghost-cli/extensions/systemd/systemd.js:61:19)
   at Instance.running (/usr/lib/node_modules/ghost-cli/lib/instance.js:119:27)
   at Instance.summary (/usr/lib/node_modules/ghost-cli/lib/instance.js:177:19)
   at instances.map (/usr/lib/node_modules/ghost-cli/lib/commands/ls.js:10:38)
   at Array.map (native)
   at LsCommand.run (/usr/lib/node_modules/ghost-cli/lib/commands/ls.js:9:32)
   at precheck.then (/usr/lib/node_modules/ghost-cli/lib/command.js:206:52)
   at process._tickCallback (internal/process/next_tick.js:109:7)
   at Module.runMain (module.js:606:11)
   at run (bootstrap_node.js:383:7)
   at startup (bootstrap_node.js:149:9)
   at bootstrap_node.js:496:3
```
If I run `ghost run`, it starts just fine.  I even rolled the config file back to pointing at the old DB server (which WAS working) and it does the same thing.  I restarted the server, and it does the same thing.  I'm quite lost.

Here's my config.production.json file:
```
{
  "url": "https://chrisrmiller.com",
  "server": {
    "port": 2369,
    "host": "127.0.0.1"
  },
  "database": {
    "client": "mysql",
    "connection": {
      "host": "db01.server.com",
      "user": "aaaabbbbcccc",
      "password": "xxxxyyyyyzzzzz",
      "database": "ghost_chrisrmiller-com"
    }
  },
  "mail": {
    "transport": "Direct"
  },
  "logging": {
      "path": "logs/",
      "level": "info",
      "rotation": {
	  "enabled": true,
	  "count": 15,
	  "period": "1d"
      },
      "transports": ["file","stdout"]
  },
  "process": "systemd",
  "paths": {
    "contentPath": "/www/chrisrmiller.com/wwwroot/content"
  },
    "caching": {
	"frontend": {
	    "maxAge": 0
	},
	"301": {
	    "maxAge": 31536000
	},
	"customRedirects": {
	    "maxAge": 31536000
	},
	"favicon": {
	    "maxAge": 86400
	},
	"sitemap": {
	    "maxAge": 3600
	},
	"robotstxt": {
	    "maxAge": 3600000
	}
    }
}
```

* OS: Debisn 8
* Node Version: v6.12.3
* Ghost-CLI Version: 1.4.2

Please help Obi-wan, you are my only hope.

**Comment by cmivxx** [comment]
Dupe of:  https://github.com/TryGhost/Ghost-CLI/issues/575
