### ISSUE TITLE
Startup error after upgrading to 1.21.1 

### ISSUE THREAD

**Issue by thedotedge** [TryGhost/Ghost-CLI#639]
### Issue Summary

Ghost fails to start after upgrade.

### Steps to Reproduce
```
ghost start
✔ Checking current folder permissions
✔ Validating config
✔ Checking folder permissions
✔ Checking file permissions
Running sudo command: systemctl start ghost_freelancehunt-com
? Password [hidden]
Running sudo command: systemctl stop ghost_freelancehunt-com
✖ Starting Ghost
A GhostError occurred.

Message: Ghost did not start.
Suggestion: journalctl -u ghost_freelancehunt-com -n 50

Debug Information:
    OS: linux, v4.14.12-x86_64-linode92
    Node Version: v6.12.2
    Ghost-CLI Version: 1.5.1
    Environment: production
    Command: 'ghost start'

Additional log info available in: /home/ghost/.ghost/logs/ghost-cli-debug-2018-02-10T12_10_33_156Z.log

Try running ghost doctor to check your system for known issues.
```

```
journalctl -u ghost_freelancehunt-com -n 50
No journal files were found.
-- No entries --
```

```
cat  /home/ghost/.ghost/logs/ghost-cli-debug-2018-02-10T12_10_33_156Z.log
Debug Information:
    OS: linux, v4.14.12-x86_64-linode92
    Node Version: v6.12.2
    Ghost-CLI Version: 1.5.1
    Environment: production
    Command: 'ghost start'
Message: Ghost did not start.
Suggestion: journalctl -u ghost_freelancehunt-com -n 50
Stack: Error: Ghost did not start.
    at connectToGhostSocket.then.catch (/usr/lib/node_modules/ghost-cli/lib/utils/port-polling.js:92:32)
    at process._tickCallback (internal/process/next_tick.js:109:7)

Original Error Message:
Message: connect ECONNREFUSED 127.0.0.1:2369
Stack: Error: connect ECONNREFUSED 127.0.0.1:2369
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
```
No config changes has been done before the upgrade and it contains different IP for ghost:
```
"server": {
    "port": 2369,
    "host": "192.168.157.188"
  },
``

No other service is listening on port 2369 and ghost is not running. Running `ghost run` works fine.

### Technical details:

* Ghost Version: 1.21.1
* Ghost-CLI version: 1.5.1
* Node Version: v6.12.2
* Browser/OS: CentOS 7

**Comment by acburdine** [comment]
@thedotedge what OS are you running Ghost-CLI on? Looks like the CLI couldn’t determine it in the error message.

**Comment by thedotedge** [comment]
It's CentOS 7.4. Ghost on this instance has been updated many time without problems until now.

**Comment by thedotedge** [comment]
`ghost run` works just fine.

**Comment by kirrg001** [comment]
Maybe this is also a timing issue? 🤔 

We already increased the timeout in https://github.com/TryGhost/Ghost-CLI/commit/88043722b223b8fd1c9cb82bf55a484ba68d637b.

@acburdine Should we release another patch with this fix?

**Comment by acburdine** [comment]
Just release ghost-cli 1.5.2 with the increased port timeout.

@thedotedge would you mind updating to the latest version of the CLI and seeing if it fixes the issue?

**Comment by welchwsy** [comment]
the same of this problem
```bash
Ghost-CLI version: 1.5.2
Ghost Version (at /var/www/ghost): 1.21.5
```
```
ubuntu 16.04
node 6.13.1
```

**Comment by kirrg001** [comment]
@welchwsy Does it timeout all the time or just sometimes?
Also, can you pls provide a little more information e.g. which server/droplet.

**Comment by welchwsy** [comment]
@kirrg001 fix this problem, It's my fault.
install ghost-cli by root, then install ghost-cli by ghost user. the file `/lib/systemd/system/ghost_localhost.service` set `user=999`.
try 
```
sudo rm /lib/systemd/system/ghost_localhost.service
ghost setup systemd
systemctl daemon-reload
```

**Comment by aurabindo** [comment]
Hi, I'm facing this issue, when I tried installing ghost. When I do 'ghost run'. I get the error message:
```
NAME: DatabaseIsNotOkError
CODE: DB_NEEDS_MIGRATION
MESSAGE: Migrations are missing. Please run `knex-migrator migrate`.
```
Should I install knex-migrator myself and run the suggested command? or will it mess up further ?
