### ISSUE TITLE
Ghost-CLI don't create "ghost" system user, ghost install via the CLI failed

### ISSUE THREAD

**Issue by gh0-0st** [TryGhost/Ghost-CLI#676]
## This issue is a

* [X] Bug Report
* [ ] Feature Request

### Summary

According to the [documentation](https://docs.ghost.org/v1/docs/install) it's indicated:

> Create a New User
> 
> When you first log into your new server it is highly recommended to create a new user with regular account privileges and do some basic system setup.
> 
> Please don't call this user ghost, Ghost-CLI will create the ghost user for managing your blog. The user you are creating is for administrating your server

So i create a user named "ghostuser" (_different than 'ghost'_) and I followed the installation procedure (there was another bug identified and while waiting for it to be fixed there is a way to bypass).

When arrive time to install ghost, i try to install via the CLI, that's failed at the end with this error message:

```
✖ Setting up "ghost" system user                                                                             
An error occurred.                                                                                           
Message: 'Command failed: /bin/sh -c id ghost
id: « ghost » : user unknown
```

### Steps to Reproduce (for a bug report)

1. Create a New User and Super User Privileges
```
adduser ghostuser
cat /etc/passwd
ghostuser:x:1002:1002:Ghost User,,,:/home/ghostuser:/bin/bash
usermod -aG sudo ghostuser
```

3. Installation NodeJS v8.10.0 and NPM
4. Check NodeJS and NPM versions
5. Installation Ghost-CLI v1.5.2 (for now the lasted)

6. Install Ghost via the CLI
```
sudo mkdir -p /var/www/ghost
sudo chown ghostuser:ghostuser /var/www/ghost
sudo chmod 775 /var/www/ghost
cd /var/www/ghost
```

```
ghostuser@host:/var/www/ghost$ ghost install
✔ Checking system Node.js version                                                                            
✔ Checking current folder permissions                                                                        
System checks failed with message: 'Linux version is not Ubuntu 16'                                          
Some features of Ghost-CLI may not work without additional configuration.
For local installs we recommend using `ghost install local` instead.
? Continue anyway? Yes                                                                                       
ℹ Checking operating system compatibility [skipped]                                                          
✔ Checking for a MySQL installation                                                                          
✔ Checking for latest Ghost version                                                                          
✔ Setting up install directory                                                                               
✔ Downloading and installing Ghost v1.21.5                                                                   
✔ Finishing install process                                                                                  
? Enter your blog URL: http://localhost:2368                                                                 
? Enter your MySQL hostname: localhost                                                                       
? Enter your MySQL username: ghostadmin                                                                        
? Enter your MySQL password: [hidden]                                                                        
? Enter your Ghost database name: ghost_prod                                                                 
✔ Configuring Ghost                                                                                          
✔ Setting up instance                                                                                        
✖ Setting up "ghost" system user                                                                             
An error occurred.                                                                                           
Message: 'Command failed: /bin/sh -c id ghost
id: « ghost » : user unknown

'
```

I think it's a bug because same error with `sudo ghost setup linux-user`:

```
ghostuser@host:/var/www/ghost$ ghost setup linux-user                                                             
✖ Setting up "ghost" system user                                                                             
An error occurred.                                                                                           
Message: 'Command failed: /bin/sh -c id ghost
id: « ghost » : user unknown

'

Debug Information:
    OS: Debian, v9.4
    Node Version: v8.10.0
    Ghost-CLI Version: 1.5.2
    Environment: production
    Command: 'ghost setup linux-user'
```

### Technical details (for a bug report)

This is automatically output by Ghost-CLI if an error occurs, please copy & paste:

```
Debug Information:
    OS: Debian, v9.4
    Node Version: v8.10.0
    Ghost-CLI Version: 1.5.2
    Environment: production
    Command: 'ghost install'
An error occurred.
Message: 'Command failed: /bin/sh -c id ghost
id: « ghost » : user unknown

'

Stack: Error: Command failed: /bin/sh -c id ghost
id: « ghost » : user unknown

    at makeError (/usr/lib/node_modules/ghost-cli/node_modules/execa/index.js:169:9)
    at module.exports.sync (/usr/lib/node_modules/ghost-cli/node_modules/execa/index.js:338:15)
    at handleShell (/usr/lib/node_modules/ghost-cli/node_modules/execa/index.js:116:9)
    at Function.module.exports.shellSync (/usr/lib/node_modules/ghost-cli/node_modules/execa/index.js:361:43)
    at SetupCommand.linuxSetupTask (/usr/lib/node_modules/ghost-cli/lib/tasks/linux.js:10:15)
    at Promise.resolve.then.then.skipped (/usr/lib/node_modules/ghost-cli/node_modules/listr/lib/task.js:168:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Code: 1
```

If I was creating the system user 'ghost' before starting the installation of ghost via the cli then it's ok, installation done:

```
root@host:~# useradd ghost
root@host:~# passwd ghost
root@host:/# su - ghostuser
ghostuser@host:~$ cd /var/www/ghost/
```

```
ghostuser@host:/var/www/ghost$ ghost install                                                                      
✔ Checking system Node.js version                                                                            
✔ Checking current folder permissions                                                                        
System checks failed with message: 'Linux version is not Ubuntu 16'                                          
Some features of Ghost-CLI may not work without additional configuration.
For local installs we recommend using `ghost install local` instead.
? Continue anyway? Yes                                                                                       
ℹ Checking operating system compatibility [skipped]                                                          
✔ Checking for a MySQL installation                                                                          
✔ Checking for latest Ghost version                                                                          
✔ Setting up install directory                                                                               
✔ Downloading and installing Ghost v1.21.5                                                                   
✔ Finishing install process                                                                                  
? Enter your blog URL: http://localhost:2368                                                                 
? Enter your MySQL hostname: localhost                                                                       
? Enter your MySQL username: ghostadmin                                                                    
? Enter your MySQL password: [hidden]                                                                        
? Enter your Ghost database name: ghost_prod                                                                 
✔ Configuring Ghost                                                                                          
✔ Setting up instance                                                                                        
Running sudo command: chown -R ghost:ghost /var/www/ghost/content                                            
? Password [hidden]                                                                                          
✔ Setting up "ghost" system user                                                                             
? Do you wish to set up "ghost" mysql user? Yes                                                              
MySQL user is not "root", skipping additional user setup                                                     
ℹ Setting up "ghost" mysql user [skipped]                                                                    
? Do you wish to set up Nginx? Yes                                                                           
Your url contains a port. Skipping Nginx setup.                                                              
ℹ Setting up Nginx [skipped]                                                                                 
Task ssl depends on the 'nginx' stage, which was skipped.                                                    
ℹ Setting up SSL [skipped]                                                                                   
? Do you wish to set up Systemd? Yes                                                                         
✔ Creating systemd service file at /var/www/ghost/system/files/ghost_localhost.service                       
Running sudo command: ln -sf /var/www/ghost/system/files/ghost_localhost.service /lib/systemd/system/ghost_localhost.service
Running sudo command: systemctl daemon-reload                                                                
✔ Setting up Systemd                                                                                         
Running sudo command: /var/www/ghost/current/node_modules/.bin/knex-migrator-migrate --init --mgpath /var/www/ghost/current
✔ Running database migrations                                                                                
? Do you want to start Ghost? Yes                                                                            
✔ Checking current folder permissions                                                                        
✔ Validating config                                                                                          
✔ Checking folder permissions                                                                                
✔ Checking file permissions                                                                                  
✔ Checking content folder ownership                                                                          
Running sudo command: systemctl start ghost_localhost                                                        
✔ Starting Ghost                                                                                             
Running sudo command: systemctl enable ghost_localhost --quiet
✔ Starting Ghost                                                                                             
You can access your blog at http://localhost:2368/
```

maybe I misunderstood the documentation.
I think I should be don't create a system user named 'ghost' because Ghost-CLI will create the ghost user for managing your blog.

If this is the case then there is a bug because Ghost-CLI does not create the ghost user.

**Comment by acburdine** [comment]
@gh0-0st what operating system are you on? The error handling is tailored to Ubuntu 16’s “no such user” error message, so if you’re on another OS it won’t detect the error message correctly.

**Comment by acburdine** [comment]
Nevermind, I just read the error log. While this is technically an unsupported OS, a fix should go out later this week for this.

**Comment by gh0-0st** [comment]
humm, you've got quicky reply before i finished my answer ;)
ok thank you so much if it's possible to fix this.

**Comment by danielmatusek** [comment]
Hi, I'm encountering exactly the same problem on Debian (8) Jessie. I can't successfully install ghost-cli. I would be glad if it would be possible to fix this :)

**Comment by gh0-0st** [comment]
@acburdine 

I retry with fresh install in Debian 9.4 and lasted version of Ghost-CLI but this issue is still there :/

```
ghostuser@host:/var/www/ghost$ ghost -v
Ghost-CLI version: 1.7.3
```
```

ghostuser@host:/var/www/ghost$ ghost install                                                                     
✔ Checking system Node.js version
✔ Checking logged in user
✔ Checking current folder permissions
System checks failed with message: 'Linux version is not Ubuntu 16'                                          
Some features of Ghost-CLI may not work without additional configuration.
For local installs we recommend using `ghost install local` instead.
? Continue anyway? Yes                                                                                       
ℹ Checking operating system compatibility [skipped]                                                          
✔ Checking for a MySQL installation
✔ Checking memory availability
✔ Checking for latest Ghost version                                                                          
✔ Setting up install directory
✔ Downloading and installing Ghost v1.22.7                                                                   
✔ Finishing install process
? Enter your blog URL: http://localhost:2368                                                                 
? Enter your MySQL hostname: localhost                                                                       
? Enter your MySQL username: ghostadmin                                                                        
? Enter your MySQL password: [hidden]                                                                        
? Enter your Ghost database name: ghost_prod                                                                       
✔ Configuring Ghost                                                                                          
✔ Setting up instance
✖ Setting up "ghost" system user
An error occurred.
Message: 'Command failed: /bin/sh -c id ghost
id: « ghost » : utilisateur inexistant

Debug Information:
    OS: Debian, v9.4
    Node Version: v8.11.1
    Ghost-CLI Version: 1.7.3
    Environment: production
    Command: 'ghost install'
```

**More infos:**
cat /home/ghostuser/.ghost/logs/ghost-cli-debug-2018-05-14T05_48_07_755Z.log

```
Debug Information:
    OS: Debian, v9.4
    Node Version: v8.11.1
    Ghost-CLI Version: 1.7.3
    Environment: production
    Command: 'ghost install'
An error occurred.
Message: 'Command failed: /bin/sh -c id ghost
id: « ghost » : utilisateur inexistant

Stack: Error: Command failed: /bin/sh -c id ghost
id: « ghost » : utilisateur inexistant

    at makeError (/usr/lib/node_modules/ghost-cli/node_modules/execa/index.js:172:9)
    at module.exports.sync (/usr/lib/node_modules/ghost-cli/node_modules/execa/index.js:341:15)
    at handleShell (/usr/lib/node_modules/ghost-cli/node_modules/execa/index.js:119:9)
    at Function.module.exports.shellSync (/usr/lib/node_modules/ghost-cli/node_modules/execa/index.js:364:43)
    at SetupCommand.linuxSetupTask (/usr/lib/node_modules/ghost-cli/lib/tasks/linux.js:10:15)
    at Promise.resolve.then.then.skipped (/usr/lib/node_modules/ghost-cli/node_modules/listr/lib/task.js:167:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Code: 1
```

Sorry but not fixed, if 'ghost' user isn't created before installation of ghost them error, seems Ghost-CLI can't create the account if it doesn't already exist.

**Comment by danielmatusek** [comment]
@acburdine sorry I haven't updated my post. Creating a 'ghost' account before installation as @gh0-0st mentioned did the trick for me.

**Comment by acburdine** [comment]
@gh0-0st Apologies, I was mistaken before. We did add something that fixed an issue _similar_ to the one you're running into, but the fix was in a different part of the codebase. 

The TL;DR of the issue is that Ghost-CLI tries to create the `ghost` user, and checks the response from the `id -u ghost` command to see if the user already exists. We check the error message and if it matches the known error message for 'no such user' we go ahead and create the user. However, because we're checking the error message strictly, if `id` outputs the same meaning but in a different format (or in your case, language) than it doesn't match and therefore fails. The fix we added in earlier was to remove the strict error message checking - it just didn't get applied to this part of the code.

I'll work on that fix asap since I know where it is now :)

**Comment by vikaspotluri123** [comment]
@gh0-0st it should be fixed in the next release - closing the issue in this case just means the master branch has been updated; a release is just a snapshot of the master branch

**Comment by gh0-0st** [comment]
@vikaspotluri123 thank you so much for your information, it's most understand.
Ok so i wait for the next version.

**Comment by gh0-0st** [comment]
@acburdine well done, thank you for your fix.

In Debian 9.4 (Stretch) with Ghost-CLI v1.8.0, the ghost install ok for now (ghost system user is successfully created):

...
✔ Configuring Ghost                                                                                          
✔ Setting up instance
_**Running sudo command: useradd --system --user-group ghost
Running sudo command: chown -R ghost:ghost /var/www/ghost/content**_                                            
✔ Setting up "ghost" system user

**Comment by adampatterson** [comment]
Is it possible to use the CLI to re-create the Ghost user? I migrated to a new server and I'm getting permission errors.

I created a ghost user and added it to the content folder, now I'm being asked to run `sudo find ./ ! -path "./versions/*" -type f -exec chmod 664 {} \;` which doesn't seem execute properly.
