### ISSUE TITLE
bug: errors using Ghost-CLI with npx

### ISSUE THREAD

**Issue by davemo** [TryGhost/Ghost-CLI#723]
`npx` is a pretty useful tool that was [made available](https://medium.com/@maybekatz/introducing-npx-an-npm-package-runner-55f7d4bd282b) in npm `5.2.0` but it currently can't be used in conjunction with the Ghost-CLI due to what appears to be an upstream issue in `find-plugins`, which is a dependency of Ghost-CLI.

For scaffolding or generator tools like `ghost install local`, it would be ideal to be able to use `npx` to avoid having to install a global module _or_ use a node version manager. 

From what I can tell this looks likely to have been introduced in d43efd7dc85c1865f1e1b028b045b3894f402c63 when `find-plugins` and `inquirer` were updated, but I don't have enough context to be sure:

```
commit d43efd7dc85c1865f1e1b028b045b3894f402c63
Author: Vikas Potluri <potlurivikas@gmail.com>
Date:   Mon Apr 30 00:05:15 2018 -0500

    chore(deps): update dependencies (including v4-locked)
    
    - find-plugins and inquirer were held back because of dropped v4
    support. Now that Ghost has dropped support for v4 they can be upgraded.
    
    - Dependencies that haven't been updated need to go through a manual
    review process (running CI / basic testing won't be enough)
    
    - Completely regenerated lockfile
```

Here's the command I was trying and the output log.

```shell
npx -p ghost-cli -p node@8 -- ghost install local
```
```shell
fs.js:904
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/Users/davemo/.npm/_npx/16586/lib/node_modules/node/lib/node_modules'
    at Object.fs.readdirSync (fs.js:904:18)
    at findCandidatesInDir (/Users/davemo/.npm/_npx/16586/lib/node_modules/ghost-cli/node_modules/find-plugins/index.js:97:13)
    at findPlugins (/Users/davemo/.npm/_npx/16586/lib/node_modules/ghost-cli/node_modules/find-plugins/index.js:28:18)
    at findExtensions (/Users/davemo/.npm/_npx/16586/lib/node_modules/ghost-cli/lib/utils/find-extensions.js:24:12)
    at Object.run (/Users/davemo/.npm/_npx/16586/lib/node_modules/ghost-cli/lib/bootstrap.js:97:28)
    at Object.<anonymous> (/Users/davemo/.npm/_npx/16586/lib/node_modules/ghost-cli/bin/ghost:16:11)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

**Comment by davemo** [comment]
👍
