### ISSUE TITLE
No issues from Ghost doctor but ghost not starting and no errors

### ISSUE THREAD

**Issue by OllieCo** [TryGhost/Ghost-CLI#746]
Welcome to Ghost-CLI's GitHub repo! 👋🎉

Do you need help or have a question? Please come chat in our forum: https://forum.ghost.org 👫.

Docs: https://docs.ghost.org 📖.

Please be aware that the team behind the Ghost CLI only supports the recommended stack: https://github.com/TryGhost/Ghost-cli#recommended-stack.

## This issue is a

* [ ] Bug Report
* [ ] Feature Request

Please fill out this template, deleting where appropriate:

### Summary

Bugs reports: search GitHub for existing issues & check the docs: https://docs.ghost.org/docs/troubleshooting. If you're still stuck, please provide a quick summary of the problem, steps to reproduce, and full tech details including logs.

Feature requests: describe the feature and make a clear, detailed case for adding it.

### Steps to Reproduce (for a bug report)

1. This is the first step
2. This is the second step, etc.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Log file (for a bug report)

All errors end with "Additional log info available in: [filepath]".

Use the command `cat [filepath]` to read the log, then copy & paste the contents here:

```
Paste log file here
```
Debug Information:
    OS: Ubuntu, v16.04
    Node Version: v6.14.2
    Ghost-CLI Version: 1.8.1
    Environment: production
    Command: 'ghost start'
Message: Ghost did not start.
Suggestion: journalctl -u ghost_olliecoady-com-au -n 50
Stack: Error: Ghost did not start.
    at connectToGhostSocket.then.catch (/usr/lib/node_modules/ghost-cli/lib/utils/port-polling.js:94:32)
    at process._tickCallback (internal/process/next_tick.js:109:7)

Original Error Message:
Message: connect ECONNREFUSED 127.0.0.1:2368
Stack: Error: connect ECONNREFUSED 127.0.0.1:2368
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1099:14)

### Technical details (for a bug report)

This is automatically output by Ghost-CLI if an error occurs, please copy & paste:

var/www/ghost$ ghost start
Running sudo command: systemctl is-active ghost_[URL]
✔ Ensuring user is not logged in as ghost user
✔ Checking if logged in user is directory owner
✔ Checking current folder permissions
Running sudo command: systemctl is-active ghost_[URL]
✔ Validating config
✔ Checking folder permissions
✔ Checking file permissions
✔ Checking content folder ownership
✔ Checking memory availability
Running sudo command: systemctl start ghost_[URL]
Running sudo command: systemctl stop ghost_[URL]
✖ Starting Ghost
A GhostError occurred.

Message: Ghost did not start.
Suggestion: journalctl -u ghost_[URL] -n 50

Debug Information:
    OS: Ubuntu, v16.04
    Node Version: v6.14.2
    Ghost-CLI Version: 1.8.1
    Environment: production
    Command: 'ghost start'

* OS:
* Node Version:
* Ghost-CLI Version:
* Environment:
* Command:

## Bug submission checklist

Please fill out this checklist to acknowledge that you followed the requirements to submit a bug report.

- [✔] Tried to find help in the forum & docs
- [✔] Checked for existing issues
- [✔] Attached log file
- [✔] Provided technical details incl. operating system

**Comment by kirrg001** [comment]
Hey @OllieCo!

What is the output of

> Suggestion: sudo journalctl -u ghost_olliecoady-com-au -n 50

What is the output of

> ls -la /var/www/ghost

**Comment by OllieCo** [comment]
Output: 
-- Logs begin at Thu 2018-05-24 17:54:22 UTC, end at Tue 2018-06-12 06:27:26 UTC. --
Jun 12 03:26:05 ubuntu-xenial-1 node[12762]: INFO [2018-06-12 03:26:05] "PUT /ghost/api/v0.1/posts/5b1f3d0a18045431f442427a/?include=tags"
Jun 12 03:26:48 ubuntu-xenial-1 node[12762]: INFO [2018-06-12 03:26:48] "PUT /ghost/api/v0.1/posts/5b1f3d0a18045431f442427a/?include=tags"
Jun 12 03:27:11 ubuntu-xenial-1 node[12762]: INFO [2018-06-12 03:27:11] "PUT /ghost/api/v0.1/posts/5b1f3d0a18045431f442427a/?include=tags"
Jun 12 03:27:37 ubuntu-xenial-1 node[12762]: INFO [2018-06-12 03:27:37] "PUT /ghost/api/v0.1/posts/5b1f3d0a18045431f442427a/?include=tags"
Jun 12 03:28:09 ubuntu-xenial-1 node[12762]: INFO [2018-06-12 03:28:09] "PUT /ghost/api/v0.1/posts/5b1f3d0a18045431f442427a/?include=tags"
Jun 12 03:38:42 ubuntu-xenial-1 node[12762]: INFO [2018-06-12 03:38:42] "PUT /ghost/api/v0.1/posts/5b1f3d0a18045431f442427a/?include=tags"
Jun 12 03:39:23 ubuntu-xenial-1 node[12762]: INFO [2018-06-12 03:39:23] "PUT /ghost/api/v0.1/posts/5b1f3d0a18045431f442427a/?include=tags"
Jun 12 03:39:37 ubuntu-xenial-1 node[12762]: INFO [2018-06-12 03:39:37] "PUT /ghost/api/v0.1/posts/5b1f3d0a18045431f442427a/?include=tags"
Jun 12 03:40:17 ubuntu-xenial-1 node[12762]: INFO [2018-06-12 03:40:17] "PUT /ghost/api/v0.1/posts/5b1f3d0a18045431f442427a/?include=tags"
Jun 12 03:43:09 ubuntu-xenial-1 node[12762]: INFO [2018-06-12 03:43:09] "PUT /ghost/api/v0.1/posts/5b1f3d0a18045431f442427a/?include=tags"
Jun 12 03:43:28 ubuntu-xenial-1 node[12762]: INFO [2018-06-12 03:43:28] "PUT /ghost/api/v0.1/posts/5b1f3d0a18045431f442427a/?include=tags"
Jun 12 03:43:34 ubuntu-xenial-1 node[12762]: INFO [2018-06-12 03:43:34] "PUT /ghost/api/v0.1/posts/5b1f3d0a18045431f442427a/?include=tags"
Jun 12 03:43:38 ubuntu-xenial-1 node[12762]: INFO [2018-06-12 03:43:38] "PUT /ghost/api/v0.1/posts/5b1f3d0a18045431f442427a/?include=tags"
Jun 12 03:43:49 ubuntu-xenial-1 node[12762]: INFO [2018-06-12 03:43:49] "PUT /ghost/api/v0.1/posts/5b1f3d0a18045431f442427a/?include=tags"
Jun 12 03:44:17 ubuntu-xenial-1 node[12762]: INFO [2018-06-12 03:44:17] "PUT /ghost/api/v0.1/posts/5b1f3d0a18045431f442427a/?include=tags"
Jun 12 03:45:32 ubuntu-xenial-1 node[12762]: INFO [2018-06-12 03:45:32] "PUT /ghost/api/v0.1/posts/5b1f3d0a18045431f442427a/?include=tags"
Jun 12 03:46:15 ubuntu-xenial-1 node[12762]: INFO [2018-06-12 03:46:15] "PUT /ghost/api/v0.1/posts/5b1f3d0a18045431f442427a/?include=tags"
Jun 12 03:46:20 ubuntu-xenial-1 node[12762]: INFO [2018-06-12 03:46:20] "PUT /ghost/api/v0.1/posts/5b1f3d0a18045431f442427a/?include=tags"
Jun 12 03:46:28 ubuntu-xenial-1 node[12762]: INFO [2018-06-12 03:46:28] "PUT /ghost/api/v0.1/posts/5b1f3d0a18045431f442427a/?include=tags"
Jun 12 03:47:28 ubuntu-xenial-1 node[12762]: INFO [2018-06-12 03:47:28] "PUT /ghost/api/v0.1/posts/5b1f3d0a18045431f442427a/?include=tags"
Jun 12 03:47:37 ubuntu-xenial-1 node[12762]: INFO [2018-06-12 03:47:37] "PUT /ghost/api/v0.1/posts/5b1f3d0a18045431f442427a/?include=tags"
Jun 12 03:48:15 ubuntu-xenial-1 node[12762]: INFO [2018-06-12 03:48:15] "PUT /ghost/api/v0.1/posts/5b1f3d0a18045431f442427a/?include=tags"
Jun 12 03:49:33 ubuntu-xenial-1 node[12762]: INFO [2018-06-12 03:49:33] "PUT /ghost/api/v0.1/posts/5b1f3d0a18045431f442427a/?include=tags"
Jun 12 03:49:55 ubuntu-xenial-1 node[12762]: INFO [2018-06-12 03:49:55] "PUT /ghost/api/v0.1/posts/5b1f3d0a18045431f442427a/?include=tags"
Jun 12 03:51:13 ubuntu-xenial-1 node[12762]: INFO [2018-06-12 03:51:13] "PUT /ghost/api/v0.1/posts/5b1f3d0a18045431f442427a/?include=tags"
Jun 12 03:51:42 ubuntu-xenial-1 node[12762]: INFO [2018-06-12 03:51:42] "PUT /ghost/api/v0.1/posts/5b1f3d0a18045431f442427a/?include=tags"
Jun 12 03:52:19 ubuntu-xenial-1 node[12762]: INFO [2018-06-12 03:52:19] "PUT /ghost/api/v0.1/posts/5b1f3d0a18045431f442427a/?include=tags"
Jun 12 03:53:40 ubuntu-xenial-1 node[12762]: INFO [2018-06-12 03:53:40] "PUT /ghost/api/v0.1/posts/5b1f3d0a18045431f442427a/?include=tags"
Jun 12 03:55:04 ubuntu-xenial-1 node[12762]: INFO [2018-06-12 03:55:04] "PUT /ghost/api/v0.1/posts/5b1f3d0a18045431f442427a/?include=tags"
Jun 12 03:57:13 ubuntu-xenial-1 node[12762]: INFO [2018-06-12 03:57:13] "PUT /ghost/api/v0.1/posts/5b1f3d0a18045431f442427a/?include=tags"
Jun 12 03:57:22 ubuntu-xenial-1 node[12762]: INFO [2018-06-12 03:57:22] "PUT /ghost/api/v0.1/posts/5b1f3d0a18045431f442427a/?include=tags"
Jun 12 03:57:25 ubuntu-xenial-1 node[12762]: INFO [2018-06-12 03:57:25] "PUT /ghost/api/v0.1/posts/5b1f3d0a18045431f442427a/?include=tags"
Jun 12 03:57:32 ubuntu-xenial-1 node[12762]: INFO [2018-06-12 03:57:32] "PUT /ghost/api/v0.1/posts/5b1f3d0a18045431f442427a/?include=tags"
Jun 12 03:58:44 ubuntu-xenial-1 node[12762]: INFO [2018-06-12 03:58:44] "PUT /ghost/api/v0.1/posts/5b1f3d0a18045431f442427a/?include=tags"
Jun 12 03:58:54 ubuntu-xenial-1 node[12762]: INFO [2018-06-12 03:58:54] "PUT /ghost/api/v0.1/posts/5b1f3d0a18045431f442427a/?include=tags"
Jun 12 03:59:18 ubuntu-xenial-1 node[12762]: INFO [2018-06-12 03:59:18] "PUT /ghost/api/v0.1/posts/5b1f3d0a18045431f442427a/?include=tags"
Jun 12 03:59:25 ubuntu-xenial-1 node[12762]: INFO [2018-06-12 03:59:25] "PUT /ghost/api/v0.1/posts/5b1f3d0a18045431f442427a/?include=tags"
Jun 12 03:59:42 ubuntu-xenial-1 node[12762]: INFO [2018-06-12 03:59:42] "PUT /ghost/api/v0.1/posts/5b1f3d0a18045431f442427a/?include=tags"
Jun 12 03:59:47 ubuntu-xenial-1 node[12762]: INFO [2018-06-12 03:59:47] "PUT /ghost/api/v0.1/posts/5b1f3d0a18045431f442427a/?include=tags"
Jun 12 04:00:04 ubuntu-xenial-1 node[12762]: INFO [2018-06-12 04:00:04] "PUT /ghost/api/v0.1/posts/5b1f3d0a18045431f442427a/?include=tags"
Jun 12 04:00:49 ubuntu-xenial-1 node[12762]: INFO [2018-06-12 04:00:49] "PUT /ghost/api/v0.1/posts/5b1f3d0a18045431f442427a/?include=tags"
Jun 12 04:01:01 ubuntu-xenial-1 node[12762]: INFO [2018-06-12 04:01:01] "PUT /ghost/api/v0.1/posts/5b1f3d0a18045431f442427a/?include=tags"
Jun 12 04:01:07 ubuntu-xenial-1 node[12762]: INFO [2018-06-12 04:01:07] "PUT /ghost/api/v0.1/posts/5b1f3d0a18045431f442427a/?include=tags"
Jun 12 04:01:13 ubuntu-xenial-1 node[12762]: INFO [2018-06-12 04:01:13] "PUT /ghost/api/v0.1/posts/5b1f3d0a18045431f442427a/?include=tags"
Jun 12 04:01:59 ubuntu-xenial-1 node[12762]: INFO [2018-06-12 04:01:59] "PUT /ghost/api/v0.1/posts/5b1f3d0a18045431f442427a/?include=tags"
Jun 12 04:02:04 ubuntu-xenial-1 node[12762]: INFO [2018-06-12 04:02:04] "PUT /ghost/api/v0.1/posts/5b1f3d0a18045431f442427a/?include=tags"
Jun 12 06:26:43 ubuntu-xenial-1 node[12762]: INFO [2018-06-12 06:26:43] "GET /robots.txt" 301 5ms
Jun 12 06:26:43 ubuntu-xenial-1 node[12762]: INFO [2018-06-12 06:26:43] "GET /robots.txt" 200 5ms
Jun 12 06:26:46 ubuntu-xenial-1 node[12762]: INFO [2018-06-12 06:26:46] "GET /" 200 86ms
Jun 12 06:26:46 ubuntu-xenial-1 node[12762]: INFO [2018-06-12 06:26:46] "GET /" 301 2ms
lines 1-51/51 (END)

Output
