### ISSUE TITLE
Error with db migrations when installing 

### ISSUE THREAD

**Issue by vilvadot** [TryGhost/Ghost-CLI#782]
### Summary

I tried installing via `ghost install` and everything goes alright until the database migrations where I get an error.

Seems like a node syntax error in a dependency to me. But version 8.9.0 supposedly supports let ???

BTW using node 8.9.0 installed vía nvm if it matters

### Steps to Reproduce

1. Run ghost install
2. Continue the process until database migrations

### Log file

```
Message: The database migration in Ghost encountered an error.
Help: https://docs.ghost.org/v1/docs/troubleshooting#section-general-update-error
--------------- stderr ---------------
/var/www/ghost/versions/1.25.4/node_modules/knex-migrator/lib/utils.js:11
    let files = [],
    ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/var/www/ghost/versions/1.25.4/node_modules/knex-migrator/bin/knex-migrator-migrate:4:13)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
```

### Technical details

    OS: Ubuntu, v16.04
    Node Version: v8.9.0
    Ghost-CLI Version: 1.8.1
    Environment: production
    Command: 'ghost install'

## Bug submission checklist

Please fill out this checklist to acknowledge that you followed the requirements to submit a bug report.

- [x] Tried to find help in the forum & docs
- [x] Checked for existing issues
- [x] Attached log file
- [x] Provided technical details incl. operating system

**Comment by vikaspotluri123** [comment]
Hmm, it looks like knex-migrator is running in an older version of node - that error usually comes up w/ node v4, since v6 started supporting Block-scoped declarations.

Can you check that the Ghost node version is valid (run `sudo -u ghost node -v` or `sudo -E -u ghost node -v`)

**Comment by vilvadot** [comment]
You are right. Its running 4.2.3. Shouldn't it be using the system's node version?.

Also how can I upgrade it for ghost to 8.9.0. thanks!

**Comment by vikaspotluri123** [comment]
Since this isn't a bug with the CLI, could you please open an issue on [the forum](https://forum.ghost.org)?
