### ISSUE TITLE
"ghost install local" and "ghost start" fails on win 10

### ISSUE THREAD

**Issue by hackhat** [TryGhost/Ghost-CLI#827]
Error:

        Debug Information:
            OS: Microsoft Windows, v10.0.17134
            Node Version: v8.9.0
            Ghost-CLI Version: 1.9.4
            Environment: development
            Command: 'ghost start'
        Message: Ghost process exited with code: 0
        Stack: Error: Ghost process exited with code: 0
            at ChildProcess.cp.on (C:\Users\xxx\AppData\Roaming\npm\node_modules\ghost-cli\lib\utils\local-process.js:56:24)
            at emitTwo (events.js:126:13)
            at ChildProcess.emit (events.js:214:7)
            at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
        
(by the way on this page https://docs.ghost.org/docs/install-local you forget to mention that `ghost start` even exists)

**Comment by acburdine** [comment]
@hackhat unfortunately I don't use Windows 10 normally, and thus it's a bit more work to test the local setup there 😕There definitely seems to be an issue, and I'll spin up a windows VM and look into this further later this week.

> (Also note that the link in ghost doctor goes to v1 not v2: You can always refer to https://docs.ghost.org/v1/docs/troubleshooting#section-cli-errors for troubleshooting)

good catch! will definitely fix that.

**Comment by javenschuetz** [comment]
I'm getting this on ubuntu 19.04 with node 10.x today.

"Ensuring user is not logged in as ghost user [skipped]
ℹ Checking if logged in user is directory owner [skipped]
✔ Checking current folder permissions
✔ Validating config
✖ Starting Ghost
A GhostError occurred.

Message: Ghost process exited with code: null

Debug Information:
    OS: Ubuntu, v19.04
    Node Version: v10.16.0
    Ghost-CLI Version: 1.11.0
    Environment: development
    Command: 'ghost restart'"

"Message: Ghost process exited with code: null
Stack: Error: Ghost process exited with code: null
    at ChildProcess.cp.on (/home/jammygit/.npm-global/lib/node_modules/ghost-cli/lib/utils/local-process.js:56:24)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)"

**Comment by AleMunin** [comment]
Hi, this is my first time using ghost, and I couldn't get it started on installation.

Doctor and Start would say everything but not start. Log wouldn't give me an explanation whatsoever to why it wouldn't.

```Debug Information:
    OS: Zorin, v16.2
    Node Version: v18.15.0
    Ghost Version: 5.39.0
    Ghost-CLI Version: 1.24.0
    Environment: development
    Command: 'ghost install local'
Message: Ghost process exited with code: null
Stack: Error: Ghost process exited with code: null
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/ghost-cli/lib/utils/local-process.js:68:24)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

When trying to find out why "ghost start" or even the no-user workaround was working, I found a post talking about "ghost run" not doing some pre-start requirements and figured I'd finally get to work, only then I got my actual error message. Why isn't Ghost Run in the documentation as a alternative?

```ghost run

Love open source? We’re hiring JavaScript Engineers to work on Ghost full-time.
https://careers.ghost.org

The `ghost run` command is used by the configured Ghost process manager and for debugging. If you're not running this to debug something, you should run `ghost start` instead.
[2023-03-21 03:15:48] INFO Ghost is running in production...
[2023-03-21 03:15:48] INFO Your site is now available on http://localhost:2368/
[2023-03-21 03:15:48] INFO Ctrl+C to shut down
[2023-03-21 03:15:48] INFO Ghost server started in 0.825s
[2023-03-21 03:15:48] ERROR connect ECONNREFUSED 127.0.0.1:3306

connect ECONNREFUSED 127.0.0.1:3306

"Unknown database error"

Error ID:
    500

Error Code: 
    ECONNREFUSED

----------------------------------------

Error: connect ECONNREFUSED 127.0.0.1:3306
    at /home/munin/Documents/Projects/Websites/Moriverse 2.0/Ghost Site/versions/5.39.0/node_modules/knex-migrator/lib/database.js:57:19
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)

```

I am very confused on to why it says "running in production" when I did try to run in development and got the same error.

Has anyone figured a workaround for this problem? It is my first time using this ever so I'm not sure where even to begin with an error like this.
