### ISSUE TITLE
 Ghost process exited with code: 0

### ISSUE THREAD

**Issue by winecat** [TryGhost/Ghost-CLI#862]
i update the ghost to 2.11.0
and then it no more work
```
$ ghost start
Process manager 'systemd' will not run on this system, defaulting to 'local'
✔ Ensuring user is not logged in as ghost user
✔ Checking if logged in user is directory owner
✔ Checking current folder permissions
✔ Validating config
✔ Checking folder permissions
✔ Checking file permissions
✔ Checking content folder ownership
✔ Checking memory availability
✖ Starting Ghost
A GhostError occurred.

Message: Ghost process exited with code: 0

Debug Information:
    OS: linux, v2.6.32-696.6.3.el6.x86_64
    Node Version: v8.9.4
    Ghost-CLI Version: 1.9.9
    Environment: production
    Command: 'ghost start'

Additional log info available in: /home/myself/.ghost/logs/ghost-cli-debug-2019-01-16T11_49_47_508Z.log

Try running ghost doctor to check your system for known issues.
```
the log is:
```
Debug Information:
    OS: linux, v2.6.32-696.6.3.el6.x86_64
    Node Version: v8.9.4
    Ghost-CLI Version: 1.9.9
    Environment: production
    Command: 'ghost start'
Message: Ghost process exited with code: 0
Stack: Error: Ghost process exited with code: 0
    at ChildProcess.cp.on (/root/.nvm/versions/node/v8.9.4/lib/node_modules/ghost-cli/lib/utils/local-process.js:56:24)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```
and ghost doctor is
```
$ ghost doctor
Process manager 'systemd' will not run on this system, defaulting to 'local'
✔ Checking system Node.js version
✔ Checking logged in user
✔ Ensuring user is not logged in as ghost user
✔ Checking if logged in user is directory owner
✔ Checking current folder permissions
System checks failed with message: 'Linux version is not Ubuntu 16 or 18'
Some features of Ghost-CLI may not work without additional configuration.
For local installs we recommend using `ghost install local` instead.
? Continue anyway? Yes
System stack check skipped
ℹ Checking operating system compatibility [skipped]
✔ Validating config
✔ Checking folder permissions
✔ Checking file permissions
✔ Checking content folder ownership
✔ Checking memory availability
```
what happen??

**Comment by acburdine** [comment]
@winecat can you please try running `ghost run` and see what the output is?

**Comment by ahmednabil950** [comment]
@acburdine when i ran ghost run it outputs:
```2019-02-11 21:44:09] INFO Ghost is running in production...```
```INFO Your blog is now available on http://localhost:2368/```
seems it works but why in production ??
i was working on deploying it and it ran perfectlyon my remote server but i dont know why 
```ghost start``` does not work anymore
