### ISSUE TITLE
InternalServerError: Sharp wasn't installed

### ISSUE THREAD

**Issue by mjkowalski** [TryGhost/Ghost-CLI#870]
### Summary

After a fresh installation of Ghost 2.12.0 via CLI and setting publication cover image the request for the image (on blog's home page) returns 500 with:
```
<h1 class="error-code">500</h1>
<p class="error-description">Sharp wasn&#x27;t installed</p>
```
Sharp has not been installed (`ls -la node_modules/ | grep sharp` returns nothing) but according to the https://github.com/TryGhost/Ghost-CLI/issues/844#issuecomment-429620397 
> Without sharp installed Ghost falls back gracefully to its old behaviour of not optimising images. That's it. Ghost will still function in every other way.

I also tried with setting:
```
  "imageOptimization": {
    "resize": false
  }
```
in `config.production.json` but the problem still occurs.

I guess this could be an issue with https://github.com/TryGhost/Ghost/blob/0f32209e65089576b7e3b6cffab76bc4c613a530/core/server/web/shared/middlewares/image/handle-image-sizes.js#L68
```
if (err.code === 'SHARP_INSTALLATION') {
    return redirectToOriginal();
}
```
cause in my case (according to the logfile) I'm getting `MODULE_NOT_FOUND` error.

### Steps to Reproduce

1. Install Ghost 2.12.0 via CLI on the environment that does not suport sharp library.
2. Set publication cover image (different Casper's default)
3. Reload the blog's homepage (the image should not be visible)

### Log file

```
App 170 output: ERROR [2019-01-26 21:59:00] "GET /content/images/size/w2000/2019/01/cover.min-1.png" 500 6ms
App 170 output: 
App 170 output: NAME: InternalServerError
App 170 output: CODE: MODULE_NOT_FOUND
App 170 output: MESSAGE: Sharp wasn't installed
App 170 output: 
App 170 output: level:critical
App 170 output: 
App 170 output: empty
App 170 output: empty
App 170 output: ERROR DETAILS:
App 170 output:     empty
App 170 output: 
App 170 output: InternalServerError: Sharp wasn't installed
App 170 output:     at new InternalServerError (/usr/home/blogusr/domains/hidden_blog_url/versions/2.12.0/node_modules/ghost-ignition/lib/errors/index.js:71:23)
App 170 output:     at Object.err [as resizeImage] (/usr/home/blogusr/domains/hidden_blog_url/versions/2.12.0/core/server/lib/image/manipulator.js:49:31)
App 170 output:     at storageInstance.exists.then.then.then (/usr/home/blogusr/domains/hidden_blog_url/versions/2.12.0/core/server/web/shared/middlewares/image/handle-image-sizes.js:78:42)
App 170 output:     at tryCatcher (/usr/home/blogusr/domains/hidden_blog_url/versions/2.12.0/node_modules/bluebird/js/release/util.js:16:23)
App 170 output:     at Promise._settlePromiseFromHandler (/usr/home/blogusr/domains/hidden_blog_url/versions/2.12.0/node_modules/bluebird/js/release/promise.js:512:31)
App 170 output:     at Promise._settlePromise (/usr/home/blogusr/domains/hidden_blog_url/versions/2.12.0/node_modules/bluebird/js/release/promise.js:569:18)
App 170 output:     at Promise._settlePromise0 (/usr/home/blogusr/domains/hidden_blog_url/versions/2.12.0/node_modules/bluebird/js/release/promise.js:614:10)
App 170 output:     at Promise._settlePromises (/usr/home/blogusr/domains/hidden_blog_url/versions/2.12.0/node_modules/bluebird/js/release/promise.js:694:18)
App 170 output:     at _drainQueueStep (/usr/home/blogusr/domains/hidden_blog_url/versions/2.12.0/node_modules/bluebird/js/release/async.js:138:12)
App 170 output:     at _drainQueue (/usr/home/blogusr/domains/hidden_blog_url/versions/2.12.0/node_modules/bluebird/js/release/async.js:131:9)
App 170 output:     at Async._drainQueues (/usr/home/blogusr/domains/hidden_blog_url/versions/2.12.0/node_modules/bluebird/js/release/async.js:147:5)
App 170 output:     at Immediate.Async.drainQueues (/usr/home/blogusr/domains/hidden_blog_url/versions/2.12.0/node_modules/bluebird/js/release/async.js:17:14)
App 170 output:     at runCallback (timers.js:672:20)
App 170 output:     at tryOnImmediate (timers.js:645:5)
App 170 output:     at processImmediate [as _immediateCallback] (timers.js:617:5)
App 170 output: 
App 170 output: Error: Cannot find module 'sharp'
App 170 output:     at Function.Module._resolveFilename (module.js:476:15)
App 170 output:     at Function.Module._load (module.js:424:25)
App 170 output:     at Module.require (module.js:504:17)
App 170 output:     at Module.require (/usr/local/lib/ruby/gems/2.4/gems/passenger-5.3.4/src/helper-scripts/node-loader.js:80:25)
App 170 output:     at require (internal/module.js:20:19)
App 170 output:     at Object.err [as resizeImage] (/usr/home/blogusr/domains/hidden_blog_url/versions/2.12.0/core/server/lib/image/manipulator.js:47:9)
App 170 output:     at storageInstance.exists.then.then.then (/usr/home/blogusr/domains/hidden_blog_url/versions/2.12.0/core/server/web/shared/middlewares/image/handle-image-sizes.js:78:42)
App 170 output:     at tryCatcher (/usr/home/blogusr/domains/hidden_blog_url/versions/2.12.0/node_modules/bluebird/js/release/util.js:16:23)
App 170 output:     at Promise._settlePromiseFromHandler (/usr/home/blogusr/domains/hidden_blog_url/versions/2.12.0/node_modules/bluebird/js/release/promise.js:512:31)
App 170 output:     at Promise._settlePromise (/usr/home/blogusr/domains/hidden_blog_url/versions/2.12.0/node_modules/bluebird/js/release/promise.js:569:18)
App 170 output:     at Promise._settlePromise0 (/usr/home/blogusr/domains/hidden_blog_url/versions/2.12.0/node_modules/bluebird/js/release/promise.js:614:10)
App 170 output:     at Promise._settlePromises (/usr/home/blogusr/domains/hidden_blog_url/versions/2.12.0/node_modules/bluebird/js/release/promise.js:694:18)
App 170 output:     at _drainQueueStep (/usr/home/blogusr/domains/hidden_blog_url/versions/2.12.0/node_modules/bluebird/js/release/async.js:138:12)
App 170 output:     at _drainQueue (/usr/home/blogusr/domains/hidden_blog_url/versions/2.12.0/node_modules/bluebird/js/release/async.js:131:9)
App 170 output:     at Async._drainQueues (/usr/home/blogusr/domains/hidden_blog_url/versions/2.12.0/node_modules/bluebird/js/release/async.js:147:5)
App 170 output:     at Immediate.Async.drainQueues (/usr/home/blogusr/domains/hidden_blog_url/versions/2.12.0/node_modules/bluebird/js/release/async.js:17:14)
```

### Technical details

Output from `ghost doctor`:
```
Debug Information:
    OS: freebsd, v11.2-RELEASE-p2
    Node Version: v6.14.4
    Ghost-CLI Version: 1.9.9
    Environment: production
    Command: 'ghost doctor'
```

**Comment by acburdine** [comment]
@mjkowalski Not sure if this issue belongs in the CLI repo. There's not much we can do about sharp being supported on your environment. As for the issue of the error code being detected incorrectly - I believe that's something that can be fixed in Ghost itself, in which case this issue would need to be opened on the [Ghost repo](https://github.com/TryGhost/Ghost). 😄

**Comment by mjkowalski** [comment]
Of course, you're right @acburdine  - that's what happens when you have too many open tabs within your browser... I'll create another ticket there. Thank you! :+1:

**Comment by mjkowalski** [comment]
Nevertheless, it looks like this could solve my issue: https://github.com/TryGhost/Ghost/pull/10415

**Comment by bmdev88** [comment]
Hi, i've solved my issue with this "trick":
[Ghost Blog - Solved Error Sharp wasn't installed](https://blog.bernsteiner.net/blog/sharp_installation/)
