### ISSUE TITLE
Unable to restart / start ghost instance

### ISSUE THREAD

**Issue by compulshun** [TryGhost/Ghost-CLI#884]
Similar to issue #430, my ghost installation is failing to restart. Shut the service down via systemctl stop, but it still won't start again.

ℹ Ensuring user is not logged in as ghost user [skipped]
ℹ Checking if logged in user is directory owner [skipped]
✔ Checking current folder permissions
✔ Validating config
✔ Checking content folder ownership
✔ Checking memory availability
✖ Starting Ghost
A SystemError occurred.

Message: The content folder is not owned by the current user.
Ensure the content folder has correct permissions and try again.

Debug Information:
    OS: Ubuntu, v18.04
    Node Version: v8.10.0
    Ghost-CLI Version: 1.9.9
    Environment: production
    Command: 'ghost start'

Try running ghost doctor to check your system for known issues.

ghost run gives me:

eythan@slootweg:/var/www/ghost$ ghost run
The `ghost run` command is used by the configured Ghost process manager and for debugging. If you're not running this to debug something, you should run `ghost start` instead.
+ sudo node current/index.js
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: EACCES: permission denied, open '/var/www/ghost/versions/2.10.1/content/logs/http___slootweg_ca_production.error.log'

this log file doesn't exist, though.

**Comment by alphaswell** [comment]
I've set the user as being the owner of the folder with chown, and it's properly chmoded to 775

**Comment by alphaswell** [comment]
After realizing I was being dumb and setting user as the owner of /var/www/ghost/content as well, running ghost start gives this error:


ℹ Ensuring user is not logged in as ghost user [skipped]
ℹ Checking if logged in user is directory owner [skipped]
✔ Checking current folder permissions
✔ Validating config
✔ Checking memory availability
✖ Starting Ghost
A GhostError occurred.

Message: Cannot read property 'engine' of undefined

Debug Information:
    OS: Ubuntu, v18.04
    Node Version: v8.10.0
    Ghost-CLI Version: 1.9.9
    Environment: production
    Command: 'ghost start'

Additional log info available in: /home/ghost-mgr/.ghost/logs/ghost-cli-debug-2019-03-21T22_59_00_366Z.log

Try running ghost doctor to check your system for known issues.

which says:

Debug Information:
    OS: Ubuntu, v18.04
    Node Version: v8.10.0
    Ghost-CLI Version: 1.9.9
    Environment: production
    Command: 'ghost start'
Message: Cannot read property 'engine' of undefined
Stack: Error: Cannot read property 'engine' of undefined
    at ChildProcess.cp.on (/usr/local/lib/node_modules/ghost-cli/lib/utils/local-process.js:63:35)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by alphaswell** [comment]
ghost run gives me:

The `ghost run` command is used by the configured Ghost process manager and for debugging. If you're not running this to debug something, you should run `ghost start` instead.
[2019-03-21 23:05:34] ERROR

NAME: NotFoundError
CODE: ENOENT
MESSAGE: The currently active theme "innocent-master" is missing.

level:normal

"name: innocent-master"
"path: /var/www/ghost/versions/2.10.1/content/themes/"
ERROR DETAILS:
    empty

NotFoundError: Package not found
    at new NotFoundError (/var/www/ghost/versions/2.10.1/node_modules/ghost-ignition/lib/errors/index.js:87:23)
    at /var/www/ghost/versions/2.10.1/core/server/lib/fs/package-json/read.js:57:35
    at tryCatcher (/var/www/ghost/versions/2.10.1/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/www/ghost/versions/2.10.1/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/var/www/ghost/versions/2.10.1/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/var/www/ghost/versions/2.10.1/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/www/ghost/versions/2.10.1/node_modules/bluebird/js/release/promise.js:690:18)
    at _drainQueueStep (/var/www/ghost/versions/2.10.1/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/var/www/ghost/versions/2.10.1/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/var/www/ghost/versions/2.10.1/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/var/www/ghost/versions/2.10.1/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)

Error: ENOENT: no such file or directory, stat '/var/www/ghost/versions/2.10.1/content/themes/innocent-master'

[2019-03-21 23:05:34] ERROR

NAME: InternalServerError
MESSAGE: Cannot read property 'engine' of undefined

level:normal

empty
empty
ERROR DETAILS:
    empty

InternalServerError: Cannot read property 'engine' of undefined
    at new GhostError (/var/www/ghost/versions/2.10.1/core/server/lib/common/errors.js:10:26)
    at server.catch (/var/www/ghost/versions/2.10.1/core/index.js:16:23)
    at tryCatcher (/var/www/ghost/versions/2.10.1/node_modules/knex-migrator/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/www/ghost/versions/2.10.1/node_modules/knex-migrator/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/var/www/ghost/versions/2.10.1/node_modules/knex-migrator/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/var/www/ghost/versions/2.10.1/node_modules/knex-migrator/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/www/ghost/versions/2.10.1/node_modules/knex-migrator/node_modules/bluebird/js/release/promise.js:690:18)
    at _drainQueueStep (/var/www/ghost/versions/2.10.1/node_modules/knex-migrator/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/var/www/ghost/versions/2.10.1/node_modules/knex-migrator/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/var/www/ghost/versions/2.10.1/node_modules/knex-migrator/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/var/www/ghost/versions/2.10.1/node_modules/knex-migrator/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)

TypeError: Cannot read property 'engine' of undefined
    at Resources._initResourceConfig (/var/www/ghost/versions/2.10.1/core/server/services/url/Resources.js:48:68)
    at Resources.fetchResources (/var/www/ghost/versions/2.10.1/core/server/services/url/Resources.js:55:14)
    at emitNone (events.js:106:13)
    at EventRegistry.emit (events.js:208:7)
    at settings.init.then.then.then (/var/www/ghost/versions/2.10.1/core/server/index.js:108:31)
    at tryCatcher (/var/www/ghost/versions/2.10.1/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/www/ghost/versions/2.10.1/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/var/www/ghost/versions/2.10.1/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/var/www/ghost/versions/2.10.1/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/www/ghost/versions/2.10.1/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/var/www/ghost/versions/2.10.1/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/var/www/ghost/versions/2.10.1/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/var/www/ghost/versions/2.10.1/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/var/www/ghost/versions/2.10.1/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)

ghost-mgr@slootweg:/var/www/ghost$

**Comment by alphaswell** [comment]
So I copied over the relevant theme from var/www/ghost/content/themes to the 2.10.1 version folder, and running ghost start worked. However, still not visible at the website. Did ghost run again and got:


The `ghost run` command is used by the configured Ghost process manager and for debugging. If you're not running this to debug something, you should run `ghost start` instead.
[2019-03-21 23:08:48] WARN Theme's file locales/en-ca.json not found.
[2019-03-21 23:08:48] WARN Falling back to locales/en.json.
[2019-03-21 23:08:48] WARN Theme's file locales/en.json not found.
[2019-03-21 23:08:49] ERROR

NAME: InternalServerError
MESSAGE: (EADDRINUSE) Cannot start Ghost.

level:normal

"Port 8080 is already in use by another program."
"Is another Ghost instance already running?"
ERROR DETAILS:
    empty

InternalServerError: (EADDRINUSE) Cannot start Ghost.
    at new GhostError (/var/www/ghost/versions/2.10.1/core/server/lib/common/errors.js:10:26)
    at Server.<anonymous> (/var/www/ghost/versions/2.10.1/core/server/ghost-server.js:79:30)
    at emitOne (events.js:116:13)
    at Server.emit (events.js:211:7)
    at emitErrorNT (net.js:1387:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by alphaswell** [comment]
If I do ghost stop first and run ghost run, it works. Really not sure why my blog isn't accessible now, as ghost does seem to be running. Getting 502 bad gateway.

**Comment by alznyc** [comment]
We are having the issue
The ghost run command is used by the configured Ghost process manager and for debugging. If you're not running this to debug something, you should run ghost start instead.

sudo node current/index.js
events.js:183
throw er; // Unhandled 'error' event

Also getting 502 bad gateway....HELPPP
