### ISSUE TITLE
Installation error - EISDIR, illegal operation on a directory, symlink 

### ISSUE THREAD

**Issue by kazik56** [TryGhost/Ghost-CLI#885]
### Issue Summary
I installed Ghost from npm with command npm install `ghost-cli@latest -g`. I ecountered error when installing Ghost (`ghost install local`) on my Windows 10 (ver 1809) today. Below is the log.

Things I have done:

- Run `ghost doctor` command (with no luck)
- Checked for simillar or identical issues (none that adress this bug)
- Used elevated command prompt

### To Reproduce
1. `cd LocalTest`
2. `ghost-cli@latest -g`
3. `ghost install local <- whis is where it fails`

### Technical details:
Debug Information:
    OS: Microsoft Windows, v10.0.17763
    Node Version: v10.15.1
    Ghost-CLI Version: 1.9.9
    Environment: development
    Command: 'ghost install local'
```
An error occurred.
Message: 'EISDIR: illegal operation on a directory, symlink '\\?\E:\Web\Ghost\LocalTest\versions\2.18.3' -> '\\?\E:\Web\Ghost\LocalTest\current''

Stack: Error: EISDIR: illegal operation on a directory, symlink '\\?\E:\Web\Ghost\LocalTest\versions\2.18.3' -> '\\?\E:\Web\Ghost\LocalTest\current'
    at Object.symlinkSync (fs.js:905:3)
    at symlinkWindows (C:\Users\noonepc\AppData\Roaming\npm\node_modules\ghost-cli\node_modules\symlink-or-copy\index.js:143:18)
    at symlinkOrCopySync (C:\Users\noonepc\AppData\Roaming\npm\node_modules\ghost-cli\node_modules\symlink-or-copy\index.js:83:5)
    at InstallCommand.link (C:\Users\noonepc\AppData\Roaming\npm\node_modules\ghost-cli\lib\commands\install.js:103:9)
    at Promise.resolve.then.then.skipped (C:\Users\noonepc\AppData\Roaming\npm\node_modules\ghost-cli\node_modules\listr\lib\task.js:167:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Code: EISDIR
Path: \\?\E:\Web\Ghost\LocalTest\versions\2.18.3
```

**Comment by kazik56** [comment]
It turned out to be my mistake to install ghost on exFAT drive which has no support for symlinks. After changing drive to NTFS ghost installed succesfully.
