### ISSUE TITLE
Not working with node 6.14.0

### ISSUE THREAD

**Issue by lmuzquiz** [TryGhost/Ghost-CLI#941]
* OS: Ubuntu 16.04
* Node Version: 6.14.0 
* NPM Version: 3.10.10
* Ghost-CLI Version: 1.10.1
* Environment: Linux, NGINX

### Steps to Reproduce

Run the following commands:

1. sudo npm install -g ghost ghost-cli@latest
2. ghost install

Instead of installing ghost we get the following output:

```
/usr/local/lib/node_modules/ghost-cli/node_modules/latest-version/index.js:4
const lastestVersion = async (packageName, options) => {
                             ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/ghost-cli/lib/utils/pre-checks.js:6:23)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
```

Going back to ghost-cli 1.9.9 by running: **sudo npm install -g ghost ghost-cli@1.9.9** solves the issue

## Bug submission checklist

Please fill out this checklist to acknowledge that you followed the requirements to submit a bug report.

- [x] Tried to find help in the forum & docs
- [x]  Checked for existing issues
- [ ] Attached log file
- [x]  Provided technical details incl. operating system

**Comment by acburdine** [comment]
@lmuzquiz the reason this issue is occurring is, as per the nodejs LTS policy, Ghost-CLI no longer supports node v6 (it became EOL on April 30th).

However, I’ll leave this issue open for a bit until I can get documentation updated, as I did forget to make a note of the nodejs 6 drop in the last release

**Comment by acburdine** [comment]
@lmuzquiz I updated the release notes on both the 1.10.0 and 1.10.1 Ghost-CLI releases to reflect dropped v6 support.

The supported node versions doc in Ghost docs still shows that v6 is supported, however that is likely to be updated soon as well, so I'm going to go ahead and close this issue. Sorry again for the confusion 😅
