### ISSUE TITLE
settingsCache.get(...).replace is not a function when doing restart after stopping a local install

### ISSUE THREAD

**Issue by schollz** [TryGhost/Ghost-CLI#951]
### Summary

Hi, I've installed ghost locally with `ghost install local`. It works great, and I can edit and view pages. Then I do `ghost stop` in the same directory I did the install. Stop works fine. Then, if I try to restart from the same directory using `ghost start` I get an error instead of being able to restart ghost.

### Steps to Reproduce

1. Do `ghost install local`
2. Do `ghost stop`
3. Do `ghost start`

I've done this on both WIndows 10 and Ubuntu 19 and it gives the exact same problem. I've tried running in development mode and it still doesn't work.

### Log file

I've done this on Windows and Ubuntu 19. The log files are almost identical so I will just paste the one from Ubuntu19. The log file for the Windows one is available [on the forum](https://forum.ghost.org/t/error-settingscache-get-replace-is-not-a-function-when-restarting/7784).

Here's what I see when I run it:

```
$ ghost start -V 
Found a development config but not a production config, running in development mode instead
[07:52:36] Ensuring user is not logged in as ghost user [started]
[07:52:36] Ensuring user is not logged in as ghost user [skipped]
[07:52:36] Checking if logged in user is directory owner [started]
[07:52:36] Checking if logged in user is directory owner [skipped]
[07:52:36] Checking current folder permissions [started]
[07:52:36] Checking current folder permissions [completed]
[07:52:36] Validating config [started]
[07:52:36] Validating config [completed]
[07:52:36] Checking memory availability [started]
[07:52:36] Checking memory availability [completed]
✖ Starting Ghost
A GhostError occurred.

Message: settingsCache.get(...).replace is not a function
Stack: Error: settingsCache.get(...).replace is not a function
    at ChildProcess.cp.on (/home/zns/node/node_modules/lib/node_modules/ghost-cli/lib/utils/local-process.js:63:35)
    at ChildProcess.emit (events.js:198:13)
    at emit (internal/child_process.js:832:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)


Debug Information:
    OS: Ubuntu, v19.04
    Node Version: v10.16.0
    Ghost-CLI Version: 1.11.0
    Environment: development
    Command: 'ghost start -V'

Additional log info available in: /home/zns/.ghost/logs/ghost-cli-debug-2019-06-15T14_52_40_229Z.log

Try running ghost doctor to check your system for known issues.

You can always refer to https://docs.ghost.org/api/ghost-cli/ for troubleshooting.
```

Here's the log file:

```
Debug Information:
    OS: Ubuntu, v19.04
    Node Version: v10.16.0
    Ghost-CLI Version: 1.11.0
    Environment: development
    Command: 'ghost start -V'
Message: settingsCache.get(...).replace is not a function
Stack: Error: settingsCache.get(...).replace is not a function
    at ChildProcess.cp.on (/home/zns/node/node_modules/lib/node_modules/ghost-cli/lib/utils/local-process.js:63:35)
    at ChildProcess.emit (events.js:198:13)
    at emit (internal/child_process.js:832:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

### Technical details

    OS: Ubuntu, v19.04
    Node Version: v10.16.0
    Ghost-CLI Version: 1.11.0
    Environment: development
    Command: 'ghost start -V'

## Bug submission checklist

Please fill out this checklist to acknowledge that you followed the requirements to submit a bug report.

- [x] Tried to find help in the forum & docs
- [x] Checked for existing issues
- [x] Attached log file
- [x] Provided technical details incl. operating system

**Comment by ErisDS** [comment]
Can you please provide the output from `ghost version`, and also let us know if this still happens after upgrading to the latest version?

I haven't seen this on my mac when starting / stopping recently.
