### ISSUE TITLE
Issue with local setup after migrating machines 

### ISSUE THREAD

**Issue by anujdeshpande** [TryGhost/Ghost-CLI#980]
### Steps to Reproduce

1. I had to migrate my existing MacOS to a new disk
2. To reproduce you can simply airdrop a ghost local development config to another machine and run `ghost start`

### Log file

```
    Debug Information:                                                                                                                                                                             
    OS: Mac OS X, v10.14.5                                                                                                                                                                     
    Node Version: v10.16.0                                                                                                                                                                     
    Ghost-CLI Version: 1.11.0                                                                                                                                                                  
    Environment: development                                                                                                                                                                   
    Command: 'ghost start'                                                                                                                                                                     
Message: Ghost process exited with code: 0                                                                                                                                                     
Stack: Error: Ghost process exited with code: 0                                                                                                                                                
    at ChildProcess.cp.on (/usr/local/lib/node_modules/ghost-cli/lib/utils/local-process.js:56:24)                                                                                             
    at ChildProcess.emit (events.js:198:13)                                                                                                                                                    
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)                                                                                                                  

```

### Technical details

```
$ ghost doctor
Found a development config but not a production config, running in development mode instead
✔ Checking system Node.js version
✔ Checking current folder permissions
✔ Validating config
✔ Checking memory availability
```
```
Found a development config but not a production config, running in development mode instead
✔ Checking system Node.js version
✔ Checking current folder permissions
✔ Validating config
✔ Checking memory availability
anujs-mbp:ghost anujdeshpande$ ghost run
The `ghost run` command is used by the configured Ghost process manager and for debugging. If you're not running this to debug something, you should run `ghost start` instead.
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/Users/anujdeshpande/code/ghost/current/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```
## Bug submission checklist

Please fill out this checklist to acknowledge that you followed the requirements to submit a bug report.

- [x] Tried to find help in the forum & docs
- [x] Checked for existing issues
- [x] Attached log file
- [x] Provided technical details incl. operating system

**Comment by acburdine** [comment]
@anujdeshpande did you copy over _only_ the config.development.json file or did you copy over the entire installation? If you only copied over the config file, then the error you're getting makes sense, as the remainder of the installation (i.e. the actual Ghost code, database, image files, theme, etc) isn't set up.

**Comment by anujdeshpande** [comment]
Hi @acburdine 
I copied everything afaik -

```
$ tree -L 2
.
├── build.sh
├── config.development.json
├── content
│   ├── apps
│   ├── data
│   ├── images
│   ├── logs
│   ├── settings
│   └── themes
├── node_modules
│   ├── node
│   └── node-bin-setup
├── package-lock.json
├── static
│   ├── applying-for-a-job-at-espressif-india
│   ├── assets
│   ├── author
│   ├── content
│   ├── favicon.png
│   ├── fossasia-19-and-awesome-hardware
│   ├── index.html
│   ├── mix-and-match
│   ├── new-blog-who-dis
│   ├── robots.txt
│   ├── rss
│   ├── sitemap-authors.xml
│   ├── sitemap-pages.xml
│   ├── sitemap-posts.xml
│   ├── sitemap-tags.xml
│   ├── sitemap.xml
│   ├── sitemap.xsl
│   ├── tag
│   └── tip-for-google-summer-of-code-applications
└── versions
    └── 2.14.3
```

Do you think anything is missing from this?

**Comment by anujdeshpande** [comment]
Are there any other logs that I can share?

**Comment by sjolicoeur** [comment]
@anujdeshpande 

I think I know what may be happening you should check where your `current` sym link  points to. The path may be wrong and thus prevent ghost from starting. I don't know if there is a `ghost doctor` or any other command to fix this.

**Comment by acburdine** [comment]
@anujdeshpande apologies for the delayed response. Based on the output above, I would think the issue definitely is the fact that the `current` symlink isn't set up at all - you'll need to create one that links to `./versions/2.14.3`. My guess is that airdrop wouldn't copy over symlinks, as those tend to get messed up sometimes when migrating from one system to another.

**Comment by acburdine** [comment]
Going to close this for now as I'm 90% sure this isn't a problem we can really solve in the CLI. If you continue to have issues, please try using the [forum](https://forum.ghost.org) if issues persist 😄

**Comment by anujdeshpande** [comment]
Just FYI for anyone who comes across something like this - I created a new ghost local project and manually copied the folders, except the `versions` and `current` sym link. It worked, and I was okay with bumping the ghost version for my installation so no hard feelings too :)
